apache/trafodion

core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/OptimizerSimulator.cpp

Fix [TRAFODION-1]: the number of Scan level ESP processes is too restrictive.

Allow scan esps to take # of partitions.

---

dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestBasic.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestBatch.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestBigCol.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestCat.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestMisc.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestTrx.java

[TRAFODION-11] Added copyright statements and some comments.

---

core/sqf/export/include/dtm/tm.h
core/sqf/export/include/dtm/tmtransaction.h
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/RMInterface.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java
core/sqf/src/seatrans/tm/hbasetmlib2/HBaseTxClient.java
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.h
core/sqf/src/tm/tm.cpp
core/sqf/src/tm/tmddlrequests.cpp
core/sqf/src/tm/tmddlrequests.h
core/sqf/src/tm/tmlib.cpp
core/sqf/src/tm/tmlibmsg.h
core/sqf/src/tm/tmrmhbase.cpp
core/sqf/src/tm/tmtransaction.cpp
core/sql/executor/HBaseClient.java

Addition of TM support for DDL Alter Table

TM Support for DDL Alter Table

---

core/sql/executor/HBaseClient_JNI.cpp
core/sql/optimizer/NAClusterInfo.cpp
core/sql/optimizer/NATable.cpp
core/sql/optimizer/NodeMap.cpp
core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/regress/core/EXPECTEDRTS
core/sql/regress/seabase/EXPECTED016

This fixes three problems described in JIRA TRAFODION-15.

ESP-colocation fixes (Ravisha and Qifan)

---

core/conn/jdbc_type2/src/main/java/org/trafodion/jdbc/t2/SQLMXStatement.java
core/conn/jdbc_type4/src/org/trafodion/jdbc/t4/TrafT4Statement.java

Check the closed statement object status failed, always get false.
Change-Id: Ifa881efffb9bce01af155d78eea4d123466910bb

[TRAFODION-17]Check the closed status of statement

---

install/installer/traf_setup

Removed a package we no longer need to install, mostly for testing purposes.

Testing with small change

---

core/sql/sqlcomp/CmpDescribe.cpp

[TRAFODION-36] showddl does not show delimited names in ON subclause of SALT clause

---

core/sqf/sqenvcom.sh
core/sqf/sql/scripts/ckill
core/sqf/sql/scripts/sqcore
core/sqf/sql/scripts/sqgen
core/sqf/sql/scripts/sqipcrm
core/sqf/sql/scripts/sqpstack
core/sqf/sql/scripts/sqstop
core/sqf/sql/scripts/update_sql
core/sqf/tools/sqtools.sh
dcs/bin/master-backup.sh
dcs/bin/servers.sh
dcs/bin/start-dcs.sh
dcs/bin/stop-dcs.sh
dcs/bin/zookeepers.sh

Changes to Trafodion core scripts effected by pdsh error.

[TRAFODION-1433] Changes for pdsh errors in Core 

---

core/Makefile
core/rest/pom.xml
dcs/pom.xml

Maven should pull jdbc jar files from local build, not
from previous release on trafodion.org.

[TRAFODION-1437] Maven dependencies on JDBC local build

---

win-odbc64/odbcclient/drvr35/cstmt.cpp

Add "UPSERT" statement type supports.

[TRAFODION-1447]Windows ODBC Driver not able to process "UPSERT" statement

---

core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/HBaseClient.java
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/executor/HTableClient.java
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h

Reduced the number of JNI to java transitions and
memory allocation by streamlining the Trafodion-HBase
client layer for IUD commands
Also removed unreferenced code and variables in this layer.

[TRAFODION-1444] Reduced pathlength for IUD

---

core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/ExHbaseSelect.cpp
core/sql/executor/HBaseClient.java
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h

Refactored the code to ensure that HTableClient object in java
is released for every batch of gets.
In the process removed unused code in HBaseClient_JNI.cpp and
ExpHbaseInterface.cpp

[TRAFODION-1448] Leak in HTableClient objects

---

core/sql/optimizer/BindRelExpr.cpp

Change is in the binder, on how characteristic inputs are assigned.

[TRAFODION - 1456] Fix for rowset upsert into table with index assert. 

---

core/sql/generator/GenPreCode.cpp
core/sql/optimizer/SearchKey.cpp
core/sql/optimizer/SearchKey.h
core/sql/optimizer/SimpleScanOptimizer.cpp
core/sql/optimizer/disjuncts.h
core/sql/optimizer/mdam.cpp
core/sql/regress/seabase/EXPECTED010

Please pull the request.  Thanks!

fix #JIRA 1449: missing end key.

---

core/sql/optimizer/CostMethod.h
core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/RelUpdate.h
core/sql/optimizer/ScmCostMethod.cpp
core/sql/optimizer/costmethod.cpp
core/sql/optimizer/opt.cpp
core/sql/regress/compGeneral/TEST071

First implementation of INSERT cost method.

[TRAFODION-25] First implementation of INSERT cost method

---

core/sql/optimizer/Cost.cpp
core/sql/optimizer/Cost.h
core/sql/optimizer/ScanOptimizer.cpp
core/sql/optimizer/disjuncts.h
core/sql/optimizer/mdam.cpp
core/sql/regress/seabase/EXPECTED011
core/sql/regress/seabase/FILTER011
core/sql/regress/seabase/TEST011

Please refer to comments here for the description of the bug and the rational for the fix. Thank you.

[TRAFODION-1468] missing MDAM plan

---

install/installer/tools/cloudera_setup

Adding small change to allow Cloudera to install from a local repo

Small bug fix to allow Cloudera to install from Local Repo

---

core/sqf/sql/scripts/install_apache_hadoop
install/installer/traf_apache_hadoop_config_setup
install/installer/trafodion_apache_hadoop_install

TRAFODION-1451: Vanilla hadoop support for installer

---

core/sql/generator/GenUdr.cpp
core/sql/optimizer/NAColumn.cpp
core/sql/optimizer/NAColumn.h
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/src/main/java/org/trafodion/sql/HTableClient.java

Please see JIRA issues for information on each fix.
The files are
1482: HTableClient.java
1474: GenUdr.cpp
1279:NaColumn.h, NAColumn.cpp, CmpSeabaseDDLtable.cpp

[TRAFODION-1482] [TRAFODION-1474] [TRAFODION-1279]

---

core/conn/unixodbc/odbc/odbcclient/unixcli/package/license.txt
dcs/conf/dcs-site.xml
tests/phx/phoenix_test.py
tests/phx/pom.xml.template

Updated license file for Linux Driver

[TRAFODION 1511] Phoenix tests when using T2 driver fails with Index out of range error

---

dcs/src/main/java/org/trafodion/dcs/servermt/ServerConstants.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverDriverInputOutput/Descriptor2.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverDriverInputOutput/Descriptor2List.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverDriverInputOutput/SQLWarningOrError.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverDriverInputOutput/Version.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiGetCatalogs.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlExecDirect.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlExecute.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlFetch.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlPrepare.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlSetConnectAttr.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafConnection.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafResultSet.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafStatement.java
dcs/src/main/java/org/trafodion/dcs/util/SqlUtils.java

[TRAFODION-1515] MT DCS - Support for multiple resultsets

---

install/installer/traf_config_check

HADOOP_PATH was not being set in config file.

[TRAFODION 1539] HADOOP_PATH will now be set

---

dcs/src/main/resources/dcs-webapps/master/servers.jsp
dcs/src/main/resources/dcs-webapps/static/dcs.css

The way to know what kinds of configurations it has on DCS. More people ask for it. Enjoy.

[TRAFODION-1561]List all configurations

---

core/rest/pom.xml
core/sqf/sqenvcom.sh
dcs/pom.xml
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestCat.java

The release1.3 branch is created. This will now distinguish the master
branch as preparing for 2.0 release.

Change release version from 1.3 to 2.0

---

install/installer/traf_cloudera_mods98
install/installer/traf_getHadoopNodes
install/installer/traf_hortonworks_mods98

Copying files and changing permissions.

[[ TRAFODION 1576 ]] Backup-restore installer support

---

core/sql/bin/SqlciErrors.txt
core/sql/cli/Cli.cpp
core/sql/comexe/ComTdbExeUtil.h
core/sql/common/CharType.h
core/sql/executor/ExExeUtilLoad.cpp
core/sql/exp/ExpLOBaccess.cpp
core/sql/exp/ExpLOBenums.h
core/sql/generator/GenRelExeUtil.cpp
core/sql/generator/GenRelSample.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/NATable.cpp
core/sql/optimizer/RelExeUtil.h
core/sql/optimizer/RelSample.cpp
core/sql/parser/sqlparser.y
core/sql/regress/executor/EXPECTED130
core/sql/regress/executor/TEST130
core/sql/sqlcomp/CmpDDLCatErrorCodes.h
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

TRAFODION-1604 - Fixed one place in CharType.h where 100 was the max limit for lob handle length
TRAFODION-1596 - Added checks in alter code to prevent altering adding LOB columns.
TRAFODION-1598 - Added several syntax filxes in parser and ExpLOBaccess.cpp to address these problems.
TRAFODION-1599 - Added checks in binder to prevent sample columns from being LOB columns.
TRAFODION-1602 - Added checks in DDL layer to prevent LOB columns as unique constraints or store by.

Resolving the following JIRAs related to LOB feature :

---

core/sqf/sqenvcom.sh

Removed mvn in path check from sqenvcom.sh

Fix for TRAFODION-1623

---

core/sqf/sqenvcom.sh

copying fix for TRAFODION-1623 from release1.3 branch to master branch

Fix for Trafodion 1623

---

core/sqf/sql/scripts/gensq.pl
core/sqf/sql/scripts/lobstart
core/sqf/sql/scripts/makemsg.ksh

Includes change from Narendra for starting lob process when a node is intergrated.(gensq.pl)

TRAFODION-1635. Changes to a few script related sql message file and to lob startup.

---

core/sqf/sql/scripts/cleanat

from the instance.
This is in response to JIRA 1644

Adding cleanat script to clean the TLOG audit tables

---

core/sqf/src/tm/tools/dtmci.cpp

Errors were not being checked after the TMSTATS call for the "json" case.

TRAFODION-1626 fix for dtmci statis -j

---

tests/phx/src/test/java/org/trafodion/phoenix/end2end/BaseTest.java
tests/phx/src/test/java/org/trafodion/phoenix/end2end/BatchTest.java

1. BatchInsert positive test case added into phoenix
2. BatchInsert negative test case added into phoenix

[TRAFODION-1659] Need Batch test cases in JDBC Phoenix tests

---

win-odbc64/odbcclient/update_version.pl

[TRAFODION-1666]Need a script to update the version of windows ODBC

[TRAFODION-1666]script to update win-odbc version

---

dcs/src/main/java/org/trafodion/dcs/master/listener/ConnectReply.java
dcs/src/main/java/org/trafodion/dcs/servermt/ServerUtils.java

It's useless to be DISCONNECTED since nothing is done between DISCONNECTED and AVALIBLE.
And seems to be not reasonable to sleep 30s.
Tested on while(true){connect/close} without sleeping and it successfully did hundreds times.

[TRAFODION-1656]Remove DISCONNECTED& refactor some code

---

dcs/src/main/java/org/trafodion/dcs/servermt/ServerUtils.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerHandler.java

Replace host name with external IP address in zookeeper content

[TRAFODION-1665]connection failed with mtdcs on

---

install/installer/traf_getHadoopNodes

[TRAFODION-1642] License issue fixes

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java

after hbase-0.98.8(include 0.98.8), the instantiation process of ScanInfo(class) is different from before, which need KeepDeletedCells(enum) as parameter instead of boolean.

TRAFODION-1643

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java

after hbase-0.98.9(include 0.98.9), the instantiation process of ScanQueryMatcher(class) is different from before, which add one long class as parameter.

TRAFODION-1650

---

docs/src/site/markdown/website.md

There is more to this JIRA. Just adding one small documentation update.

[TRAFODION-1699] Update website publishing instructions

---

win-odbc64/odbcclient/update_version.pl

update the scirpt to make it can update the version number in build_os.bat
and the inno setup script.

[TRAFDOION-1666]script to update win-odbc version

---

install/installer/trafodion_install

Adding full path for kernel.pid_max.
Adding call for traf_sudoAccess for DCS HA.

[[TRAFODION 1694]] [[ TRAFODION 1689]]

---

core/sqf/sql/scripts/findPort.py
core/sqf/sql/scripts/install_local_hadoop

With this option, the port range is chosen randomly from the list returned reported by findPort.py script.

A new option "-p available" to install_local_hadoop. 

---

core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

[TRAFODION-1618] Fix row estimation to scale to more than 255 columns

---

dcs/bin/start-dcs.sh
dcs/bin/stop-dcs.sh

Before fixes it might be:
[poc@esgvm-8 dcs]$ ./bin/dcs --config /data/esgyndb/traf-plus/dcs/bin/../conf org.trafodion.dcs.zookeeper.ZkUtil /poc/dcs/master
15/12/22 01:33:49 DEBUG zookeeper.ZkClient: ZooKeeper Servers:localhost:2181,SessionTimeout:180000,MaxRetries:3,RetryIntervalMillis:1000
15/12/22 01:33:49 DEBUG zookeeper.ZkClient: Zookeeper.State=CONNECTING
15/12/22 01:33:50 DEBUG zookeeper.ZkClient: Zookeeper.State=CONNECTED
esgvm-8.novalocal

[TRAFODION-1719]Got needed info

---

core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/NADefaults.h
core/sql/sqlcomp/nadefaults.cpp

fix JIRA-1739 to aggressively allocate ESPs.

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionRegionLocation.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionState.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java

UnknownTransactionException in prepare causes error 97

Fix for JIRA TRAFODION-1748

---

core/sql/optimizer/NATable.cpp

Using the "reportError" parameter in the underlying method to avoid
generating an error when we just want to test whether a certain
object name is registered in the OBJECTS table.

[TRAFODION-1747] Avoid generating SQL errors in successful statements.

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionObserver.java

Rework of Region Split/Move code.  Enhanced error handling and ability to split/move with active transactions.

TRAFODION-1648 Region Split/Move work

---

dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafStatement.java

[TRAFODION-1774][MT-DCS]use hashCode() instead of random to make the
stmtHandle is unique

[TRAFODION-1774]use hashCode instead of random

---

dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlExecute.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafStatement.java

close all previous results before starting a new query

[TRAFODION-1780][MTDCS]jPrepareStatement execute twice, second ResultSet is empty

---

core/sqf/sqenvcom.sh
core/sqf/sql/scripts/install_apache_hadoop
core/sqf/sql/scripts/install_hadoop_regr_test_env
core/sqf/src/seatrans/hbase-trx/Makefile
core/sqf/src/seatrans/hbase-trx/pom.xml.apache
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/SsccTransactionalTable.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionalTable.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/SingleVersionDeleteNotSupported.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java

change getFamilyMap() to getFamilyCellMap()
add ScanQueryMatcher instantiation for hbase 0.98.9 and later version
change ScanInfo instantiation for hbase 0.98.8 and later version

support vanilla hbase 0.98.10

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/generated/TrxRegionProtos.java
core/sqf/src/seatrans/hbase-trx/src/main/protobuf/TrxRegion.proto
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/TmAuditTlog.java

Lower overhead in deleting old Tlog entries

Fix for [TRAFODION-1703]

---

core/rest/src/main/asciidoc/_chapters/apis.adoc
core/sqf/sql/scripts/sqcheck

Change details in JIRA 
https://issues.apache.org/jira/browse/TRAFODION-1785

Add DCSMaster status to sqcheck json output

---

core/rest/src/main/asciidoc/_chapters/apis.adoc
core/rest/src/main/java/org/trafodion/rest/ServerResource.java

Changes for JIRA https://issues.apache.org/jira/browse/TRAFODION-1797

Add new REST API to display DCS configuration summary

---

core/rest/src/main/java/org/trafodion/rest/ServerResource.java

Fix for TRAFODION-1814 : REST Servers' pstack API does not return pstack information of process
https://issues.apache.org/jira/browse/TRAFODION-1814

Fix for REST Server pstack api

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java

Fixes the following scenario which resulted in a hang.
Begin work;
insert into table t  values( 1);
drop table t;
commit work;
In this scenario, as part of commit, the drop table t gets hadmin:disabled in prepare phase followed by hadmin delete in commit phase. However, because there was a insert to table, commit phase encounters the disabled table. Fix is to detect this exception in the commit thread and validate against the drop table list maintained in TmDDL log.

TRAFODION-1798 This change is item 2( of 4 items ) listed in jira

---

core/sql/regress/privs1/EXPECTED132
core/sql/regress/privs1/TEST132
core/sql/regress/tools/runregr_privs1.ksh
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp
core/sql/sqlcomp/PrivMgrMD.cpp

Activated privs1 regression test 132. This tests privileges on various 
utilities.

TRAFODION-1832: Add privilege regression test 132

---

core/conn/unixodbc/odbc/odbcclient/unixcli/package/LICENSE
core/sqf/LocalSettingsTemplate.sh
core/sqf/sqenvcom.sh
core/sql/SqlCompilerDebugger/mk.sh
core/sql/nskgmake/SqlCompilerDebugger/Makefile

Also clean up symlink to obsolete directory.

[TRAFODION-1840] Disable bundling of Qt libs into packaging

---

core/sqf/sql/scripts/genstats.sh
core/sql/executor/hiveHook.cpp

Hi,
This is to push the genstats.sh and the looping compiler fix to the Trafodion branch. 
Please review and commit.
Thanks --Qifan

Genstats script and fix to JIRA 1872 (looping compiler)

---

core/sqf/sql/scripts/gensq.pl
core/sqf/sql/scripts/sqnodeipcrm

[TRAFODION-1860,1875]

---

core/sql/ustat/hs_globals.cpp

When CQD USTAT_ESTIMATE_HBASE_ROW_COUNT was set to 'ON' and when sampling was not used and when logging was not used, we would sometimes get 0 UEC counts. This was due to defective tests in the code to determine if sampling was used. Fixed these tests. Also added code to correct the actual row count when the estimate we get from HBase is wrong.

[TRAFODION-807] Fix for zero UEC counts

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/NATable.cpp
core/sql/regress/privs2/EXPECTED135
core/sql/regress/privs2/TEST135
core/sql/sqlcomp/CmpSeabaseDDLview.cpp

The create view code is looking for SELECT privilege on sequence generators 
but Trafodion only allows USAGE privilege to be specified.

TRAFODION [1806] - create view with sequence failed with ERROR[4481] though the  user has been granted usage privilege

---

core/rest/src/main/java/org/trafodion/rest/ServerResource.java

TRAFODION-1934 REST Server node status api should use trafnodestatus script

Change RESTServer node status to report trafodion up/down status

---

core/sqf/sql/scripts/sqnodestatus
install/Makefile
install/installer/acceptKeys

Removing tools directory for installer makefile (tools should only be used for dev)
Adding new acceptKeys script to easily create known_host file

[[TRAFODION 1932]] Fixing sqnodestatus

---

.rat-excludes
core/conn/odb/odb.sln
core/conn/odb/odb/odb.vcxproj
core/conn/odb/odb/odb.vcxproj.filters
core/conn/odb/odb/odb.vcxproj.user
core/conn/odb/src/memcpy_wrapper.c
core/conn/odb/src/odb.c
core/conn/odb/src/verslib.h
core/conn/odb/src/versodb.c

add Visual Studio project files to support compile odb in windows platform

[TRAFODION-1931]ODB tool support windows platform

---

docs/src/site/markdown/index.md
docs/src/site/resources/css/site.css
docs/src/site/site.xml

See discussion on dev list. 
Please updated the website. There's no need to rebuild the documentation.

Highlighting the incubation status of the project.

---

core/sqf/sqenvcom.sh
core/sql/nskgmake/Makerules.mk
core/sql/regress/core/FILTER116

The 2.0 release is now on side branch.
Also fix a parallel-build bug when multiple commands were copying
the same files to same destination. Fix is to make file pattern
specific to each build task.

Bump release number to 2.1 on master branch

---

core/rest/pom.xml
core/rest/src/assembly/all.xml

Include jetty-security jar in REST server packaging.

Fix for JIRA 1953

---

.gitattributes

This will allow these directories to be included in source package,
and hence in the official released code.
Note that it also includes the website pages, which provides a snapshot
in time of the project site, for whatever that is worth.

[TRAFODION-1972] Remove docs directories from exclude list

---

install/traf_tools_setup.sh

Issue found while testing build environment setup for release 2.0.
Simple fix.

[TRAFODION-1973] Fix unpacking of hadoop dependencies

---

core/sql/generator/GenRelExeUtil.cpp
core/sql/regress/hive/EXPECTED015
core/sql/regress/hive/TEST015

Delimited name was being sent during load complete.

TRAFODION-1963 Create index with delimited name fails if table has data

---

core/sql/lib_mgmt/src/main/java/org/trafodion/libmgmt/FileMgmt.java

Merge library management fix from master to R2.0

Merge library management fix from master to R2.0

---

core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

Additional changes and bug fix
Removed ByteArrayList JNI class

[TRAFODION-1955] JNI optimization at the time of compilation

---

core/sqf/src/tm/tmlib.cpp
core/sqf/src/tm/tmtx.cpp

Commit conflicts should not be reported as FELOCKED

Fix for JIRA [TRAFODION-1991].

---

core/sql/comexe/ComTdbFastTransport.cpp
core/sql/executor/ExExeUtilMisc.cpp
core/sql/executor/ExFastTransport.cpp
core/sql/executor/ExHdfsScan.cpp
core/sql/generator/Generator.cpp
core/sql/optimizer/RelExeUtil.cpp
core/sql/regress/hive/EXPECTED003
core/sql/regress/hive/EXPECTED005
core/sql/regress/hive/EXPECTED018
core/sql/regress/hive/TEST005
core/sql/regress/tools/runallsb

In addition to purgedata:
-- showplan correctly shows aqr setting
-- data modification check is skipped during insert if overwrite
option was used

JIRA TRAFODION-2022 Add support for purgedata of hive tables

---

core/sqf/sqenvcom.sh
core/sql/regress/core/FILTER116

Patch release for linking SSL libraries.

Bump Release number to 2.0.1

---

.gitignore
.rat-excludes
core/sqf/.gitignore
core/sqf/Makefile
licenses/Makefile

TRAFODION-2068: Missing DISCLAIMER files for release package
Added DISCLAIMER file to servers package.

Fixes for TRAFODION-2068

---

core/sql/sqlcomp/CmpSeabaseDDLroutine.cpp

Thank you Steve Varnau for finding this mistake.

[TRAFODION-2039] Fix mistake in PR530 https://github.com/apache/incubator-trafodion/pull/530

---

docs/src/site/markdown/download.md

Preparing web-site for 2.0.1 release. These links will not work until release has officially been approved and artifacts posted. Merge this PR and update website after release is approved.

Download links for 2.0.1 release

---

core/sqf/sql/scripts/install_local_hadoop

Change swstatus to give a simple "up" or "down" answer, instead of the current, confusing display

[TRAFODION-1609]

---

docs/shared/license.txt
docs/shared/revisions.txt
docs/src/site/markdown/index.md
docs/src/site/resources/css/site.css
docs/src/site/site.xml

- Updated branding per recommendations from a discussion in the general list.
- Updated news section for 2.0.1 release.
- Updated revisions for 2.0.1 release.
Please rebuild the documentation and the website.

Modified website

---

core/sql/regress/executor/EXPECTED022.SB

Modify the EXPECT file for executor/TEST022 which broke the regression test.
Sorry that I didn't do a full regression before check-in, should do 'Jenkins, extra tests' to trigger more tests.

[TRAFODION-1676] rework to solve TEST022 failure

---

install/Makefile

Portion of this JIRA previously taken care of with Anu's change.
Will likely also backport these changes to release2.0 branch in case we need another 2.0.x patch release.

[TRAFODION-2092] Include "incubating" in installer package name

---

core/sql/exp/exp_function.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ItemExpr.cpp
core/sql/regress/seabase/EXPECTED030
core/sql/regress/seabase/EXPECTED031
core/sql/regress/seabase/TEST030
core/sql/regress/seabase/TEST031
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

-- TRAFODION-1843: allow 'default user' in create table statement
-- TRAFODION-2106: fix bug with use of to_date function in where clause

JIRA TRAFODION-1843 TRAFODION-2106

---

.gitignore
core/conn/Makefile
core/sqf/.gitignore
core/sqf/Makefile
core/sql/common/swscanf.cpp
core/sql/common/swsprintf.cpp
install/Makefile
licenses/Makefile
licenses/lic-server-src

Final changes for 2.0.1 release merged forward.

[TRAFODION-1977] Merge forward release2.0 changes to master

---

core/sql/regress/core/FILTERRTS

Some of the filter conditions were reporting error when it was
applied on both the expected and log output.

[TRAFODION-2110] core/TESTRTS is being incorrectly flagged as PASSED

---

docs/jdbct4ref_guide/src/asciidoc/_chapters/introduction.adoc
docs/load_transform/src/asciidoc/index.adoc
docs/messages_guide/src/asciidoc/_chapters/introduction.adoc
docs/odb_user/src/asciidoc/_chapters/about.adoc

In hope of practicing the commit and publish process.

Minor formatting updates.

---

core/sql/optimizer/NormRelExpr.cpp

A missing ">" character caused us to do an unnesting transformation
without having uniqueness constraint on the main query.
Note that this is a rare case, since most tables have unique columns
and since the code tries to get those unique columns if they are not
already included.

[TRAFODION-2130] Incorrect subquery unnesting

---

core/sql/regress/compGeneral/EXPECTED001.SB

Fix regression test case failure. 
Should be more carefully next time.

fix regression test compGeneral TEST001

---

core/sql/sqlcat/TrafDDLdesc.cpp
core/sql/sqlcat/TrafDDLdesc.h
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLschema.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

Code now handles writing binary data into TEXT after encoding it.
And decodes it during read.
Non-binary data is added using input params  instead of literals.

JIRA-2137 Addnl change to metadata improvement based on review comments

---

core/sql/common/OperTypeEnum.h
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelSet.h
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED001.SB
core/sql/regress/compGeneral/TEST001

initial support of SQL syntax EXCEPT

[TRAFODION-2117] add SQL support of EXCEPT

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java

Changes as per the review comments of PR 645

[TRAFODION-2129] Trafodion to avoid use of deprecated HBase APIs/Classes

---

core/conn/jdbc_type2/native/CoreCommon.h
core/conn/jdbc_type2/native/SQLMXConnection.cpp
core/conn/jdbc_type2/native/SrvrOthers.cpp

this jira has been merged in #561, but it is strange the changed code in apache/master disappeared. so i do a PR again.
add seesion to each connection.

TRAFODION-1743 add connection session

---

core/sqf/sql/scripts/ckillall

ckillall should remove the confused warning message

[TRAFODION-2183] remove warning in ckillall

---

core/sql/generator/GenShape.cpp
core/sql/optimizer/RelRoutine.cpp
core/sql/optimizer/RelRoutine.h
core/sql/sqlcomp/CmpDescribe.cpp

The JIRA talks about both showshape and CQS. The CQS part
was fixed with TRAFODION-2190, this is the fix for showshape.

[TRAFODION-2147] showshape does not work for TMUDFs

---

tests/phx/pom.xml.template

[TRAFODION-2206] Fix phx T2 test references to trafodion jar files

---

core/sql/exp/exp_datetime.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/regress/core/EXPECTED038.LINUX
core/sql/regress/executor/EXPECTED022.SB
core/sql/regress/seabase/EXPECTED030

rework of the JIRA, in previous code, it get display string length using strlen(), but the srcData is not null-terminated for sure, so it will randomly get some unknown content.
And also refactor the previous code for better coding rule.
This should address the sql regression failure of executor/TEST022.

[TRAFODION-1676] rework, fix executor regression test022 failures

---

core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp

Changes in mxosrvr to handle null terminator in explain plan
as needed by the following pull request:
https://github.com/apache/incubator-trafodion/pull/694
Without these changes execution of queries with plans > 50K fail with error 8887:
*** ERROR[8887] The provided buffer to retrieve generated code or explain data
is either null or not big enough.

[TRAFODION-1755] - Additional changes to handle error 8887.

---

core/sqf/export/include/seabed/mslimits.h
core/sqf/monitor/linux/msgdef.h
core/sqf/sql/scripts/sqnodes.pm

The installer also has changes to allow the limits increase.

[TRAFODION-2233] Increased the number of cores limit to 256

---

core/sqf/sql/scripts/cleanZKNodes
core/sqf/sql/scripts/install_local_hadoop
core/sqf/sql/scripts/sqstart

JIRA [TRAFODION-2236]

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java.tmpl
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionObserver.java.tmpl
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TransactionState.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java.tmpl

Fixes are part of JIRA [TRAFODION-1435]

Recovery changes for region transaction changes

---

docs/src/site/markdown/index.md
docs/src/site/site.xml

Removed meetup notification.
Added Roadmap link in top menu.
Updated news.

Website Updates

---

core/sqf/sql/scripts/rmscheck

rmscheck should use relative path of sql file location.

[TRAFODION-2278] rmscheck should use relative path

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestForeignKey.java

Fix the error of the old implementation and add test cases for it.

[TRAFODION-1698]ODBC: trafodon doesn't support SQLForeginKeys

---

core/sqf/sql/scripts/install_local_hadoop

add restrict in install_local_hadoop

[TRAFODION-2293] remove minor version for the hbase-trx-apache_*.jar

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/RMInterface.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionState.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java
core/sql/src/main/java/org/trafodion/sql/HTableClient.java

Avoided calling System.getenv() many times

[TRAFODION-2325] Reduce path length by avoiding expensive APIs

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java.tmpl

TransactionState.hasConflict gets a null pointer exception

Fix for [Trafodion-2348]

---

core/sql/sqludr/sqludr.cpp
core/sql/sqludr/sqludr.h

add code to support "double" as a output column type.

jira 2354 : TMUDF doesn't support "double" as a output column type.

---

core/sqf/export/include/common/evl_sqlog_eventnum.h
core/sqf/monitor/linux/cluster.cxx
core/sqf/monitor/linux/zclient.cxx
core/sqf/monitor/linux/zclient.h

[TRAFODION-2235] Changed EPOLL logic and ZClient to handle transient

---

install/installer/traf_start

Using Amanda's recommended fix.

[TRAFODION-2256] installer not detecting true init errors

---

core/conn/jdbcT4/pom.xml
core/sqf/.gitignore
core/sqf/Makefile
core/sqf/build-scripts/genverhdr.ksh

Fix for jdbcT4 build errors. 
Eliminates  git dependency when building from src package

TRAFODION-2357 log4c++ build error

---

core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

When ALTER TABLE RENAME is done on a table having an IDENTITY column, the sequence name of the IDENTITY column was not updated. That caused DML which requires sequence values (e.g., INSERT) to fail. This code change adds logic to take care of renaming the sequence name for IDENTITY columns.

[TRAFODION-2371] Fix ALTER TABLE RENAME for IDENTITY columns

---

core/sql/optimizer/ItemExpr.cpp
docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

this is a resbumit PR of PR 837: https://github.com/apache/incubator-trafodion/pull/837
Fix all code review comments in PR 837 , and combined all the changes into one commit.

[TRAFODION-2355] document about IP address/hashing functions

---

core/sqf/src/seatrans/hbase-trx/pp.awk

Make awk script extensible to support any number of distro variations.
Also support #elseif  define.

[TRAFODION 2381] Enhance awk script to support many variations of distros

---

.rat-excludes
dcs/src/test/odbc/README.txt
dcs/src/test/odbc/build/Makefile
dcs/src/test/odbc/build/odbc.vcxproj
dcs/src/test/odbc/build/odbc.vcxproj.filters
dcs/src/test/odbc/src/Main.cpp
dcs/src/test/odbc/src/common/Global.cpp
dcs/src/test/odbc/src/common/Global.h
dcs/src/test/odbc/src/common/TestBase.cpp
dcs/src/test/odbc/src/common/TestBase.h
dcs/src/test/odbc/src/test/varchar32k/LargeVarcharCol.cpp
dcs/src/test/odbc/src/test/varchar32k/LargeVarcharCol.h

Add source code, build files and readme files, and test code runs in following way:
Every time 1 row of data is inserted to a specific table and fetched out into local buffer after insertion is done. And then comparation is made between input buffer and fetch-out buffer, if difference exists, then test fails.

[TRAFODION-2386]ODBC:add odbc unit-test code for large varchar column issue

---

core/sql/executor/ExExeUtilLoad.cpp
core/sql/regress/hive/EXPECTED018

Unload command returned invalid start time in the output for its tasks.

[TRAFODION-2351] Bulk load with log error rows enhancements

---

core/conn/trafci/Makefile
core/conn/trafci/install/Installer.java-tmpl

replace TRAFCI_CLASSPATH in trafci.sh, previous is absolute path, now is ${TRAF_HOME}/traf/lib/xx.jar

TRAFODION-2402

---

.rat-excludes
install/Makefile
install/python-installer/prettytable.py
install/python-installer/scripts/httplib2/__init__.py
install/python-installer/scripts/httplib2/iri2uri.py
install/python-installer/scripts/httplib2/socks.py
licenses/Makefile
licenses/lic-pyinstall-src

@svarnau, please help to review.

[TRAFODION-2431] python installer - add python lib dependencies

---

core/sql/regress/hive/FILTER005

FILTER file that was missed out as part of PR 931

[TRAFODION-2351] Bulkload enhancements

---

core/sql/regress/hive/EXPECTED009
core/sql/regress/hive/TEST009
core/sql/regress/privs1/EXPECTED123
core/sql/regress/privs1/TEST123

Added new regression test privs1/TEST123

Trafodion-2175

---

install/python-installer/db_install.py
install/python-installer/scripts/traf_setup.py

[TRAFODION-2479] pyinstaller - firewall status should not block the installation process

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

1. Add "CREATE SEQUENCE Statement", "DROP SEQUENCE Statement" & "ALTER SEQUENCE Statement".
2. Update "CREATE INDEX Statement".

[TRAFODION-2412] Add CREATE/DROP/ALTER SEQUENCE Statement + Update CREATE INDEX Statement

---

core/sqf/sqenvcom.sh

Changing the minor version of Trafodion master to 2 since the 2.1 branch is now  created.

Changing minor version for main branch to 2.

---

core/sqf/monitor/linux/pnode.cxx
core/sqf/monitor/linux/pnodeconfig.cxx
core/sqf/monitor/linux/pnodeconfig.h
core/sqf/monitor/linux/shell.cxx

cherry pick from esgyndb.
@narendragoyal , please review.

[TRAFODION-2480] monitor should not check hostname strictly

---

install/python-installer/scripts/traf_sqconfig.py
install/python-installer/scripts/traf_start.py

[TRAFODION-2489] pyinstaller - sqconfig on single node
[TRAFODION-2490] pyinstaller - admin user setup gives syntax error

[TRAFODION-2489] [TRAFODION-2490] fix for pyinstaller

---

docs/sql_reference/src/asciidoc/_chapters/olap_functions.adoc

1. Add details for OLAP function.
2. Add LEAD, LAG, FIRST_VALUE & LAST_VALUE window functions.

[TRAFODION-2520] Add details for OLAP function + Add LEAD, LAG, FIRST_VALUE & LAST_VALUE window functions

---

docs/sql_reference/src/asciidoc/_chapters/olap_functions.adoc

Make sure that these changes are included in the 2.1 documentation.

Cherry-pick two documentation changes from 2.2 into 2.1

---

install/python-installer/configs/db_config_default.ini
install/python-installer/configs/prompt.json
install/python-installer/db_install.py
install/python-installer/db_uninstall.py

[TRAFODION-2519] pyinstaller - uninstaller should kill all trafodion processes.

[TRAFODION-2518] pyinstaller - remove unused db_admin settings.

---

core/conn/trafci/install/Installer.java-tmpl
core/conn/trafci/src/main/java/org/trafodion/ci/QueryWrapper.java

[TRAFODION-2462] TRAFCI gui installer does not work

---

core/conn/jdbcT4/pom.xml

jdbcT4 profile configuration for publish to maven central

jdbcT4 profile configuration for publish to maven central

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_language_elements.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

[TRAFODION-2522] Add WITH Clause

---

docs/cqd_reference/src/asciidoc/_chapters/query_execution.adoc

[TRAFODION-2521] Add SCRATCH_DISKS CQD

---

NOTICE
core/sqf/sqenvcom.sh
install/ambari-installer/Makefile

Added both License/Notice as well as the sqenvcom.sh change in this PR

[TRAFODION-2570],{TRAFODION-2572]  Added Notice,License, Disclaimer to amabari install RPM package

---

core/sqf/export/include/dtm/tm.h
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.h
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HashMapArray.java
core/sqf/src/tm/tm.cpp
core/sqf/src/tm/tools/dtmci.cpp

Prints the full region name, hostname:port, and startkey/endkeys in hex format.

[TRAFODION-2449] dtmci - Adding 'status regions' command

---

install/python-installer/db_install.py
install/python-installer/db_uninstall.py
install/python-installer/scripts/common.py
install/python-installer/scripts/copy_files.py
install/python-installer/scripts/hdfs_cmds.py
install/python-installer/scripts/traf_check.py
install/python-installer/scripts/traf_kerberos.py
install/python-installer/scripts/traf_setup.py
install/python-installer/scripts/traf_user.py
install/python-installer/scripts/wrapper.py

along with some other stability fixes.

[TRAFODION-2526] pyinstaller - don't use sudo command in root user during installation

---

core/sql/optimizer/BindItemExpr.cpp

The problem does not show for a query such as 
prepare ss1 from select k1 from tbl where b >= '1234567' and b < '12345678';
select k1 from tbl where b like '1234567%';
does get transformed to previous 2 range prepicates, but the histogram is compressed to one interval for all LIKE predicates. For such simple Like predicates, it is better to treat the the two range predicates 
resulting from LIKE transformation, as any other pair of range predicates.

[TRAFODION 2512] Index access with MDAM not chosen with LIKE predicate

---

core/sqf/sql/scripts/hbcheck
core/sqf/sql/scripts/sqstart
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/hbstatus.java

This code was written by Narendra Goyal.

[TRAFODION-2592] Better error message when HBase is down at startup.

---

core/conn/jdbcT4/.gitignore
core/conn/jdbcT4/Makefile
core/conn/jdbcT4/pom.xml
core/conn/trafci/installer_pom.xml
core/conn/trafci/pom.xml
core/conn/trafci/src/main/resources/install_jar.xml
core/rest/pom.xml
dcs/pom.xml

[TRAFODION-2544] JDBCT4 group id needs to be changed to org.apache.trafodion in JAR

[TRAFODION-2544] JDBCT4 group id needs to be changed to org.apache.trafodion in JAR 

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_utilities.adoc

Changes proposed in this pull request: 
Add "CLEANUP Statement".

[TRAFODION-2550] update sql reference manual about metadata clean up command

---

core/conn/trafci/src/main/java/org/trafodion/ci/ConsoleReader.java
core/conn/trafci/src/main/java/org/trafodion/ci/FCQuery.java
core/conn/trafci/src/main/java/org/trafodion/ci/ParseArguments.java
core/conn/trafci/src/main/java/org/trafodion/ci/QueryWrapper.java
core/conn/trafci/src/main/java/org/trafodion/ci/Session.java
core/conn/trafci/src/main/java/org/trafodion/ci/SessionInterface.java
core/conn/trafci/src/main/java/org/trafodion/ci/UserInterface.java
core/conn/trafci/utils/trafci.cmd-tmpl
core/conn/trafci/utils/trafci.sh-tmpl

use -j yes or no to decide whether using jline
yes means use jline
no means not use jline 
default is not use jline

TRAFODION-2462 jline not work well

---

core/sql/ustat/hs_globals.cpp

Don't call the rowcount estimation interface when the SET ROWCOUNT
option is specified, we will discard that estimate anyway.

[TRAFODION-2618] Option to skip rowcount estimation in update stats

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TmDDL.java

HBaseTxClient throws TableNotFoundException for TRAFODION._DTM_.TDDL

Fix for [Trafodion-2614]

---

docs/shared/revisions.txt

Used release date documented in board report.
This PR is for release2.1 branch!

[TRAFODION-2643] Release date for 2.1

---

docs/shared/revisions.txt

This PR is for master branch - 2.1 and 2.2 release dates

[TRAFODION-2643] Document release dates

---

core/sqf/sql/scripts/gensq.pl
core/sqf/sql/scripts/sqconfig
core/sqf/sql/scripts/sqconfig.sample

[TRAFODION-2647] Restored sqgen 'overflow' configuration section

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4ResultSet.java

there exists bug in #1098 , this PR is to fix it.

TRAFODION-2385 bug fix

---

core/sqf/monitor/linux/zclient.cxx
core/sqf/monitor/linux/zclient.h

do retry on every 'zoo_exists' call when we get a ZCONNECTIONLOSS failure.
@zcorrea , could you have to review the changes?

[TRAFODION-2664] Instance will be down when the zookeeper on name node has been down

---

core/conn/odb/src/odb.c

root cause: each thread try to call splitcso to get Catalog/Schema/Table from the same tgt buffer, but splitcso will modify tgt buffer, so only one thread can get the correct result.
fix way: 1. Catalog/Schema/Table can be determined when creating etab,  so move it forward.
2. etab[*].tgt is used elsewhere and is assumed not split, so make a copy of tgt.
3. add globalPointers to save pointers to buffers which may be shared by many thread and length determined at run time.

[TRAFODION-2677] odb load source with src=-file is failure

---

core/sql/executor/JavaObjectInterface.cpp

Character arrays used to build the options went out of scope before
they were passed to the JNI layer to create the JVM.
Selva also requested that we use the default heap size defined in
our code instead of the JVM default method of 1/4 the physical
memory when a value <= 0 is passed in env var JVM_MAX_HEA_SIZE_MB.

[TRAFODION-2682] JVM startup options like heap are not passed correctly

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

[TRAFODION-2355] fix format in sql reference document

---

core/sql/cli/sqlcli.h
core/sql/executor/ExExeUtilGetStats.cpp
core/sql/executor/ExStats.cpp
core/sql/executor/ExStats.h
core/sql/regress/core/EXPECTEDRTS
core/sql/regress/core/FILTERRTS

Added four new counters to provide information about multiple executes
of a prepared statement.
No. of times executed
Min. Execute Time
Max. Execute Time
Avg. Execute Time

[TRAFODION-2420] RMS enhancements

---

core/sql/regress/hive/EXPECTED018
core/sql/regress/hive/TEST018
core/trafodion.spec
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/params.py
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodionmaster.py
install/python-installer/scripts/hdfs_cmds.py
install/python-installer/scripts/traf_user.py

Both ambari and python installers

[TRAFODION-2697] Set bulkload permissions for hbase upload

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/sqltocconv.cpp

For our server , we need not to swap value to big endian

[TRAFODION-2687] the value of Numeric Struct need not to be changed to BidEndian

---

core/sqf/sqenvcom.sh

change the release number on the master branch to indicate it is 2.3

change the release number on the master branch to indicate it is 2.3

---

core/conn/odb/src/odb.c

root cause: careless and not tested.

[TRAFODION-2712] fix TRAFODION-2712

---

docs/odb_user/src/asciidoc/_chapters/load.adoc

[TRAFODION-2703] Add *Load XML Files* for ODB User Guide

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/cconnect.cpp

Using multi-threads app with linux-odbc to connect trafodion will make dcs down

[TRAFODION-2709] getpwuid is not a Thread-safe function

---

core/conn/odb/src/odb.c

root cause: logic error when trying to limit max rows to be copied.  AlreadyLoadRows is actually not already loaded Rows but already fetched rows. lf statement in Oloadbuff may cause less insertion. It 's better to limit max rows to be copied at fetching data.

[TRAFODION-2721] When setting max property , copy data from mysql to trafodion failed

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

1. Add an example for **ALTER COLUMN (ALTER TABLE Statement)**

[TRAFODION-2745] Add an example for *ALTER COLUMN (ALTER TABLE Statement)* in *Trafodion SQL Manual*

---

core/sql/clitest/blobtest.cpp
core/sql/regress/tools/regress-filter-linux

Fix for executor/TEST130 failure in daily build

[TRAFODION-2754] Get statistics cores sqlci or mxosrvr at str_sprintf()

---

core/sql/ustat/hs_globals.cpp

Missing TRAFODION. in metadata query.

Fix for regression failure in hive/TEST007.

---

core/conn/odb/src/odb.c

we needn't call other function which may cause odb hang again when receiving a signal, we just want to exit.

[TRAFODION-2773] When the timeout is set, odb is still hang

---

core/conn/odb/src/odb.c

1. The field enclosed in double quotes was not handled correctly before, fixed it.
2. field index now start from 1.
3. fix some other potential bug.

[TRAFODION-2714] odb does not load data correctly

---

core/sql/src/main/java/org/trafodion/sql/udr/LmClassLoader.java

load jars under UDR lib first then load trafodion env classpath

TRAFODION-2782 reserve UDRs classloader sequence

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4DatabaseMetaData.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java

Statement for metadata should be closed with connection

[TRAFODION-2786]Statement for metadata should be closed with connection

---

core/conn/trafci/src/main/java/org/trafodion/ci/ParseArguments.java
core/conn/trafci/src/main/java/org/trafodion/ci/UserInterface.java

when do trafci.sh -h there is no description for how to use jline

TRAFODION-2784 trafci help has no description for jline

---

core/sql/exp/ExpError.cpp
core/sql/regress/charsets/EXPECTED314
core/sql/regress/charsets/EXPECTED315

Expected file change for the failures observed in daily build due
to fix for the above problem

[TRAFODION-2785] mxosrvr dumps core generated when loading data

---

core/conn/jdbcT4/src/main/java/T4Messages.properties
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestWrap.java

when use jdbc there is not implement Wrapper with unwrap and isWrapperFor method

TRAFODION-2787 jdbc does not implement wrapper related api

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestNetworkTimeout.java

implement networkTimeout relate api

TRAFODION-2789 jdbc does not implement NetworkTimeout related api

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestAbort.java

TRAFODION-2790 jdbc does not implement abort related api

---

core/sql/common/ComSmallDefs.h
core/sql/sqlcomp/CmpSeabaseDDLview.cpp

1. resolve enum type conflict while merging to esgyn
Compiled and test.

new COMMENT-ON SQL statement: resolve merge conflict

---

docs/provisioning_guide/src/asciidoc/_chapters/script_install.adoc

fix minor issue in the provisioning document based on community discussion

[TRAFODION-2810] fix typo in provisioning guide

---

core/sql/optimizer/IndexDesc.cpp
core/sql/optimizer/ItemExpr.cpp
core/sql/regress/compGeneral/EXPECTED071
core/sql/regress/compGeneral/TEST071

[TRAFODION-2813] Ignore leading salt columns when checking index compatibility

---

core/sql/executor/SequenceFileReader.cpp
core/sql/regress/fullstack2/EXPECTED062.RELEASE

-- hive fix is for an earlier checkin related to java deallocation
for sequence files
-- fullstack2 is expected file update for release mode run

regr fixes for hive and fullstack2

---

core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXDataSource.java
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXDesc.java
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXPreparedStatement.java
core/conn/trafci/utils/trafci.sh-tmpl
core/sql/langman/LmSQLMXDriver.java
core/sql/src/main/java/org/trafodion/sql/udr/LmT2Driver.java
core/sql/src/main/java/org/trafodion/sql/udr/LmUtility.java
dcs/src/main/java/org/trafodion/dcs/servermt/ServerConstants.java
dcs/src/test/java/org/trafodion/dcs/IntegrationTestEndurance.java
dcs/src/test/pytests/README.rst
docs/command_interface/src/asciidoc/_chapters/launch.adoc
docs/jdbct4ref_guide/src/resources/source/blob_example.java
docs/jdbct4ref_guide/src/resources/source/clob_example.java
docs/messages_guide/src/asciidoc/_chapters/binder_msgs.adoc
docs/spj_guide/src/asciidoc/_chapters/execute_spjs.adoc
docs/spj_guide/src/asciidoc/_chapters/get_started.adoc
win-odbc64/odbcclient/drvr35/cconnect.cpp

there are some codes and comments contain HP in trafodion, like HPT4Connection，HPT4ResultSet

TRAFODION-2824

---

core/conn/trafci/utils/trafci
core/conn/trafci/utils/trafci.sh-tmpl

trafci is wrapper used mostly for development, but either script should
pick up client configuration file if present to determine host and user.

[TRAFODION-2826] Consolidate trafci defaults in trafci.sh script

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceConnection.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4Properties.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestClientInfo.java

when use jdbc there is not implement with setClientInfo and getClientInfo

TRAFODION-2788 - jdbc does not implement ClinetInfo related api

---

dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestClientInfo.java

this is for that there cann't pass jenkins test
The test cases in  previous PR do not close conn, and other case could not get conn.

TRAFODION-2823 add close to TestClientInfo.java

---

core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED045
core/sql/regress/compGeneral/FILTER045
core/sql/regress/compGeneral/TEST045
core/sql/regress/tools/runregr_compGeneral.ksh

add "LIMIT" clause support for statements create-as-select, insert-into-select and load-into-select

[TRAFODION-2804] Limit clause support in statements LOAD/INSERT/CREATE-TABLE + query

---

core/conn/jdbcT4/src/main/samples/BatchSample/BatchSample.java
core/conn/jdbcT4/src/main/samples/BatchSample/README.md
core/conn/jdbcT4/src/main/samples/TransactionSample/README.md
core/conn/jdbcT4/src/main/samples/TransactionSample/TransactionSample.java
core/conn/jdbcT4/src/main/samples/common/sampleUtils.java

some users indicate that they have no experience on how to use jdbc, they require some jdbc demos

TRAFODION-2825 add jdbc user case

---

core/conn/trafci/install/Installer.java-tmpl
core/conn/trafci/lib/python/Session.py
core/conn/trafci/samples/sampleDDL.py
core/conn/trafci/samples/sampleDML.py
core/conn/trafci/samples/sampleTables.py
core/conn/trafci/src/main/java/org/trafodion/ci/SessionInterface.java

First, Make sure that your environment is installed with Jython, then All Python examples can run when you use the rigth command. To modify the Installer.java-tmpl file to add all the jar dependent paths to the Session.py,and add the first line of each Python file.

TRAFODION-2829 the examples of python is running

---

core/sql/regress/hive/EXPECTED009

Fix for hive/TEST009 regression failure with commit 375eeeab7a

[TRAFODION-2733] BMO quota changes

---

win-odbc64/odbcclient/drvr35/sqltocconv.cpp

SQL_NUMERIC to SQL_C_CHAR
***ERROR: SQLGetData: Expected: SQL_SUCCESS Actual: SQL_ERROR
State: HY000
Native Error: 29
Error: [TRAF][Trafodion ODBC Driver] General error.EXCEPTION: UNKNOWN - Exception Code = c000001d

[TRAFODION-2818] For Server 2008, function pow() throws STATUS_ILLEGAL_INSTRUCTION

---

dcs/src/main/java/org/trafodion/dcs/master/ServerManager.java

DcsServer does not be restarted by DcsMaster on HDP.
Steps To Reproduce
1. check Hadoop and instance status
2. kill active DcsMaster
3. repeat Step 1
4. kill DcsServer on the active DcsMaster node
5. repeat Step 1
6. DcsServer never been restarted

TRAFODION-2877 can't restart DCSServer after switch to backup-master

---

DISCLAIMER
Makefile
core/Makefile
core/conn/Makefile
core/conn/jdbcT4/pom.xml
core/sqf/.gitignore
core/sqf/Makefile
core/trafodion.spec
docs/client_install/src/asciidoc/_chapters/preparation.adoc
docs/provisioning_guide/src/asciidoc/_chapters/quickstart.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc
install/.gitignore
install/Makefile
install/ambari-installer/Makefile
licenses/Makefile

Remove disclaimer file and incubating string from packaging file names.

[TRAFODION-2861][TRAFODION-2869] Remove incubating from release packaging

---

docs/src/site/site.xml

To be compatible with http or https

[TRAFODION-2863] Web-page style sheets should be protocol relative

---

core/conn/trafci/Makefile

The extra $ seems no use
remove it

[TRAFODION-2887] extra $ sign in trafci Makefile

---

core/sql/regress/seabase/EXPECTED027

seabase 027 test fail due to message content changes

[TRAFODION-2898] fix sql regression failure

---

dcs/src/main/java/org/trafodion/dcs/master/ServerManager.java

Check all configured servers, if the server is not watched by zookeeper during dcs master or backup master starting, add to the restart queue, then dcs master will try to restart it.

TRAFODION-2885 dcs server cant be restart while switching master

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/sqltocconv.cpp
win-odbc64/odbcclient/drvr35/sqltocconv.cpp

correct datalen while converting char in table to local datetime struct

[TRAFODION-2902] datalen is wrong while converting varchar in table to local datetime struct

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java
core/conn/trafci/src/main/java/org/trafodion/ci/DatabaseQuery.java

if stmtLabel is "null" string, then it will skip driver's conditional judgment (if (stmtName ==null) throw exception).

TRAFODION-2905 query id contain null

---

core/conn/odbc/src/odbc/Common/ODBCMXTraceMsgs.cpp
core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/ctosqlconv.cpp
core/sqf/src/seabed/src/sqstatepi.cpp
core/sql/langman/Measure.cpp
core/sql/optimizer/MJVIndexBuilder.cpp
win-odbc64/odbcclient/drvr35/cdesc.cpp
win-odbc64/odbcclient/drvr35/ctosqlconv.cpp

The count of parameters mismatches the format string in sprintf

[TRAFODION-2893] fix the logic Critical error checked by TScanCode.

---

core/conn/odb/src/odb.c
core/conn/odbc/src/odbc/Common/ExpConvMxcs.cpp
core/conn/odbc/src/odbc/Common/linux/sqmem.cpp
core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/ctosqlconv.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/common/ExpConvMxcs.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/hbasetm.h
core/sqf/src/stfs/common/stfs_msgbuff.cpp
core/sql/arkcmp/CompException.h
core/sql/common/BaseTypes.h
core/sql/common/csconvert.cpp
core/sql/executor/ExExeUtilGetStats.cpp
core/sql/exp/ExpConvMxcs.cpp
core/sql/exp/exp_conv.cpp
core/sql/optimizer/NATable.cpp
core/sql/regress/tools/logsort_src/tokstr.c
core/sql/sqlmsg/ComDiagsMsg.cpp
win-odbc64/Common/ExpConvMxcs.cpp
win-odbc64/odbcclient/drvr35/ctosqlconv.cpp
win-odbc64/odbcclient/drvr35/diagfunctions.cpp
win-odbc64/sql/common/csconvert.cpp

fix the bufoverrun Critical error checked by TScanCode

[TRAFODION-2891] fix the bufoverrun Critical error checked by TScanCode

---

dcs/pom.xml
dcs/src/main/java/org/trafodion/dcs/Constants.java
dcs/src/main/java/org/trafodion/dcs/server/ServerManager.java
dcs/src/main/java/org/trafodion/dcs/util/RetryCounter.java
dcs/src/main/java/org/trafodion/dcs/util/RetryCounterFactory.java
dcs/src/main/resources/dcs-default.xml

When mxosrvr down, DCS server will restart it , and if mxosrvr down a lot of times(6 default) in a period of time(30 min default), there should reject the restart behavior.
if this down time is more than 30 min (default) to 6 times ago (default), DCS server should allow the restart

TRAFODION-2844 add strategy to dcsserver for restart moxsrvr

---

dcs/bin/dcs-daemon.sh
dcs/src/main/java/org/trafodion/dcs/master/ServerManager.java

this is the enhancement for TRAFODION-2885

TRAFODION-2885 enhancement for dcs server restart

---

docs/src/site/markdown/index.md

This pull request adds recent articles about Apache Trafodion becoming a Top-Level Project and Apache Trafodion features to the Apache Trafodion web site.

[TRAFODION-2928] Add recent articles to Trafodion web site

---

NOTICE

update the NOTICE file year
This is for Release R2.2 change.

[Trafodion 2942] Update year in license text

---

core/conn/odb/src/odb.c

**root cause:** original odb didn't consider blank line.
**fixed by:** deal with the blank line.
**verifying:** run a regression test and found this bug had been fixed and no new issues were introduced.

[TRAFODION-2955] odb crash when executing sql statements in a file and the file contains space only line. 

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

When using ODBC2.x to get description of columns, failure occurs but no error returns.

[TRAFODION-2899] Catalog API SQLColumns support ODBC2.x

---

core/sql/optimizer/ScanOptimizer.cpp

This set of changes fixes some issues that were found in the new MDAM costing code while testing it for the case of an inner table of a nested join.
The fixes are:
1. We were way too pessimistic in calculating the number of seeks. We assumed we would do a seek per block, but it is obvious that the number of seeks is bounded from above by the number of subsets. This showed up when testing queries with tiny numbers of probes (4) but large numbers of rows per sequential subset (over 100 blocks worth in total).
2. We were applying some rowsize adjustment factors twice, once in NewMDAMCostWA::compute, and again in FileScanOptimizer::scmComputeMDAMCostForHbase, which it calls. The duplicate logic was removed in NewMDAMCostWA::compute.
3. We were overestimating the number of fetch subset rows …

[TRAFODION-2645] Fixes to MDAM costing code found during nested join tests

---

docs/src/site/markdown/download.md

Old releases need to be from archives site.

[TRAFODION-2959] Change download URLs for old releases

---

core/sql/optimizer/ScanOptimizer.cpp

This change fixes a bug in the new MDAM costing code. The code checks for a mix of less than and greater than predicates and if so detected uses the square of the HIST_DEFAULT_SEL_FOR_PRED_RANGE when calculating the UEC for the range. But the code was assuming the key column was always on the left. It turns out this assumption is not true. With this change, we no longer make this assumption but instead check to see which side of the comparison operator has the key column.

[TRAFODION-2964] Fix bug in new MDAM costing code concerning comparisons

---

core/sql/executor/HdfsClient_JNI.cpp

https://jenkins.esgyn.com/job/Check-Daily-master-rh6/360/

Fix for failure in hive/TEST018 test in 02/22/18 daily build

---

docs/src/site/markdown/download.md

Some download links are wrong, fix them. This time, try each link by hand one by one. Should be all correct...

[TRAFODION-2985] fix wrong download link

---

core/sql/optimizer/mdam.cpp

[TRAFODION-2988] prepare query returns 2006 internal error

---

core/sqf/sql/scripts/pkillall
core/sqf/sql/scripts/presumeall
core/sqf/sql/scripts/psuspendall
core/sqf/sql/scripts/traf_pkill
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodionnode.py

[TRAFODION-3013] Several scripts incorrectly use cut -b 1-5 to extract pid information

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceStatement.java
core/conn/jdbc_type2/native/SQLMXCommonFunctions.cpp
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXDesc.java
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXPreparedStatement.java

fill in blank when give value to a char() type.
support Chinese value, when column type is UCS2

TRAFODION-3019 pstmt.setByte cannot support string.getbyte well

---

core/sql/parser/sqlparser.y

one line of unused code in parser

[TRAFODION-3020] regression issue

---

core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp
core/conn/odbc/src/odbc/nsksrvr/SrvrMain.cpp
dcs/src/main/java/org/trafodion/dcs/Constants.java
dcs/src/main/java/org/trafodion/dcs/server/ServerManager.java
dcs/src/main/resources/dcs-default.xml

To improvement performance when every query executed needs to be written into repository.
The time when the queries cached will be published into repository is determined by cache time or number of queries. You can configure it in the file dcs/conf/dcs-site.xml.

[TRAFODION-3041] Support watchdog query cache

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/Certificate.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/Cipher.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/Key.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/MessageDigest.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/SecPwd.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/Security.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/SecurityException.java

Attach original error on customized exception.

[TRAFODION-3067]Print out original exceptions for cert error

---

core/sqf/export/include/seabed/int/thread.inl

This is a temp solution.
Root cause need much more time to figure out.

[TRAFODION-3075] DCS start fail at CentOS 7

---

core/sql/bin/SqlciErrors.txt
core/sql/cli/Cli.cpp
core/sql/cli/Cli.h
core/sql/cli/CliExtern.cpp
core/sql/cli/Context.cpp
core/sql/cli/Context.h
core/sql/cli/SessionDefaults.cpp
core/sql/comexe/ComTdbExeUtil.h
core/sql/executor/ExExeUtil.h
core/sql/executor/ExExeUtilLoad.cpp
core/sql/exp/ExpErrorEnums.h
core/sql/exp/ExpLOB.cpp
core/sql/exp/ExpLOB.h
core/sql/exp/ExpLOBenums.h
core/sql/exp/ExpLOBexternal.h
core/sql/generator/GenItemFunc.cpp
core/sql/generator/GenPreCode.cpp
core/sql/generator/GenRelExeUtil.cpp
core/sql/parser/sqlparser.y
core/sql/runtimestats/SqlStats.cpp
core/sql/runtimestats/SqlStats.h
core/sql/runtimestats/rts_msg.cpp
core/sql/runtimestats/rts_msg.h
core/sql/runtimestats/sscpipc.cpp
core/sql/runtimestats/sscpipc.h
core/sql/runtimestats/ssmpipc.cpp
core/sql/runtimestats/ssmpipc.h
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

This is an interim solution to provide a locking mechanism for LOB operations. See JIRA for a document on the issue and the details.

[TRAFODION-2946] Support to provide a locking mechanism for LOB insert/update operations

---

dcs/src/main/java/org/trafodion/dcs/server/ServerManager.java

in previous [TRAFODION-2668] , there deleted nid accidentally, this result when mxosrvr restart, there will do a whole sqlcheck instead of node check

[TRAFODION-2668] fix nid been accidentally deleted

---

pom.xml

Change the URL from http: to https:

[TRAFODION-2926] Fix issue-tracking URL on web site

---

win-odbc64/Common/TransportBase.h
win-odbc64/Common/marshalingdrvr_drvr.cpp
win-odbc64/Common/marshalingdrvr_drvr.h
win-odbc64/Krypton/generated_incs/odbc_cl.h
win-odbc64/odbcclient/drvr35/Interface/odbcs_drvr.cpp
win-odbc64/odbcclient/drvr35/Interface/odbcs_drvr.h
win-odbc64/odbcclient/drvr35/cconnect.cpp
win-odbc64/odbcclient/drvr35/cconnect.h
win-odbc64/odbcclient/drvr35/cdesc.cpp
win-odbc64/odbcclient/drvr35/cstmt.cpp
win-odbc64/odbcclient/drvr35/cstmt.h
win-odbc64/odbcclient/drvr35/ctosqlconv.cpp
win-odbc64/odbcclient/drvr35/drvr35_os.vcxproj
win-odbc64/odbcclient/drvr35/drvr35_os.vcxproj.filters
win-odbc64/odbcclient/drvr35/drvrglobal.cpp
win-odbc64/odbcclient/drvr35/drvrnet.cpp
win-odbc64/odbcclient/drvr35/drvrnet.h
win-odbc64/odbcclient/drvr35/lob.cpp
win-odbc64/odbcclient/drvr35/lob.h
win-odbc64/odbcclient/drvr35/netstmt.cpp
win-odbc64/odbcclient/drvr35/sqltocconv.cpp
win-odbc64/odbcclient/drvr35/sqltocconv.h
win-odbc64/sql/cli/sqlcli.h

The operation is following JDBC T4

[TRAFODION-2743] Windows ODBC LOB support

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

Nowadays, the metadata table in server is not correct.
I will do more test with this PR.
The problem is that the 'COLUMN_PRIVILEGES' table has no data increased after I grant privileges on table to any user.

[Trafodion-3143] SQLColumnPrivileges support

---

core/sql/regress/seabase/EXPECTED012
core/sql/regress/seabase/EXPECTED024
core/sql/regress/seabase/EXPECTED027

Sorry, need yet another fix to the GET command display change, which causing failures.

fix regression failure

---

core/sqf/sqenvcom.sh

environments due to port number collisions.

[TRAFODION-2884] Disabled monitor agen mode startup in workstation

---

core/sqf/sql/scripts/localstfscheck
core/sqf/sql/scripts/stfscheck
core/sqf/src/tm/tools/dtmci.cpp

It is hard to test the STFS status if the cluster has many nodes and the STFS configured with many directories. This script will help to do basic checking.

[TRAFODION-3163] Add script to do STFS health check

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

update the doc for new added function

[TRAFODION-3172] update documentation for sys_guid function

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

add documentation for some newly added MySQL functions. For comparability enhancement of Trafodion.

[TRAFODION-2968] update SQL manual for MySQL functions unix_timestamp, uuid, sleep etc

---

docs/cqd_reference/src/asciidoc/_chapters/query_execution.adoc

Add a new CQD which end user will use, so update the manual

[TRAFODION-3193]update cqd reference manual about the new CQD

---

core/conn/odb/src/odb.c

Some customer asks for this feature and these feature has been tested.

[TRAFODION-3235] add div and trim function for map feature, improve bad file print function.

---

win-odbc64/odbcclient/drvr35/charsetconv.cpp
win-odbc64/odbcclient/drvr35/charsetconv.h
win-odbc64/security_dll/native/source/secpwd.cpp

1. Set your current language used in non-unicode programs to GBK.
2. Create user name with chinese.
3. Test odbc.

[TRAFODION-3238] ODBC can not connect to server when the local language is gbk

---

core/sql/regress/hive/DIFF003.KNOWN

accommodate the costing change between Jenkins and contributor's
work space environments.

Fix for hive/TEST003 failure. Created a known failure to

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceConnection.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceUtilities.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4Properties.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4ResultSet.java

1. change charset map in InterfaceUtilities.java to Canonical Charset Name according to jdk define.
2. if user specify clientCharset, then it will change that charset when display string value

[TRAFODION-3247] support customer define client charset

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/CONNECTION_CONTEXT_def.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceConnection.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceStatement.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/OUT_CONNECTION_CONTEXT_def.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Connection.java

push down setSchema() to server side, now it will be set in server side.
getSchema() will get value from outContext, and it will not do a tcp request

[TRAFODION-3250] optimize get/set schema

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

@DaveBirdsall Could you please help review? Thanks

[TRAFODION-3289] Add the OVERLAY Function in the Trafodion SQL Reference Manual

---

core/sql/bin/SqlciErrors.txt
docs/messages_guide/src/asciidoc/_chapters/binder_msgs.adoc

Added message text for messages 4131 and 4132.
Marked some unused messages as unused in SqlciErrors.txt.
Made minor editorial corrections to a few other messages.

[TRAFODION-3294] Updated Messages Guide for some binder messages

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

@DaveBirdsall Could you please help review? Thanks
I've got inputs from the PR #1276.

[TRAFODION-3295] Add syntax descriptions and examples of *WITHOUT LOB COLUMNS* for CREATE TABLE LIKE Statement in Trafodion SQL Reference Manual

---

docs/odb_user/src/asciidoc/_chapters/load.adoc

@DaveBirdsall Could you please help review? Thank you.

[TRAFODION-3301] Add considerations for empty mapping options in the Trafodion odb User Guide

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

@DaveBirdsall Could you please help review? Many thanks.

[TRAFODION-3303] Add the Comparison of Rounding Functions in the Trafodion SQL Reference Manual

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

@DaveBirdsall Could you please help review? Many thanks.
I've deleted the CEIL function, the FLOOR function and the ROUND function in the table of Mathematical Functions, and created a table of Rounding Functions for them along with the TRUNC function.

[TRAFODION-3302] Add the CEIL Function in the Trafodion SQL Reference Manual

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

@DaveBirdsall Could you please help review? Many thanks.

[TRAFODION-3306] Add the TRUNC Function in the Trafodion SQL Reference Manual

---

core/conn/odb/src/odb.c

change the null string and empty string handle logic as below:
if empty string handle option defined in the map file then
handle empty string as the map file defined rule
else if ns option is set then
handle empty string as an empty string
else
handle empty string as null

fix TRAFODION-3307

---

core/conn/jdbc_type2/native/CSrvrStmt.cpp
core/conn/jdbc_type2/native/CSrvrStmt.h
core/conn/jdbc_type2/native/CoreCommon.h
core/conn/jdbc_type2/native/GlobalInformation.h
core/conn/jdbc_type2/native/SQLMXConnection.cpp
core/conn/jdbc_type2/native/SQLMXDriver.cpp
core/conn/jdbc_type2/native/SqlInterface.cpp
core/conn/jdbc_type2/native/SrvrCommon.cpp
core/conn/jdbc_type2/native/pThreadsSync.h
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/SQLMXConnection.java
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/T2Driver.java
core/conn/jdbc_type2/src/main/java/org/apache/trafodion/jdbc/t2/T2Properties.java

Removed nowait and mploc related code in T2 driver. Both of these concepts are not valid anymore.

[TRAFODION-3329] Code cleanup in Type 2 driver

---

core/sql/comexe/ComTdbHdfsScan.h
core/sql/executor/ExHdfsScan.cpp
core/sql/executor/ExHdfsScan.h
core/sql/generator/GenRelScan.cpp
core/sql/generator/GenRelUpdate.cpp
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/sqlcomp/nadefaults.cpp

Retired the HDFS text/sequence file scan using lib hdfs.
Fix for udr/TEST102 failure

[TRAFODION-3328] Code cleanup in Trafodion

---

docs/src/site/markdown/download.md

[TRAFODION-3336] Update apache downloads URL
