core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/RelExeUtil.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelUpdate.h
core/sql/optimizer/TableDesc.cpp
core/sql/optimizer/TableDesc.h
core/sql/regress/core/TEST019
core/sql/regress/executor/EXPECTED015.SB
core/sql/regress/executor/TEST015
core/sql/regress/hive/EXPECTED015
core/sql/regress/hive/TEST015

A prior checkin to address https://bugs.launchpad.net/trafodion/+bug/1460771 caused two tests to fail in the nightly build. The problem was twofold
a) VEG creation was disabled between old and new values in an the WHEN MATCHED clause of a MERGE statement. This caused several MERGE statements to fail.
b) Bulk load was incorrectly taking the merge code path.
Both these problem have been addressed by making the previous checkin apply only to UPSERT statements on tables with index. In addition a few other outstanding issues that could potentially cause inconsistency between table and index have been disabled. These include
a) MERGE statement on table with UNIQUE index
b) UPSERT statement on table with serialized columns.
Bulk load on tables with index will now cause the index to be rebuilt …

Fix for TRAFODION-4

---

core/sqf/export/include/dtm/tmtransid.h
core/sqf/src/tm/tmlib.cpp
core/sqf/src/tm/tmtransid.cpp
core/sql/comexe/ComTdbHbaseAccess.h
core/sql/executor/ExHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.h
core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/executor/HTableClient.java
core/sql/exp/ExpHbaseDefs.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h
core/sql/generator/GenRelUpdate.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Non-blocking hbase operation to smoothen the data flow in trafodion engine
A new CQD HBASE_ASYNC_OPERATIONS is introduced to enable non-blocking
hbase operation for checkAndInsert operations. The default value is
'OFF'.
This allows the trafodion engine to insert rows into base table and
indexes at the same time. checkAndInsert operations always done under
a transaction ensuring the data consistency between tables and indexes
for a single row insert operation.
During this process, TM is refactored to enable passing a transaction
id created in a thread to another thread.
Change-Id: I0d09e5b0a3f988808c44bd83463df45fd21c67c0

JIRA TRAFODION-9

---

core/sql/executor/HTableClient.java
core/sql/sqlshare/CatSQLShare.cpp

System with large number of nodes, some created tables can not be used
The code that generates the unique ID that has been used as OBJECT_UID
is reworked to avoid getting negative numbers. Earlier, it was possible
to get negative number on the nodes at or above 64 nodes.
Please see the inline comments in CatSQLShare.cpp for the new
algorithm.
Change-Id: I7df665c16d9c156e110d9d2db3dcd82bd6dfd615

Fix for Trafodion-5

---

core/sql/executor/ExHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.h
core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h

upsert or merge into a table with indexes can result in
inconsistency between index and table
The change is to pass the recent row timestamp to the Delete
operator. However, this may not solve the above issue because
tombstone marker timestamp can be same or later than the
recently added row even with this change.
This change is pushed for the following reasons:
a) To enable Trafodion async operation concept for the merge
operation
b) To optimize delete operation by removing unwanted memory
allocation.

Changes related to JIRA [TRAFODION-14]

---

core/conn/jdbc_type2/native/Debug.cpp
core/conn/jdbc_type2/native/Debug.h
core/conn/jdbc_type2/native/SQLMXConnection.cpp

With this check-in, JDBC T2 can use -D_DEBUG to make a debug version.
The debug version can output many debug informations and detect the
memory leak.
Change-Id: Ibf5dc2ae7e73b232bf0f3499fa3194d7f04c2e0e

[TRAFODION-6]JDBC T2 has compilation errors when use -D_DEBUG option

---

core/sql/sqlcomp/PrivMgrCommands.cpp
core/sql/sqlcomp/PrivMgrPrivileges.cpp
core/sql/sqlcomp/PrivMgrPrivileges.h

1438896: Internal error during create or replace view
The objectUID check when getting privilege information was not correct.
1465356: Revoke privilege from role returns dependent object error
There is a check in mainline revoke code to determine if the object type is a
view and if the SELECT privilege is no longer applicable. If so, then the
dependent error is returned. However, this code is incorrect and actually the
correct code exists in the gatherViewPrivileges method. The view check has been
removed.

Privilege manager fixes for 1438896 and 1465356

---

core/sql/cli/Statement.cpp
core/sql/generator/GenProbeCache.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

queries of BLOB with JOINs
A new CQD EXE_MEMORY_FOR_PROBE_CACHE_IN_MB is introduced
to limit the amount of memory consumed in probe cache
operator. The default value is 100MB.
For other details, refer to JIRA

Fix for [TRAFODION-27] - Time consuming compilation for

---

core/sqf/sql/scripts/install_local_hadoop

using install_local_hadoop
Fixed the local hadoop script so servers file in $DCS_INSTALL_DIR
/conf folder is generated correctly. Also took care of the default
github location for DCS/REST and Phoenix tests

[TRAFODION-30]dcs start fails on development workspaces when

---

core/sql/comexe/ComTdbHbaseAccess.cpp
core/sql/comexe/ComTdbHbaseAccess.h
core/sql/executor/ExHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.h
core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h

upsert or merge into a table with indexes can result
in inconsistency between index and table
This change avoids the HBase issue of rows getting lost when the
delete and put operations are done in the same milliseconds
timestamp dimension for the given rowid.
In the trafodion_delete operation execution, the row is skipped
for deletion if the new and old rowid evaluates to the same value.
This needs change from the compiler sub-task in the JIRA to complete
for it to be effective.
In addition removed yet another memory allocation for the delete
operation.

Fix for [TRAFODION-14]

---

core/sql/regress/tools/runregr_fullstack2.ksh

I checked in a file EXPECTED062.RELEASE, but the test was looking for
EXPECTED062.SB.RELEASE.

TRAFODION-1418 Fixing Jenkins test failure of fullstack/TEST062 in release mode.

---

core/sql/comexe/ComTdbHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.cpp
core/sql/generator/GenPreCode.cpp
core/sql/generator/GenRelUpdate.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ImplRule.cpp
core/sql/optimizer/Inlining.cpp
core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelUpdate.h

This fixes the issue where we update an indexed column to itself, and
the index maintenance tree both deletes and re-inserts the index row
within the same millisecond. This makes the index row disappear, as the
delete takes precedence over the insert, even though it happened earlier.
As a side-effect, index maintenance may get faster, because we are
also replacing the CheckAndPut of the index insert with a Put.
We could further improve this by processing multiple Puts together.

TRAFODION-40 Make index-maintenance delete conditional

---

core/sql/comexe/ComTdbHbaseAccess.cpp
core/sql/executor/ExHbaseIUD.cpp

Evaluated the DeletePreCond expression in the VSBB delete and
skipped the rows to be deleted when needed. This is expected to resolve
the random failures with executor/TEST015.
Also, changed some of the tcb names to match the compiler names.
EX_TRAF_VSBB_INSERT -> EX_TRAF_VSBB_UPSERT
EX_TRAF_ROWSET_UPDATE -> EX_TRAF_VSBB_UPATE
EX_TRAF_ROWSET_DELETE -> EX_TRAF_VSBB_DELETE
EX_TRAF_ROWSET_MERGE -> EX_TRAF_VSBB_MERGE

[TRAFODION-14] Inconsistency in index

---

core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h
core/sql/generator/GenRelScan.cpp
core/sql/optimizer/NAClusterInfo.cpp
core/sql/optimizer/NATable.cpp
core/sql/optimizer/NATable.h
core/sql/optimizer/NodeMap.cpp
core/sql/optimizer/RelScan.h
core/sql/sqlcat/desc.h
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

This request is for the merge of the two fixes to the main branch. 
1425:  represent native HBase tables as partitioned (if so). Previously, all such tables are modeled as single partitioned inside the compiler. 
1432:  compiler crashes when compile LOAD INTO salted trafodion tables

fix JIRA 1425 and 1431

---

core/sqf/sqenvcom.sh
install/installer/tools/traf_hortonworks_uninstall
install/installer/tools/traf_hortonworks_uninstall_suse
install/installer/traf_add_user
install/installer/traf_cloudera_mods98
install/installer/traf_config_setup
install/installer/traf_getHadoopNodes
install/installer/traf_hortonworks_mods98
install/installer/traf_setup
install/installer/traf_start
install/installer/trafodion_uninstaller

Trafodion can now be installed on cloudera parcels. 
traf_setup was trying to use pdsh and pdcp for the epel repo 
when it had not been installed.

[[Trafodion 1452]] Cloudera parcel support and EPEL fix

---

core/sql/cli/SessionDefaults.cpp
core/sql/cli/SessionDefaults.h
core/sql/cli/Statement.cpp
core/sql/executor/ExExplain.cpp
core/sql/executor/ex_control.cpp
core/sql/sqlcomp/nadefaults.cpp

EXPLAIN_IN_RMS is now enabled by default. The explain plan
can now be obtained from a different session using
explain for qid <qid>
explain options 'f' for qid <qid>
The explain fragment in packed format is retained in RMS shared
segment till the query is deallocated.

[TRAFODION-1460] Enable EXPLAIN IN RMS feature by default

---

core/sql/bin/SqlciErrors.txt
core/sql/executor/ExHdfsScan.cpp
core/sql/executor/ExHdfsScan.h
core/sql/generator/GenRelScan.cpp

The null byte is now skipped over to look for the column and record delimiter while scanning the hdfs row buffer. The null byte will be part of the column value. The behavior of null byte in the column value is unknown. Skipping over null byte is now in sync with other tool's behavior.
Also, improved the code to scan the buffer for both record and column delimiter once. Earlier, the buffer was scanned twice; once for the record delimiter and another for column delimiter.
No errors are returned when null byte is found.
A sql error 7002 is now reported when a unsupported row format type is accessed from Trafodion.
*** ERROR[7002] The input row format of the hive table is not yet supported.

[TRAFODION-1453] Improvements in Hive Scan

---

core/sql/regress/compGeneral/EXPECTED042

It seems TEST042 failure is not related to multiple column family support.
compGeneral/EXPECT042 is changed since Aug 18, which gives wrong lines to compare.

Fix TRAFODION-1450

---

install/installer/traf_config_setup

Using $username:$password instead or hardcoded admin:admin.

TRAFODION-1461 Install scripts have hard coded values for Hadoop admin and password

---

install/installer/traf_sqconfig

- Try to get cores and processors from /proc/cpuinfo when we cannot get from lscpu.

TRAFODION-1480 Alternative to lscpu to get cores and cpus using info from /proc/cpuinfo

---

core/conn/trafci/src/org/trafodion/ci/SessionDefaults.java
core/conn/trafci/src/org/trafodion/ci/UserInterface.java
core/sqf/build-scripts/genverhdr.ksh
core/sqf/export/include/SCMVersHelp.h
core/sqf/sqenvcom.sh
core/sqf/sqvers
core/sql/common/copyright.h
core/sql/nskgmake/sqlcilib/Makefile
core/sql/nskgmake/sqlmsg/Makefile
core/sql/regress/tools/regress-filter-linux
core/sql/regress/tools/setuplnxenv
core/sql/regress/udr/EXPECTED100.SB
core/sql/regress/udr/FILTER100
core/sql/sqlmsg/ComDiagsMsg.cpp

This change addresses the product banners to reflect Apache Trafodion copyright and name.
The copyright and product names have been made envvars in sqencom.sh so we dont' have to touch code in the future to make any updates. 
Changed sqvers output to give detail to show the Apache Trafodion name in it.

[TRAFODION-28] Update the copyrights in all Trafodion source files to make them conform to ASF standards.

---

core/sqf/sqenvcom.sh

The script now checks for common HBase and Hadoop setup scenarios, for
example with environment variables HADOOP_PREFIX, HBASE_HOME and
HIVE_HOME set.
This work is not complete yet, we need to document the entire process
and probably need to make a few small code changes to fix interfaces
that went away or are not yet added in Apache Hadoop/HBase.

Changes to sqenvcom.sh file to make it easier to run on Apache HBase w/o distro

---

core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

Fixes a bug in UPDATE STATS. UPDATE STATS when used with the SAMPLE clause creates a sample of data from a table. If the sample is too large to fit in memory, it writes that sample to a temporary table. It uses an UPSERT or LOAD statement to do so. The bug is that the plan chosen for this UPSERT/LOAD was a serial plan, when a parallel plan should have been selected. For details on the bug, see the JIRA.

[TRAFODION-1494] UPD STATS used serial plans for sample table

---

core/sqf/conf/install_features
core/sqf/conf/trafodion.udr.config
core/sql/executor/JavaObjectInterface.cpp
core/sql/udrserv/UdrCfgParser.cpp
core/sql/udrserv/udrserv.cpp

This is a fix for the second of the two issues described in this JIRA. The first 
has been addressed by narendra in a separate checkin. 
In this checkin we allow multiple methods to specify JVM startup options for the 
UDR server process. There are three methods applied in this order with the last 
specification for each property superceeding previous specifications.
1. A default default of 512MB for UDR JVM's max heap size
2. Specify any desired property including -Xmx in a new configuration file
3. Specify any desired property using TRAF_UDR_JAVA_OPTIONS env variable
The new configuration file is at $MY_SQROT/conf/trafodion.udr.config. It has 
detailed comments on how properties should be specified in the file. The location 
(including name) of the configuration file can be overridden …

[TRAFODION-1492] Allow specification of MaxHeapSize for JVM started by UDR server

---

core/sql/cli/memorymonitor.cpp

- Ignore if some properties are not found in the procfs
- Ability to disable memory monitoring in the SQL process by setting
SQL_DISABLE_MEMMONITOR to 1 in $MY_SQROOT/etc/ms.env

Fix for [TRAFODION-1492]

---

core/sql/regress/compGeneral/EXPECTED042

The fix to JIRA TRAFODION-1494 unfortunately changed the results for compGeneral/TEST042. This check-in updates the expected results for that test.

[TRAFODION-1497] Fix expected results for compGeneral/TEST042

---

core/sqf/sql/scripts/install_local_hadoop
core/sqf/sql/scripts/sqgen

Avoid the common mistake of doing an sqgen in an environment that
is not clean, where changes to CLASSPATH or other environment variables
have been done after sourcing sqenv.sh.
This commit also fixes TRAFODION-1505, delete the sw* convenience scripts
created by install_local_hadoop when we do swuninstall_local_hadoop.

TRAFODION-1504 check for environment in sqgen

---

tests/phx/pom.xml.template

The new trafodion-dtm-1.2.0.jar file needed to be added to the
Phoenix tests as well, those are using Maven, not the CLASSPATH
set up in sqenvcom.sh.

Fix for Phoenix T2 test failures due to missing DTM classes.

---

core/sqf/build-scripts/build.branch
core/sqf/src/seatrans/.gitignore
core/sqf/src/seatrans/tm/hbasetmlib2/Makefile
core/sqf/src/seatrans/tm/hbasetmlib2/pom.xml
core/sql/nskgmake/Makerules.mk
core/sql/pom.xml
install/traf_tools_setup.sh

Removed the Koraktor Maven plugin from SQL and hbasetmlib2 pom files,
since it fails when we build a source tree that is not managed by git.
Additional changes:
- Added "clean" steps to remove the built jar files
- Suppressed "svn not found" error when building outside of git
- Added maven to traf_tools_setup.sh

TRAFODION-1541 Fix make errors when building outside of git

---

core/sql/export/NAStringDef.h
core/sql/optimizer/EncodedKeyValue.cpp
core/sql/optimizer/EncodedKeyValue.h
core/sql/optimizer/ItemColRef.h
core/sql/optimizer/ItemExpr.cpp
core/sql/optimizer/ItemExpr.h
core/sql/optimizer/NAFileSet.cpp
core/sql/optimizer/NAFileSet.h
core/sql/optimizer/NATable.cpp
core/sql/optimizer/PartFunc.cpp
core/sql/optimizer/PartFunc.h
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelScan.h
core/sql/optimizer/ScanOptimizer.cpp
core/sql/optimizer/ValueDesc.cpp
core/sql/optimizer/ValueDesc.h
core/sql/qms/QmsJoinGraph.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

This set contains the fix to JIRA461, which addresses the problem as follows. 
1. For range partition function only, the the begin B and end E partition is identified using the begin key and end contained in the SearchKey generated for the FileScan object.
2. The number of active partitions is the number of partitions contained within B and E. 
3. The work is done for both Trafodion and Native Hbase table, where key comparison is different:  binary key comparison for encoded key in a Traf table, and ASCII key comparison for a Native Hbase table.

fix JIRA461

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/SplitBalanceHelper.java

Region split/balance is not being delayed if Trx Scanner obj is present
Fix was to delay on scanners list clear OR pending list clear instead
of AND.

[TRAFODION-1564]Split/balance is not being delayed

---

core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/ScmCostMethod.cpp

Costing changes merged in a few weeks ago enabled more efficient DELETE plans. For example, in a table with 200,000 rows, formerly we would pick a serial plan for "delete from t". With the costing changes, we would pick a plan that would scan its regions in parallel, forward the keys to the Master, then do a "vsbb delete" in the Master. This is much faster. 
However it is still not ideal. A better plan would  be to skip the forwarding step and do "vsbb delete" in the ESP where we are doing a scan. In this way, the HBase deletes are happening in parallel as well as the scans.
The reason the ideal plan was not chosen was that method HbaseDelete::synthPhysicalProperty() had stub code that always generated a "single partition" partitioning function. So, plans that attempted to do the delete …

[TRAFODION-25] Fix bug preventing fully parallelized DELETEs

---

install/installer/trafodion_install

On an upgrade, INSTALL_LOG was getting the old installer name (because
the config file had already been sourced). Added new variable to "remember"
the new installer log.

[[ TRAFODION 1563 ]] Fix of INSTALL_LOG file with current date

---

core/sql/regress/hive/EXPECTED018

I think the diff is due to some other reason, since my changes are about update stats on hive tables which is not done in TEST018.  
Here are some interesting findings. 
1. If I prepare the query separately, I do not see the warnings. 
2. If I ran the test with explain, the explain shows reasonable cardinality for the query in question, which indicates the stats is present.
3. Earlier on, I noticed the disappearance of the same warning from core/test126. 
A JIRA will be filed to track the unnecessary warning.

update expected file for HIVE/TEST018

---

core/sqf/sql/scripts/findPort.py

This check-in adds a new script in the sql/scripts directory, findPort.py. It is useful in finding a range of ports that are not in use before using install_local_hadoop.

[TRAFODION-1591] Script to find ports not-in-use

---

core/sql/comexe/ComTdbHbaseAccess.cpp
core/sql/comexe/ComTdbHbaseAccess.h
core/sql/executor/ExHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.h
core/sql/executor/ExHbaseIUD.cpp
core/sql/generator/GenRelUpdate.cpp
core/sql/optimizer/BindRelExpr.cpp

commands to improve performance of update statements. When a table has
check constraint the update command is transformed into insert and delete.
Added code to evaluate constraint expressions in all TCBs so that
constraint checking is done correctly. But, the subtask [TRAFODION-1610]
needs to implemented before this change is exercised.

[TRAFODION-1575] Avoid transforming update into delete and insert

---

core/bldenvchk.sh
core/sqf/sqenvcom.sh
core/sqf/src/seatrans/hbase-trx/Makefile
install/traf_tools_setup.sh

1612: Stop building HBase-trx for MAPR, due to instable Maven repository
- removed mapr from the build_all step in the hbase_trx Makefile, we now create
6 jar files instead of 7
1613: build failing due to mismatched Maven downloads
When building Trafodion from source objects, Maven is required.  It is not
possible to download Maven from yum, instead it needs to be installed. There
are a few problems related to how Maven is managed with Trafodion builds.
- In many environments, Maven is already installed.  The check to see if Maven
is already installed is commented out in traf_tools_setup.sh. This has been
fixed.
- Today, sqenvcom.sh checks to see if mvn is installed, if not, it sets it to
version 3.0.5 but we install 3.3.3. Changed the code to return an error:
"ERROR unable to find mvn …

Trafodion-1612 and Trafodion-1613

---

core/sql/regress/seabase/EXPECTED027
core/sql/regress/seabase/TEST027
core/sql/sqlcomp/CmpDescribe.cpp
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

1) JIRA 1606. Create of a table LIKE a metadata table
now succeeds.
2) JIRA 1611. An error was incorrectly being returned if the
number of columns in a user specified column family
exceeded 32. That has been fixed.

Couple of fixes for JIRA issues. Details below.

---

core/rest/pom.xml
core/sqf/sql/scripts/install_traf_components
dcs/pom.xml
dcs/src/test/jdbc_test/jdbc_test.py
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestCat.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/Utils.java

To change the trafodion release version major/minor number, there were about a dozen locations in four different files that needed to be modified.
This set of changes eliminates all those places except for the single place in core/sqf/sqenvcom.sh.
It does add maven warnings in DCS and REST build logs, same as in other components that already use maven with environment variable version number.
jdbc_test.py script now takes additional options to pass in correct version numbers. If you use swjdbc script, then it is taken care of. Other environments that call jdbc_test.py directly (e.g., jenkins test automation) should also be changed. But the default values match the current release, so the change is not urgent.

[TRAFODION-1417] Reduce locations to change release version number

---

core/sql/generator/GenPreCode.cpp

A delete query on a 200K large table was marked as a unique delete. This was found when the long operation was not being cancelled when a cancel query was issued. Unique queries are typcially not cancelable since they are  short running.   The issue happens when rowset deletes are chosen . This  plan change happened recently due to a costing change. The rowset operation needs to be marked as cancelable.

Fix for the executor/TEST106 failure caused due to JIRA TRAFODION-1625

---

core/sql/executor/HBaseClient_JNI.cpp
core/sql/generator/GenExpGenerator.cpp
core/sql/generator/GenPreCode.cpp
core/sql/generator/GenRelScan.cpp
core/sql/generator/GenRelUpdate.cpp
core/sql/generator/Generator.h
core/sql/optimizer/NAColumn.h
core/sql/optimizer/NATable.cpp
core/sql/regress/seabase/TEST022
core/sql/sqlcomp/CmpDescribe.cpp
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp
core/sql/sqlcomp/nadefaults.cpp
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

The indexes row format is now independent of the table. The table
can be in format that aids in pushing down the predicates to
hbase, but the index is now created in aligned format by default.
SHOWDDL <table_name> now shows the row format of the index when it
is in aligned row format.

[TRAFODION-1423] indexes are now created in aligned format by default

---

win-odbc64/odbcclient/drvr35/cconnect.cpp

[TRAOFDION-1557] DataSource cannot connect using Tableau
using LONG_PTR instead of long to cast a point in some MFC function.
in Windows 10 x64 , Visual Stduio 2013, long is 4 bytes and point is 8 bytes.

[TRAFODION-1557]connot connect using Tableau

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/regress/seabase/EXPECTED010

This set of changes is a partial fix to [TRAFODION-1641]. It does resolve the issue described in the JIRA (that is, the query now gets a better choice of MDAM plans), however as in many Optimizer changes, there are side effects that still remain to be fully evaluated. Follow-on work will address these if judged to be significant.
JIRA 1641 describes two bugs. This set of changes fixes bug #1: MDAM costing now takes into account the cumulative cost of each key column materialized. This set of changes partially fixes bug #2: It removes a bit of code that set the stop column for all MDAM plans to the last column (which caused MDAM plans to always traverse all keys, which can be grossly inefficient).
For queries not containing RangeSpec predicates with OR subtrees, these changes will allow …

[TRAFODION-1641] Fix MDAM costing bugs

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Hi,
Could you please review the fix? 
The idea is to compute the product of UECs for key columns without predicates and consider MDAM when that product is within a fraction of the total UEC. 
CQDs re-arranged/created for this new and the existing restriction. 
MDAM_APPLY_RESTRICTION_CHECK:
// Specify whic additional restriction check to apply
//  0: no check
//  1: apply majority of keys with predicates check
//  2: apply total UECs on keyless key columns check (default)
//  3: apply both 1) and 2)
MDAM_TOTAL_UEC_CHECK_UEC_THRESHOLD:
// A threshold of total UECs on keyless key columns above which MDAM will not be considered.
// The threshold is expressed as a percentage of the total RC.
Default to 1 percent of the total RC. 
MDAM_TOTAL_UEC_CHECK_MIN_RC_THRESHOLD:
// A threshold of …

fix JIRA 1654 for Trafodion

---

win-odbc64/odbcclient/drvr35/cstmt.cpp
win-odbc64/odbcclient/drvr35/drvrnet.h

[TRAFODION-1558]Used driver connection with TCP:<ip>/<port>. Connection
succeeded but no schemas or tables are listed. It's was casued by the
driver use long (4 bytes) to store the points (8 bytes) which caused data
loss. The fix is use LONG_PTR insteaded.

[TRAFODION-1558]Tableau returns to tables or data

---

core/sqf/build-scripts/genverhdr.ksh
core/sqf/sqenvcom.sh
core/sqf/sqvers

Fix sqvers -u to treat all the jars from a build as a single version (JDBC jars not yet integrated).
Add version display for SuSE Linux to sqvers.
Remove LD_BIND_NOW environment variable, should be for debugging only.

TRAFODION-1570 and TRAFODION-1667 fixes to sqvers -u display

---

core/sql/executor/ExHdfsScan.cpp
core/sql/executor/ExStats.cpp
core/sql/executor/ExStats.h
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/ex_split_bottom.cpp

0 for OperCpuTime for operators hosted in ESP.
Isolate the timer for Operator Cpu Time from HBase IO Timer.
Statistics enabling flag was not set though statistics area was
created and some of the metrics were collected. Operator Cpu time
metrics collection requires statistics to be enabled. It is now
enabled when the operators are hosted in ESPs.

[[TRAFODION-1655]] RMS reports incorrect hbase io time and

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/regress/compGeneral/TEST062
core/sql/regress/hive/EXPECTED005
core/sql/regress/hive/EXPECTED006
core/sql/regress/hive/EXPECTED020
core/sql/regress/hive/TEST005
core/sql/regress/hive/TEST006
core/sql/regress/hive/TEST018
core/sql/regress/hive/TEST020
core/sql/regress/tools/runallsb
core/sql/sqlcomp/nadefaults.cpp

Hi,
I updated the regression tests with an increased value for CQD HIST_ROWCOUNT_REQUIRING_STATS to take care of missing stats warnings. 
A minor improvement also included to consider MC uecs only when the # of key columns without predicates is larger than 1. This is for a previous fix JIRA 1665. 
Thanks

Stats warnings

---

core/sql/arkcmp/CmpContext.cpp
core/sql/sqlcomp/CmpDescribe.cpp

This fixes the two bugs mentioned in JIRA TRAFODION-1678. The change to sqlcomp/CmpDescribe.cpp fixes the first bug, that is, some returns from CmpDescribe were failing to restore the SQL parser flags global before exiting. The change to arkcmp/CmpContext.txt fixes the second bug, which is the code was using the wrong API to set the SQL parser flags. Fixing either of these bugs resolves the symptom seen in the JIRA (one bug masks the other); I have chosen to fix both.

[TRAFODION 1678] Fix DTM error 97 on DROP SCHEMA

---

tests/phx/src/test/java/org/trafodion/phoenix/end2end/BatchTest.java

1. A new test case of inserting duplciate primary key value with
"insert" statement.
2. Changed the initializtion of expected value array of upsert
duplicate primary key values, previous code may cause incorrect test
result.

Add a new case to BatchTest of Phoenix test

---

core/rest/src/main/java/org/trafodion/rest/GetStatusResponse.java
core/rest/src/main/java/org/trafodion/rest/RESTServlet.java
core/rest/src/main/java/org/trafodion/rest/provider/JAXBContextResolver.java
core/rest/src/main/java/org/trafodion/rest/provider/producer/PlainTextMessageBodyProducer.java
core/rest/src/main/java/org/trafodion/rest/util/ConfTool.java
core/rest/src/main/java/org/trafodion/rest/zookeeper/ZkClient.java

Fix for TRAFODION-1736 where REST server was reporting duplicate entries for servers after a dcs restart.
Also fixed these other errors reported by eclipse:
- Fixed the java package name for the GetStatusResponse.java and ConfTool.java
- Removed the @override annotation for some of the methods which were either implementing interface methods or abstract methods with no real implementation in the super class. Touched classes are ZkClient , JAXBContextResolver and PlainTextMessageBodyProducer

TRAFODION-1736 REST server reports duplicate DCS connections

---

core/rest/src/main/java/org/trafodion/rest/RESTServlet.java

The earlier fix caused only the mxosrvrs associated with last DCS servers to be displayed in the REST dcs connections output. This was because the fix was put inside a loop which cleared the dcsservers discovered for the previous nodes.
The fix is now moved outside the for loop and so preserves all the discovered mxosrvrs. Tested and verified this on a 2 node cluster.

Fix reopened JIRA 1736

---

dcs/src/main/java/org/trafodion/dcs/servermt/serverDriverInputOutput/Descriptor2List.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlEndTransact.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverHandler/ServerApiSqlExecDirect.java

This commit will fix following issues.
1. [TRAFODION-1682][MTDCS] ODBC: SQLFetch returned invalid cursor
state. It's caused by the length of descriptor2List is not correct and
the sqlQueryType is not correct either. For sqlQueryType,
SqlUtils.getSqlStmtType(String str) will be used instead of
SqlUtils.getSqlStmtType(int stmtType) since it can't return the
correct value.
2. [TRAFODION-1653][MTDCS] coast tests core dumped at 'operator new'
when Multithread DCS is on. It's caused by the EndTransaction message
missing a int which indicate 0 excaption when there is no exception.
3. [TRAFODION-1658][MTDCS] with MultiThread DCS on, coast core dumped
at memcpy when there is parameter in prepare statement. It's caused by
the length of the descriptor2List is not correct.

[TRAFODION-1682]MT-DCS protocol issue fix

---

dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafConnection.java

[TRAFODION-1728][MT-DCS]ODBC: SQLExecute ran into communication link
failure when mtdcs is on.

[TRAFODION-1728]MT-DCS communication link failure

---

dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafConnection.java
dcs/src/main/java/org/trafodion/dcs/servermt/serverSql/TrafStatement.java

[TRAFDOION-1784][MTDCS]statement shoud be removed from HashMap when it's closed.
TrafConnection uses a HashMap to store the statements in MTDCS code.
When a statement is closed, it should be removed from the HashMap,
otherwise the JVM garbage collection couldn't delete the unused objects.

[TRAFODION-1784]remove closed statement from HashMap

---

core/sql/bin/SqlciErrors.txt
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp
core/sql/ustat/hs_const.h
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_lex.ll
core/sql/ustat/hs_parser.cpp
core/sql/ustat/hs_yacc.y

For [TRAFODION-1775], added a check to UPDATE STATISTICS to return a new error (9243) if UPDATE STATISTICS is attempted on a large table (100,000,000 or more rows) without a SAMPLE clause. Added an explicit NO SAMPLE clause to the syntax to override this check. The value 100,000,000 is not hard-coded; it can be changed via CQD USTAT_YOULL_LIKELY_BE_SORRY.
For [TRAFODION-1777], fixed a minor annoyance. UPDATE STATISTICS on a non-existing object would return three error messages that the object doesn't exist. Changed it to return just one.

[TRAFODION-1775][TRAFODION-1777] UPDATE STATS usability improvements

---

core/sqf/sql/scripts/findPort.py
core/sqf/sql/scripts/lsof.awk

Hi,
Could you please do a quick review of the fix to findPort.py?  In the fix, a new method to find the port numbers in use is added. This method utilizes the command "sudo lsof -i" and then do a simple parsing to grab all these port numbers. If the sudo command is unable to run, then the existing method is called. 
Thanks --Qifan

fix 1795: findPort.py may find some ports that are in CLOSE_WAIT state

---

core/conn/odbc/src/odbc/nsksrvr/Makefile
core/sqf/LocalSettingsTemplate.sh
core/sqf/monitor/linux/makefile
core/sqf/sqenvcom.sh
core/sqf/sqvers
core/sqf/src/tm/Makefile
core/sql/nskgmake/Makerules.linux
install/installer/traf_package_setup
install/traf_tools_setup.sh

Since log4cxx is not available in all Linux distros, we make it a
build-time dependency only, and bundle the shared library for runtime.
This eliminates the installer dependency to check log4cxx package.
The build-time dependency can be satisfied either by installing log4cxx
and log4cxx-devel RPM packages, if available, or by building library
from source.  The traf_tools_setup.sh script is enhanced to download
source code and build this dependency.
@robertamarton @amandamoran

[TRAFODION-1749] Bundle log4cxx library in Trafodion build

---

core/sql/optimizer/ItemExpr.cpp
core/sql/optimizer/NormRelExpr.cpp
core/sql/regress/executor/EXPECTED015.SB
core/sql/regress/executor/TEST015

Create index was failing when bulk load is used to populate the newly created index
Bulk load uses RangePartitionFunction on source table. We get an error when 
source table has timestamp column in key and rangepartitionfunction is used.
Fix is to avoid casting <min>/<max> used internally to TIMESTAMP type.
Change in ItemExpr.cpp
Change in NormRelExpr.cpp (tabs) and executor/test015 is rework for previous PR.

[TRAFODION-1799] create index failed with ERROR[3047]

---

docs/src/site/markdown/documentation.md

Also fix URL of the 1.3 API docs.

[TRAFODION-1699] Expose in-development manuals on documentation web page

---

core/sqf/sql/scripts/genms
core/sqf/src/tm/idtmsrv.cpp

IDs returned from IDTMSRV process should be periodically re-calibrated
so that they are a better approximation of a logical time

Fix for JIRA [TRAFODION-1713]

---

install/traf_tools_setup.sh

This script is for one-time set-up of build environment (aka TOOLSDIR),
but an hour or more is excessive, per the JIRA. So to shrink the time, we kick off all
the builds in background.  All the builds are independent, except
that LLVM depends on udis86.
LLVM is the long pole in build time. Biggest gain is building the
two flavors of LLVM in parallel. All the other tools can be
downloaded and built while we are waiting for LLVM.
Factoring download speed out of the equation (pre-downloaded the source tar files), it took me 26 minutes to build everything. Roughly 50% improvement.

[TRAFODION-1614] Improve time to build external dependencies

---

core/sqf/sql/scripts/dcscheck
core/sqf/sql/scripts/dcsstart
dcs/bin/stop-dcs.sh
dcs/src/main/java/org/trafodion/dcs/server/ServerManager.java

1. handle partially up and operational Trafodion environment.
2. If zookeeper interface gives an error during dcsstop, then explicitly kill the DCS master and servers.

TRAFODION-1757 Improvements to DCS infrastructure:

---

core/sqf/Makefile
core/sqf/src/seatrans/tm/hbasetmlib2/Makefile

Add dependencies in sqf/Makefile to prevent collision of maven
builds downloading dependencies.
Replace spaces in hbasetmlib2/Makefile with tabs. Makefile syntax
requires initial tab for shell commands.

[TRAFODION-1818] Parallel build with maven caused error

---

core/sql/bin/SqlciErrors.txt
core/sql/ustat/hs_const.h
core/sql/ustat/hs_update.cpp

UPDATE STATS sometimes does DDL and DML under the covers, and likes to start its own transactions for this purpose. Trafodion doesn't support mixed DDL and DML in the same transaction. Therefore, it makes sense for UPDATE STATS to check for a user transaction up front, and raise an error if there is one running.

[TRAFODION-1819] Disallow UPDATE STATS in a user transaction

---

LICENSE
licenses/LICENSE-bsd4
licenses/LICENSE-jquery
licenses/LICENSE-js

More updates to license files from the reviews while releasing 1.3.
There was copyright info in code that was not reflected in top-level
license file.

[TRAFODION-1725] Missing license information

---

core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

When $MY_SQROOT/etc/traf_coprocessor.properties is absent, SQL operations fail with
*** ERROR[1394] Trafodion needs to be reinitialized on this system due to missing or corrupted metadata objects. Do 'initialize trafodion, drop' followed by 'initialize trafodion' to reinitialize Trafodion. This will delete all metadata and user objects from the Trafodion database and recreate metadata.
This is incorrect, and doing the steps described does not solve the problem.
Changed the code to instead raise the following error:
*** ERROR[1398] Error 704 occured while accessing the hbase subsystem. Fix that error and make sure hbase is up and running. Error Details:
java.lang.NullPointerException
java.lang.String.contains(String.java:2076)
org.TRAFODION.sql.CoprocessorUtils.addCoprocessor(CoprocessorUti …

[TRAFODION-1831] Improved error msg when properties file is absent

---

core/rest/src/main/java/org/trafodion/rest/ServerResource.java
core/rest/src/main/java/org/trafodion/rest/VersionResource.java

The fix earlier did not fully work when pstack was requested for a specific program.
The sqpstack output had a line with "--" string between the lines with "pstack-ing" and the "ssh -q <host> pstack <pid>" lines and this was not handled in the logic.
An example sqpstack output:
pstack-ing 24162
–
ssh -q node2 pstack 24162
The new fix ignores adding a new line if the string is just "--"

Update fix for TRAFODION-1814

---

core/sql/common/str.cpp
core/sql/common/str.h
core/sql/executor/ExSequence.cpp
core/sql/executor/MdamPoint.cpp
core/sql/executor/MdamPoint.h
core/sql/exp/ExpAtp.cpp
core/sql/exp/ExpAtp.h
core/sql/exp/ExpCriDesc.cpp
core/sql/exp/ExpCriDesc.h
core/sql/exp/ExpSqlTupp.cpp
core/sql/exp/ExpSqlTupp.h
core/sql/exp/exp_tuple_desc.cpp
core/sql/exp/exp_tuple_desc.h

Hi,
This is the work to cover JIRA 1833 "Lack of a display method for ATP, CRI, and TUPP in executor".  Please review. 
These display methods can be called from gdb, or hard coded into the executor. 
Thanks

run-time display methods for Atp, Cri and Tupp.

---

core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/ustat/hs_update.cpp

Fix two bugs:
1. UPDATE STATISTICS on a table with a nullable key column failed, because the CQD ALLOW_NULLABLE_UNIQUE_KEY_CONSTRAINT was not propagated to a child compiler process by the CREATE TABLE LIKE logic. This has been fixed.
2. A buffer overrun can occur when using USTAT_CQDS_ALLOWED_FOR_SPAWNED_COMPILERS with a single CQD. This bug was encountered while debugging the first bug above. This has been fixed.

[TRAFODION-1838] Send CQDs down to child process on CREATE TABLE LIKE

---

core/sql/cli/CliExpExchange.cpp
core/sql/exp/exp_datetime.cpp
core/sql/regress/executor/EXPECTED022.SB
core/sql/regress/executor/TEST022
core/sql/sqlci/Param.cpp
core/sql/sqlci/SqlCmd.cpp

When a datetime value is input as a param or used in a literal, 
it needs to exactly match the corresponding datatype.
For ex: '2010-01-01' is the correct format for DATE datatype.
But it is not the right format for TIMESTAMP datatype.
This is done for values that are input from sqlci, jdbc/odbc params, trafci
and literals.
On the other hand, if a value is converted using the cast function, then
the source value is extended with trailing zeroes.
For ex:  cast ('2010-01-01' as timestamp) will result in '2010-01-01 00:00:00.000'.
These 2 cases are now handled correctly. It was causing a memory overflow
which resulted in a core.
This checkin also fixes an error display bug that was not displaying the correct
datatype.

JIRA TRAFODION-1825. Fix for core caused by input datetime values.

---

core/conn/trafci/manualtests/README
core/conn/trafci/manualtests/statcheck.sql
core/conn/trafci/src/org/trafodion/ci/DatabaseQuery.java
dcs/bin/stop-dcs.sh
dcs/src/main/java/org/trafodion/dcs/master/listener/ConnectReply.java

TRAFODION-1765 - trafci would throw an error when set statistics on 
TRAFODION-1757 - 1) DCS stop script still not handling zookeeper error properly
2) No indication in DCS logs for "No Available Servers" unless
debug level is enabled.

[TRAFODION-1765] trafci would throw an error when set statistics on

---

core/conn/unixodbc/odbc/odbcclient/unixcli/makefile.lnx
core/conn/unixodbc/odbc/odbcclient/unixcli/package/linux64_install.sh
core/conn/unixodbc/odbc/odbcclient/unixcli/package/mklnxpkg.sh
core/conn/unixodbc/odbc/odbcclient/unixcli/package/trafodbclnx_install.sh
install/traf_tools_setup.sh

We keep using our customized suffix from Neoview time, Nv4,
for ICU lib files, this causes confusion to developers who wants
to build Linux ODBC driver. Remove this suffix from the name of
lib files, to get rid of the confusion.

[TRAFODION-1514] Stop using custom suffix (Nv44) of ICU libs.

---

tests/phx/src/test/java/org/trafodion/phoenix/end2end/DescColumnSortOrderTest.java
tests/phx/src/test/java/org/trafodion/phoenix/end2end/ProductMetricsTest.java

(1) MM-DD-YYYY format is no longer supported.  Changed it to MM/DD/YYYY
(2) Added an extra order by column to reinforce the row order of a date column.

Fixed 2 date related issues in phoenix tests

---

core/sql/executor/ExFirstN.cpp
core/sql/executor/ExFirstN.h

This also fixes [TRAFODION-908].
This is the entire or a partial fix to the problem where
a select [first n] * from udf(...) can return more than n rows.
The problem was that neither FirstN nor the UDF operator fully
implemented the GET_N protocol. While that may be ok for the UDF,
the FirstN needed a fix.

[TRAFODION-1850] First N operator no longer returns extra rows.

---

licenses/lic-clients-bin

win-odbc pulls in openssl and zlib.  These licenses are on the list compatible with Apache2.0.
Closing in on all the license info for binary distribution.

[TRAFODION-1836] License info for win-odbc binary dist

---

core/sql/lib_mgmt/Makefile

The earlier pull request passed test, but then it was a long time
before it merged. By time work for 1668 merged, it caused a build error.
The branch is now broken for all builds without this small change.

[TRAFODION-1668] Emergency build fix

---

core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_globals.cpp

Fixes an assertion that happens in UPDATE STATISTICS when: 1. the default character set is UTF8 and 2. statistics already exist on the table.

[TRAFODION-1871] Fix error 2006 in UPDATE STATISTICS

---

core/sqf/Makefile

Cluster install failed with invalid symbolic link for cextdecs.h . This commit addresses that.

Fix symbolic link for cextdecs.h

---

core/sql/regress/tools/runregr_udr.ksh

The problem was reported by Eric over the weekend and Arvind found
the bug and suggested this fix.
The failure occurs when a user installed Hadoop using non-standard ports and if there is no running instance on the default ports.

Fix for a typo in runregr_udr, causing udr/TEST002 failure

---

licenses/lic-clients-bin
licenses/lic-winodbc-bin

Removing TFODBC64 from the client packaging, since there is still
a license issue with pulling in redistributed code from visual
studio.  The existing license info is moved to a new file that is
not added to the LICENSE file during packaging. But it is retained
for future use when the issue can be resolved and win-odbc added back
into the binary distribution.

[TRAFODION-1836] Remove win-odbc license info from clients package

---

tools/docker/Dockerfile
tools/docker/build-base-docker.sh
tools/docker/start-compile-docker.sh

Initial commit of docker file.
- The first (base) image downloads all the dependencies, as described on [Create Build Env](https://cwiki.apache.org/confluence/display/TRAFODION/Create+Build+Environment) page 
- The second (user) image downloads and installs all the tools, as described on [Build Source](https://cwiki.apache.org/confluence/display/TRAFODION/Build+Source) page
For testing, please run the two scripts in order:
`cd ./tools/docker`
`./build-base-docker.sh`
`./start-compile-docker.sh`
The second one will take long as it needs to install the tools. Once the second container is up and running, follow the build instructions: **debug** `source ./env.sh` or **release**

TRAFODION-1878 Initial commit for adding a portable (docker) build env

---

core/sqf/monitor/linux/shell.cxx

Monitor's CClusterConfig class treat all character as lower case when reading the cluster configuration file.
Monitor will not use hostname in normal operation, so convert the hostname into lowercase in shell.cxx will solve the issue

[TRAFODION-1854] Trafodion cannot start on nodes with uppercase hostname

---

core/rest/pom.xml
core/sqf/hbase_utilities/pom.xml
core/sqf/sqenvcom.sh
core/sqf/sql/scripts/get_libhdfs_files
core/sql/nskgmake/Makerules.linux
core/sql/regress/tools/dll-compile.ksh
dcs/pom.xml
install/traf_tools_setup.sh
wms/pom.xml

Make sure various pom.xml files with hadoop dependency are all pulling in
the same version.
Make HDFS dependencies a build-time pre-req. As with other build
dependencies on shared libraries, make them part of the build environment
(TOOLSDIR).
Prior to this change, we were picking up these dependencies (2 shlib &
1 header) from environment (such as local_hadoop) or downloading the
source and building it on the fly. Building it made trafodion build more
than twice as long.
Now requiring a consistent build dependency, separate from the runtime
environment.
The 64-bit native libraries are now available from binary distro of
hadoop-common. So we can download binaries and extract files we need rather
than build them.  Dependencies can be updated via install/traf_tools_setup.sh,
but in case the …

[TRAFODION-1880] Do not build libhdfs dependency from source

---

core/dbsecurity/auth/Makefile
core/sql/exp/ExpHbaseInterface.h
core/sql/optimizer/RelFastTransport.cpp
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp

this is partial changes to Trafodion code base in order to make it compatible with gcc 4.8.
Gcc 4.8 generally is more strict than gcc 4.4, so Trafodion code need to fix all potential issues.
1. variable declared and initialized, but not used anymore
2. suspicious overload of same variable names
3. ld need the required library name to be explicitly added using '-l' option
4. some STL/Boost functions replaced with c++11 features in gcc 4.8, so remove unnecessary call into boost
So there are a lot of changes, to make this process easier, we decided to do this incrementally. Fix small amount of issues each time, easier to code review and test.
It must make sure same code compile and work well under gcc 4.4.
This is the first commit for the whole gcc 4.8 support changes.
We already have a …

[TRAFODION-1868] Compatibility with gcc 4.8

---

core/sql/sqlcomp/CmpSeabaseDDLauth.cpp
core/sql/sqlcomp/CmpSeabaseDDLroutine.cpp

A while back a change was made in the PrivMgr constructors to assume that
authorization is enabled by default instead of the unknown state.  If the state 
is unknown, privilege manager performs I/O to determine its state, otherwise
no additional checking is performed. This was changed because one, the 
authorization check in PrivMgr is expensive and two, the majority of the callers 
already perform the authorization check by looking in the compile context set up 
during process startup.  Role code was not updated to handle this change 
correctly as described in TRAFODION-1696.  Changes were made to check compiler 
context to verify that authorization is enabled  for role commands.

TRAFODION [1696] - drop authorization doesn't drop all roles, and create role will run into internal error

---

core/sqf/monitor/linux/clio.cxx
core/sqf/monitor/linux/monitor.cxx
core/sqf/monitor/linux/shell.cxx
core/sqf/src/seabed/src/msmon.cpp

rework of the previous fix, tested on a real cluster using upper case hostname.

[TRAFODION-1854] rework

---

core/sqf/src/tm/Makefile
core/sqf/src/tm/tm.cpp
core/sqf/src/tm/tmaudit.cpp
core/sqf/src/tm/tmauditobj.cpp
core/sqf/src/tm/tmddlrequests.cpp
core/sqf/src/tm/tmlib.cpp
core/sqf/src/tm/tmpoolelement.h
core/sqf/src/tm/tmrecov.cpp
core/sqf/src/tm/tmregisterregion.cpp
core/sqf/src/tm/tmrmhbase.cpp
core/sqf/src/tm/tmrmtse.cpp
core/sqf/src/tm/tmtime.h
core/sqf/src/tm/tmxarmmain.cpp
core/sqf/src/tm/tmxatxn.cpp
core/sqf/src/tm/tools/Makefile
core/sqf/src/tm/tools/dtmci.cpp
core/sqf/src/tm/xarmapi.cpp
core/sqf/src/tm/xatmapi.cpp
core/sql/optimizer/Stats.h

This is the second part of gcc 4.8 compatibility changes.
Related files are from DTM component.
Major fixed issues:
- unused var
- old C++ array init method
- link options compatible for gcc 4.8
- use NULL as integer, but NULL is a pointer

[TRAFODION-1868] Compatibility with gcc 4.8 , part 2, DTM changes

---

.rat-excludes
dcs/Makefile
dcs/pom.xml
licenses/lic-dcs-bin
licenses/not-dcs-bin

DCS build currently bundles 9 dependent jars. This gives license info on those, as well as additional NOTICE file additions that jython pulls in from Xerces.

[TRAFODION-1828] License info for DCS binary distro

---

core/sqf/sql/scripts/install_local_hadoop

SSCC is long time not maintained and test, and at the time of its writing, it is for HBase 0.98.6.
Remove it for now from install_local_hadoop will help in some times that HBase for no reason to fail to start and just remove it will make it work fine.
Will add it back after more tests of SSCC.

[TRAFODION-1890] disable SSCC entirely in current Trafodion

---

core/sql/cli/Cli.cpp
core/sql/common/ComSmallDefs.h
core/sql/exp/ExpLOB.cpp
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLschema.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

The LOB dependent tables were getting dropped before the actual LOB table was getting dropped in the dropSchema method. Changed that to drop these objects in 2 sequences to avoid this problem.

TRAFODION-1883.Changes to drop LOB dependent tables during drop schema. 

---

core/sql/comexe/ComTdbHbaseAccess.h
core/sql/executor/ExHbaseSelect.cpp
core/sql/generator/Generator.cpp

When doing MDAM scans, we are performing interlaced scan for PROBE and for real scan. The probes always return only 1 row, then we close the scanner immediately, therefore should use always small scanner. I will make it conditional on the existing CQD HBASE_SMALL_SCANNER (ether SYSTEM or ON). In addition, caching of blocks retrieved by probe should always we at least receiving one succesfull cache hit on the next MDAM scan, therefore forcing caching ON for MDAM prob is a good idea. Again, will make this forcing conditional on HBASE_SMALL_SCANNER SYSTEM or ON.
Then for the real scan part of MDAM, I will use the following heuristic: If previous scan fitted in one hbase block, then it is likelly than next will also fit in one hbase block, therefore enable small scanner for next scan. Again …

[TRAFODION-1900] Optimize MDAM scans with small scanner

---

core/sql/bin/SqlciErrors.txt
core/sql/parser/ElemDDLCol.cpp
core/sql/parser/ElemDDLColDef.h
core/sql/parser/StmtDDLCreate.cpp
core/sql/parser/sqlparser.y
core/sql/regress/seabase/EXPECTED010
core/sql/regress/seabase/EXPECTED027
core/sql/regress/seabase/TEST010
core/sql/regress/seabase/TEST027
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/sqlcomp/CmpSeabaseDDLview.cpp

Default clause can now appear in any order during column definition of
a create table or alter table statement.
One can specify any mix of "not null", "default", "constraint..." and other
column attributes.

JIRA TRAFODION-1901 Default clause can appear in any order during create

---

core/sql/generator/GenRelScan.cpp

It was found previous fix will cause abort if the src contains 'full-width' chars. The guess is the pointer length is not enough. So here, I simulate the same behavior as UTF8 before.
asciiType =  new (h) SQLVarChar(sizeof(Int64) ... 
that means the max length is 8, not 4. This is a pointer to real data not the data itself.
With this change I test with:
ＲＥＡＬ
and it works well.

[TRAFODION-1720] rework, fix a bug in it

---

core/sql/arkcmp/CmpStatement.cpp
core/sql/cli/CliExtern.cpp
core/sql/cli/SQLCLIdev.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp

NATableDB is caching a pointer to a HiveClient_JNI object
(HiveMetaData::client_), but that object gets deallocated when a JDBC
client disconnects. Fixing this by keeping the HiveClient_JNI around
across sessions.
Selva and Suresh commented on the first fix and suggested to treat both
HBaseClient_JNI and HiveClient_JNI the same and to remove the CLI
interface that's used to delete these objects.
Therefore, the new fix is to remove this CLI call. It gets called from
two places, one is when an ODBC/JDBC connection closes and the other
is from "initialize trafodion, drop". We believe that neither of them
is needed. Note that we have only one object of each type per CLI
context, and that we delete both objects when we delete the context
(ContextCli::deleteMe()), so there are no leaks.

TRAFODION-1910 mxosrvr crashes on Hive query after reconnect (take 2)

---

tests/phx/phoenix_test.py

Partial-Bug: [TRAFODION-1929]
Temporary disable running tests with maven till root cause is known.

Phoenix T2 tests failing with CDH

---

tests/phx/phoenix_test.py

Change the repository URL to
http://repo.hortonworks.com/content/groups/public/
Note TRAFODION-1929 and TRAFODION-1930 will need a change in
testware to pass in the CLASSPATH till the root cause of Error 706
is known.

[TRAFODION-1930] Phoenix T2 tests failing with HDP during build phase

---

core/conn/jdbc_type2/build.xml
core/conn/jdbc_type4/build.xml
core/sqf/sqenvcom.sh

This will allow distribution of jars directly via maven repos.
Also fix build-time sqenvcom.sh issue. The default empty variables
of APACHE_*_HOME caused existence check of /lib directory, which of
course always exists. Changed default location to "None", so we do
not falsely think we have hbase and query it for classpath.
Removed error checks, since it is fine in the build case to not have those
components.

[TRAFODION-1924] Add license/notice files to jdbc driver jars

---

tests/phx/phoenix_test.py

Per the Jira, the testing automation now invokes the test script in
the trafodion user environment, but that also has the side effect of
making the current directory as trafodion home directory.
The test script already calculates the path where it was invoked,
so changing directory there makes the dependent builds work.

[TRAFODION-1929] Set correct working dir for phx dependency builds

---

NOTICE
core/sqf/sqenvcom.sh
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/IdTmId.java
win-odbc64/odbcclient/DSNConverter/DSNConverter.def
win-odbc64/odbcclient/Drvr35Res/Drvr35Res.rc
win-odbc64/odbcclient/TranslationDll/TranslationDll.def
win-odbc64/odbcclient/TranslationDll/TranslationDll.rc
win-odbc64/odbcclient/drvr35/TCPIPV4/TCPIPV4.RC
win-odbc64/odbcclient/drvr35/TCPIPV6/TCPIPV6.RC
win-odbc64/odbcclient/drvr35/drvr35.rc
win-odbc64/odbcclient/drvr35adm/drvr35adm.rc
win-odbc64/odbcclient/drvr35msg/DrvMsg35.rc

Also removed a redundant license header from one source file.

[TRAFODION-1936] Update copyright banners for 2016

---

core/sql/cli/CliExtern.cpp
core/sql/cli/SQLCLIdev.h
core/sql/cli/sqlcli.h
core/sql/sqlci/SqlciEnv.cpp

The SQL_EXEC_GetAuthState_Internal CLI request has been changed to 
SQL_EXEC_GetAuthState and moved from SQLCLIdev.h to sqlcli.h so it is available
to external callers.

TRAFODION [1944] Check status of authentication and authorization via a CLI call

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java

TransactionManager needlessly retries in doPrepareX when an
UnknownTransactionException is caught

Fix for JIRA [TRAFODION-1935]

---

dcs/src/assembly/all.xml

Zookeeper jar file will now get installed in $DCS_INSTALL_DIR/lib
as was done before TRAFODION-1828. This is similar to how it's
currently been done for REST subsystem.

[TRAFODION-1916] dcscheck fails with cdh5.4.4 and hbase 1.0.0

---

core/sql/sqlcomp/CmpSeabaseDDLschema.cpp

Drop schema cascade internally selects against objects table.
The fix is to use a distinct clause in the internal select query.

Fix for TRAFODION-1948

---

core/conn/jdbc_type4/src/org/trafodion/jdbc/t4/SecPwd.java

Variable hostname is not in use

[TRAFODION-1952]jdbc can not work without config hostname and ip in /etc/hosts on client machine

---

core/sql/executor/ExExeUtil.h
core/sql/executor/ExExeUtilGet.cpp
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/exp/ExpHbaseInterface.h
core/sql/generator/GenRelScan.cpp
core/sql/lib_mgmt/Makefile
core/sql/optimizer/NATable.cpp
core/sql/optimizer/NATable.h
core/sql/optimizer/RelScan.h
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcleanup.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java
core/sql/src/main/java/org/trafodion/sql/HTableClient.java

Removed ByteArrayList class and used array of byte array instead.
Only one JNI to java transistion is done to getRegionStartKeys
and getRegionEndKeys at the time of query compilation
Also fixed an issue with lib_mgmt Makefile.

[TRAFODION-1955] JNI optimization at the time of compilation

---

core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/TEST001

The "length" keyword  for clob/blob is not valid anymore. now the syntax is just blob(10) or clob(8)

Testware fix for udr/TEST001 failure. 

---

core/sql/regress/hive/DIFF018.KNOWN.SB

The diff only happens on cdh an not hdp hence the known diff file. The plan is almost similar on both platforms  but with a slight difference.

Known diff file hive/TEST018 for recent plan change that is non deterministic.

---

core/sql/bin/SqlciErrors.txt
core/sql/regress/executor/EXPECTED130
core/sql/regress/executor/TEST130
core/sql/ustat/hs_const.h
core/sql/ustat/hs_la.cpp
core/sql/ustat/hs_parser.cpp

Histogram statistics on LOB columns do not make sense at the moment; Trafodion does not support them. However, the UPDATE STATISTICS command would fail in odd and diverse ways when asked to create stats on LOB columns. This has been fixed. Now when LOB columns are explicitly referenced in an UPDATE STATISTICS command, an error 9246 will result. When LOB columns are implicitly referenced (e.g., in an ON EVERY COLUMN clause), they will be silently skipped.

[TRAFODION-1978] Report a nice error when attempting UPD STATS on LOBs

---

core/sqf/sql/scripts/makemsg.ksh

There is no need to copy gencat file at build time. Installer will copy it to all nodes during installation.
This in fact will break the build if the dev system happen to installed with pdsh.

[TRAFODION-1874] fix build issues when PDSH installed in build system

---

core/sql/common/Ipc.cpp
core/sql/common/Ipc.h
core/sql/generator/GenPreCode.cpp
core/sql/nskgmake/udr_predef/Makefile
core/sql/optimizer/ValueDesc.cpp
core/sql/sqludr/sqludr.cpp
core/sql/src/main/java/org/trafodion/sql/udr/TupleInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/TypeInfo.java

This also constains a fix for TRAFODION-1710 (setString in UDFs does not accept numeric values with scale) as well as misc small fixes. It may make more sense to review the three commits in this PR separately, as they are on different topics.

TRAFODION-1983 error in preCodeGen plus more items

---

core/sql/executor/ExHbaseIUD.cpp

After each flush during the preparation phase of bulk load, HFile
initialization was taking place redundantly. This imposed significant
overhead and slowed down loads.

[TRAFODION-1971] Avoid redundant reinitialization during bulk load

---

core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h

This is not a definitive fix for the issue of timeouts during Update
Statistics processing for very large tables, but should decrease the
frequency of such occurrences. It extends the fix for TRAFODION-1740
(SHA-1 99a143f29910c7d3c8e02fb1bf101214568bf80a, Dave Birdsall), which
modified the CQDs controlling HBase cache size based on the sampling
rate when the ustat sample table is populated. This commit does the
same thing when the sample can be read directly into memory from the
table being sampled.

[TRAFODION-1974] Limit HBase cache size for ustat direct sampling

---

core/sqf/sql/scripts/install_traf_components

Change install_traf_components to use built target directory
instead of tar file, now that tar file is not produced for DCS and REST.
Submitting to release2.0 branch. Since this is a developer script, end-user is not affected. Not critical for 2.0.0, but can be picked up in next patch release if it does not make this one.

[TRAFODION-1992] Re-packaging server tar file broke install_traf_components

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/RelFastTransport.cpp
core/sql/optimizer/RelFastTransport.h
core/sql/regress/hive/EXPECTED003
core/sql/regress/hive/TEST003

Also TRAFODION-1904 column list in insert/select into Hive table is ignored
Added checks for matching number and data types, so that the
data to be inserted matches the column layout of the Hive target
table.
Using a column list for insert into a Hive table now will raise
SQL error 4223 instead of being ignored (so it is still not supported).

TRAFODION-2002 check columns for Hive inserts

---

docs/provisioning_guide/src/asciidoc/_chapters/prepare.adoc
docs/src/site/markdown/index.md
docs/src/site/site.xml
pom.xml

Change made to comply with the Apache standard.
Also, fixed errors in the provisioning guide regarding passwordless ssh.
Please rebuild **2.0.0** documentation and publish website.

Removed carousel with contributing companies 

---

core/conn/odb/build.bat
core/conn/odb/odb/odb.vcxproj

Add a script to build odb for windows. The target will be copied to
C:\Build\odb. User can modify the PACKDIR to other place if needed .

[TRAFODION-1931]add a script to build odb for windows

---

core/sql/bin/SqlciErrors.txt
core/sql/regress/executor/EXPECTED013.SB
core/sql/regress/executor/TEST013
core/sql/regress/hive/EXPECTED018
core/sql/regress/hive/TEST018
core/sql/sqlcomp/NADefaults.h
core/sql/sqlcomp/nadefaults.cpp
core/sql/ustat/hs_const.h
core/sql/ustat/hs_parser.cpp
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

UPDATE STATISTICS currently does not work on volatile tables in Trafodion. Before this change, it gave confusing and varying error messages when invoked on a volatile table. This code change will cause UPDATE STATISTICS to put out error 9247 "UPDATE STATISTICS is not supported on volatile tables presently" instead.
Ironically, to get this error message to come out in all the right contexts, there were two bugs in CQD logic that needed to be addressed. It is ironic, because we'd have to fix these bugs to make UPDATE STATISTICS work for volatile tables. So, we've taken a small step toward that goal with these changes.
The bugs were in the CQD HOLD and CQD RESTORE mechanism. CQD HOLD essentially allows one to push the current value of a CQD in preparation for setting a different value …

[TRAFODION-2004] UPDATE STATS not supported on volatile tables

---

core/sql/executor/ExExeUtilLoad.cpp
core/sql/executor/ExFastTransport.cpp

SequenceFileWriter java objects had global references on the JNI side.
These references were not deleted because the corresponding JNI objects
were not deallocated. This was causing the java objects leak.

[TRAFODION-2015] hive/TEST018 fails in daily build regressions

---

core/sql/parser/SqlParserGlobalsCmn.h
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_la.cpp

This code change provides new, safer APIs to manipulate the Sql_ParserFlags global.
Or_SqlParser_Flags is intended to replace Set_SqlParser_Flags. It simply turns on whatever bits are requested. If the input parameter is zero, it does nothing, in contrast to Set_SqlParser_Flags, which turns all the bits off in that case.
UnOr_SqlParser_Flags is intended to replace Reset_SqlParser_Flags. It simply turns off whatever bits are requested. If the input parameter is zero, it does nothing, in contrast to Reset_SqlParser_Flags, which turns off all the bits in that case.
For the common use case of a method that simply wants to turn on a few flags then return them to their entry-time state, the new class PushAndSetSqlParserFlags is provided. By coding a single line, one can turn on some flags, and …

[TRAFODION-2020] Safer APIs to manipulate Sql_ParserFlags

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/BindWA.h
core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelUpdate.h

In this particular case, the extra nodes added by index maintenance
and the WHERE clause interacted in a way that caused some missing
characteristic inputs, leading to the generator error.  The fix is to
add the required inputs not directly to the nodes, but as "outer
references" to the BindScope, so that they get added automatically to
any nodes created in that BindScope. Since the predicates get created
by a method called at a higher level, I also needed to add a "remote
control" feature for the BindScope of a MergeUpdate node.
Also: [TRAFODION-2026] Upsert fails on table with nullable key column.
When creating the predicate that links the target clustering key with
the corresponding source values, use "special nulls" semantics for
nullable key columns, so a comparesion NULL = NULL is …

[TRAFODION-2021] Internal error on upsert with index

---

core/sql/optimizer/ScanOptimizer.cpp

If it is known that there will be exactly one probe of the inner child of a nested join, this change enables consideration of MDAM for that inner child.
This is a replacement of https://github.com/apache/incubator-trafodion/pull/174. It takes the suggestion from @zellerh to use the input logical properties instead of adding constraint information to the input physical properties. The result is a much simpler code change. I will close the older pull request shortly.

[TRAFODION-1585] Allow MDAM on inner child of NJ sometimes

---

core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_la.cpp
core/sql/ustat/hs_la.h

The CQD ESTIMATE_HBASE_ROW_COUNT is no longer used anywhere but in
Update Stats, which also uses USTAT_ESTIMATE_HBASE_ROW_COUNT. Both
have to be set before the row count is estimated, and the flawed
logic used in this decision sometimes results in estimation being
performed twice. The former CQD has been removed, the latter set
to ON by default, and the decision logic has been cleaned up.
Also, the estimation is avoided if it is known that it will not
be used (e.g., if sampling is not being used).

Fix problems with use of HBase row count estimate

---

core/sql/sqlcomp/NADefaults.h
core/sql/sqlcomp/nadefaults.cpp

[TRAFODION-2004] In the review for https://github.com/apache/incubator-trafodion/pull/499, @zellerh suggested adding an assert when CQD HOLDs overflow their stack. This has now been done.
[TRAFODION-1775] Pull request https://github.com/apache/incubator-trafodion/pull/292 (released in release 2.0) added a new CQD, USTAT_YOULL_LIKELY_BE_SORRY. Unfortunately it was added as a 32-bit integer, which meant that if one wanted to set it to 10 billion, then that would fail with a validation error. But 10 billion is a reasonable size for a table. This code change changes the validation rule to be a float greater than or equal to 1. So now 10 billion would be possible.

[TRAFODION-2004][TRAFODION-1775] Two follow-on fixes

---

core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

This solves the issue of UPDATE STATISTICS doing select count(*) on large tables. Details are in the JIRA.

[TRAFODION-2041] Turn off bucket cache in HBaseClient estimateRowCount

---

docs/src/site/markdown/documentation.md
docs/src/site/markdown/download.md
docs/src/site/markdown/release-notes-2-0-0.md
docs/src/site/markdown/release-notes-2-0-1.md
docs/src/site/markdown/release-notes.md

Update website with release notes for 2.0.0 and 2.0.1 (up coming).
Re-worked the download page to point to the provisioning guides, rather than try to summarize installation in a release independent way. 
Use apache download guidelines to point to mirror sites for tar-file downloads, but the main apache site for signatures and checksums.
Place-holder for 2.0.1 release download since it is not official yet.

2.0.0 Release Notes

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

[TRAFODION-1684]ODBC: trafodion doesn't support API SQLStatistics.
It's preliminary implementation for ODBC API SQLStatistics. Now, it
will ignore the parameter "Unique".
SQLStatistics returns information as a standard result set.
TABLE_CAT        # support
TABLE_SCHEM      # support
TABLE_NAME       # support
NON_UNIQUE       # support
INDEX_QUALIFIER  # not support
INDEX_NAME       # not support
TYPE             # not support
ORDINAL_POSITION # support
ASC_OR_DESC      # not support
CARDINALITY      # support
PAGES            # not support
FILTER_CONDITION # not support

[TRAFODION-1684]ODBC:preliminary support SQLStatistics

---

win-odbc64/odbcclient/drvr35/cconnect.cpp

windows ODBC return a default catalog name in the output connection string
if input connection string doesn't give a catalog name.

[TRAFODION-1652]SQLDriverConnect can't get catalog name

---

core/sql/bin/SqlciErrors.txt
core/sql/common/OperTypeEnum.h
core/sql/parser/ElemDDLLikeOptions.cpp
core/sql/parser/ElemDDLLikeOptions.h
core/sql/parser/ElemDDLNode.cpp
core/sql/parser/ElemDDLNode.h
core/sql/parser/ElemDDLSaltOptions.h
core/sql/parser/ParDDLLikeOpts.cpp
core/sql/parser/ParDDLLikeOptsCreateTable.h
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED015.SB
core/sql/regress/seabase/EXPECTED040
core/sql/regress/seabase/TEST040
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
docs/messages_guide/src/asciidoc/_chapters/parser_msgs.adoc
docs/messages_guide/src/asciidoc/_chapters/sqlstate.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

Formerly, several clauses (examples: SALT and STORE BY) were allowed on CREATE TABLE LIKE, but were ignored. So, for example, one could say, "CREATE TABLE t2 LIKE t1 SALT USING 6 PARTITIONS", but t2 would end up getting the same salting as t1 instead.
With this change, the parser has been changed so that, except for SALT, specifying these clauses will now result in a syntax error.
For the SALT clause, it is now fully supported with CREATE TABLE LIKE. So, in our example above, t2 would get 6 partitions, and would be salted on the primary key.
A new regression test, seabase/TEST040, has been added to cover this support. The manuals have also been updated, and a few unrelated corrections in CREATE TABLE have been made also.
This pull request also updates the expected results for regression …

[TRAFODION-2044] Support SALT clause on CREATE TABLE LIKE

---

core/sql/optimizer/RelExeUtil.cpp
core/sql/parser/StmtDDLAlterLibrary.h
core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/TEST001
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLroutine.cpp

Library file (.jar, .dll or .so) can now be altered for an existing library 
object. ALTER command will check for existence of new file. Old library
definition will be removed from compiler cache.

[TRAFODION-2039] Add support for ALTER LIBRARY FILE '<file-name>'

---

core/sql/sqlcomp/CmpSeabaseDDLindex.cpp

Have check the code context that it's useless to check current catalog and schema. As the comments, it's used for alter table but it has nothing about current catalog and schema against my testing.

[TRAFODION-1128]Remove current catalog& schema check

---

core/conn/Makefile
core/sql/common/swscanf.cpp
core/sql/common/swsprintf.cpp
install/Makefile
licenses/lic-server-src

TRAFODION-2068: Missing DISCLAIMER files for release package
TRAFODION-2082: BSD-4 license for swsprintf and swscanf unclear
Added DISCLAIMER file to clients and installer packages
Updated BSD license text in swsprintf.cpp and swscanf.cpp

Fixes for TRAFODION-2068 and TRAFODION-2082

---

core/sql/bin/SqlciErrors.txt
core/sql/comexe/ComTdbFastTransport.h
core/sql/executor/ExFastTransport.cpp
core/sql/generator/GenFastTransport.cpp
core/sql/regress/hive/EXPECTED005
core/sql/regress/hive/TEST005
core/sql/regress/hive/TEST005_a.hive.sql
core/sql/regress/seabase/EXPECTED011
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/DefaultValidator.cpp
core/sql/sqlcomp/nadefaults.cpp

cqd hive_insert_error_mode '<val>' has been added to control
insert behavior.
if 0, datatype error check is not done during inserts into hive tables.
Invalid values may get inserted.
This is the behavior prior to this JIRA fix.
if 1, error check done, row is not inserted if conversion error.
Insertion stops. This is new default behavior.
if 2, error check done, row is not inserted if conversion error.
Insertion continues with next row
if 3, null inserted if conversion error.
Insertion processing continues. This is hive behavior.

JIRA TRAFODION-2084 Handling of invalid data inserts into hive tables

---

docs/provisioning_guide/src/asciidoc/_chapters/about.adoc
docs/provisioning_guide/src/asciidoc/_chapters/activate.adoc
docs/provisioning_guide/src/asciidoc/_chapters/enable_security.adoc
docs/provisioning_guide/src/asciidoc/_chapters/introduction.adoc
docs/provisioning_guide/src/asciidoc/_chapters/prepare.adoc
docs/provisioning_guide/src/asciidoc/_chapters/requirements.adoc
docs/provisioning_guide/src/asciidoc/_chapters/script_install.adoc
docs/provisioning_guide/src/asciidoc/_chapters/script_upgrade.adoc
docs/shared/revisions.txt
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

Changed the provisioning guide to include provisioning for Kerberos.
Fixed some links to the provisioning guide in the sql reference document.
Fixed a few issues in the provisioning guide found while adding Kerberos

TRAFODION [2056] Update installation documentation for Kerberos

---

core/conn/jdbc_type2/Makefile

Following the build instruction on wiki in from a bare metal system, JDBCT2 build fail if one doesn't install log4cxx into system location.
Change JDBCT2 Makefile same to all other components to contain log4cxx referenced by LOG4CXX_INC_DIR

[TRAFODION-2089] JDBC_T2 Makefile not add INCLUDE path for log4cxx

---

docs/client_install/pom.xml
docs/command_interface/pom.xml
docs/cqd_reference/pom.xml
docs/jdbct4ref_guide/pom.xml
docs/load_transform/pom.xml
docs/messages_guide/pom.xml
docs/odb_user/pom.xml
docs/provisioning_guide/pom.xml
docs/provisioning_guide/src/asciidoc/_chapters/prepare.adoc
docs/provisioning_guide/src/asciidoc/_chapters/quickstart.adoc
docs/provisioning_guide/src/asciidoc/_chapters/requirements.adoc
docs/provisioning_guide/src/asciidoc/_chapters/script_install.adoc
docs/provisioning_guide/src/asciidoc/_chapters/script_upgrade.adoc
docs/provisioning_guide/src/asciidoc/index.adoc
docs/spj_guide/pom.xml
docs/sql_reference/pom.xml

Provisioning Guide now has a quick-start chapter. Also, fixed minor error
and reordered guided vs. automated mode in install and upgrade chapters.
Changes apply to 2.0.0 and 2.0.1 documentation. Please update website accordingly.

Modified Provisioning Guide and fixed build errors.

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4DatabaseMetaData.java
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

Re-fix SQLGetTypeInfo for JDBC broken.
JDBC and ODBC has different standards of Data Type Code definitions, and we share the same query for getting the information, last commit yesterday broke JDBC getTypeInfo() API. Re-fix it for JDBC API functionality.

[TRAFODION-306] Re-fix

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TmDDL.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseAuditControlPoint.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTmZK.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/TmAuditTlog.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/TrafInfo.java
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java
core/sql/src/main/java/org/trafodion/sql/HBulkLoadClient.java
core/sql/src/main/java/org/trafodion/sql/HTableClient.java
core/sql/src/main/java/org/trafodion/sql/OrcFileReader.java
core/sql/src/main/java/org/trafodion/sql/SequenceFileWriter.java

This time the focus is on hbasetmlib2 improvements

[TRAFODION-1988] Better Java exception handling in Trafodion - Part2

---

core/conn/odb/Makefile
core/conn/odb/src/odb.c

Mispaced paranthesis causes us to take the generic database codepath,
with dbt = 0, instead of dbt = 8 for Trafodion.
All compiler warnings for ODB are now fixed or suppressed.

[TRAFODION-2094] Truncate option slow in ODB

---

Makefile
core/Makefile
install/Makefile
licenses/lic-server-src

This is a backport of Anu's changes and mine from master to generate
installer package from the main makefile and name the package correctly.
Also includes the license typo mentioned in TRAFODION-2093.
These changes are backported in case any more patch releases are needed
for 2.0.x.

[TRAFODION-2092] (Backport to release2.0) Fix installer package name

---

core/sqf/sql/scripts/install_hadoop_regr_test_env

create all TPCDS required table in hive, and genreate data. So it will be easier to run and test using TPCDS queries.
This is helpful for future testing, for example, by introducing 'WITH clause' or 'rollup', one can run a same query in Hive and in Trafodion and compare the result, using real TPCDS queries.
By this change, I also want to check the extra Jerkins test.

[TRAFODION-2096] create all tpcds hive tables from install_local_hadoop

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ValueDesc.cpp
core/sql/regress/seabase/EXPECTED003
core/sql/regress/seabase/TEST003
core/sql/regress/tools/runregr_hive.ksh
core/sql/regress/tools/runregr_seabase.ksh

-- tinyint datatype was not correctly converted to a corresponding
datatype(returned type and input params) in all cases for callers
that dont yet support tinyint/boolean datatypes. This caused phoenix
tests for t4/t2 drivers to fail.
That has been fixed.
-- unsupported datatypes are no longer converted to equivalent
datatypes if select is for a view.
-- swstatus output change was causing seabase/hive regressions to
incorrectly stop and start hadoop. regression scripts have been updated
to reflect the swstatus change.

[JIRA TRAFODION-2060] additional changes to tinyint datatype support (and one more fix)

---

core/sql/bin/SqlciErrors.txt
core/sql/parser/ParKeyWords.cpp
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED005
core/sql/regress/compGeneral/TEST005
core/sql/regress/core/EXPECTED037.SB
core/sql/regress/core/TEST037
core/sql/sqlci/sqlci_lex.ll
core/sql/sqlci/sqlci_yacc.y
core/sql/sqlcomp/parser.cpp
core/sql/sqlcomp/parser.h

initial support new SQL syntax 'WITH', which required in many use cases, for example, in 35 TPCDS queries.
This change will transform the WITH definition into table typed sub-query, so can be used in later compile phases.
As tested, in 35 TPCDS queries that contains WITH, this change pass 19 of them , others due to other syntax gap, like rollup. The passed TPCDS queries include:
q1
q2
q4
q11
q23
q24
q30
q31
q33
q51
q54
q56
q58
q59
q60
q64
q81
q83
q97
Since still not widely tested, this syntax is still protected by MODE_SPECIAL_4 CQD.
Please help to code review it.

[TRAFODION-1673] support with clause

---

core/sqf/sql/scripts/install_hadoop_regr_test_env
core/sqf/sql/scripts/install_local_hadoop

Also removed three dsdgen calls, the *_returns tables are created
together with the *_sales tables, calling dsdgen for those tables will
give an error.

[TRAFODION-2112] Avoid hard-coding DNS name in local Hadoop install

---

core/sql/executor/ex_root.cpp

Removing some leftover debug code causing several "connection refused" messages in mon*.log files during regression runs.Related to [TRAFODION-2091]

Fix for  leftover debug code causing several "connection refused" log messages related to [TRAFODION-2091]

---

core/sqf/sql/scripts/sqstart

add ulimit checking in sqstart
if not proper setup as Trafodion installer does, print WARNING/ERROR
This should only happen in dev environment as described in the JIRA. Installer already handle this, so a WARNING/ERROR print should be enough.

[TRAFODION-1605] sqstart hangs if ulimits not correct

---

core/conn/Makefile
core/sqf/Makefile
core/sqf/sqenvcom.sh

Add RH6-x86_64 to the server and client package names. This gives us
differentiation when we start building on RedHat 7 (TRAFODION-1861).
I also fixed the setting of JAVA_HOME in CentOS 7 environment, which
does not include x86_64 in the path name.
The build does not yet work on CentOS/RedHat 7, due to compiler
differences (TRAFODION-1868).

[TRAFODION-2126] Add OS version and processor type to package names

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4DatabaseMetaData.java
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/DrvrManager/drvrmanager.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/cdesc.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/cstmt.cpp
win-odbc64/odbcclient/drvr35/cdesc.cpp
win-odbc64/odbcclient/drvr35/cstmt.cpp

1.Changed the returned type code of DATE, TIME, TIMESTAMP all to ODBC 3.0 compliance for SQLGetTypeInfo.
2.Changed a few places of using SQL_OV_ODBC3 for ODBC standard version compatibility to use pre-compilation definition ODBCVER for conditioning, which it should be, both Linux and Windows.

[TRAFODION-2100]SQLGetTypeInfo Catalog API should return identifiers conforming to ODBC 3.0

---

install/.gitignore

Jenkins automation is supposed to catch when we miss one, but the
check was not catching everything.  It will be updated when this fix is in.

[TRAFODION-2128] update installer gitignore file

---

core/sql/generator/GenExpGenerator.cpp
core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_update.cpp

1. Fix cores caused by buffer overruns when doing UPDATE STATISTICS on INTERVAL YEAR(1) TO MONTH, TINYINT and LARGEINT UNSIGNED columns. Thanks to @anoopsharma00 for suggesting the  use of CQDs to fix these issues.
2. Add support for BOOLEAN data type in UPDATE STATISTICS.
3. Fix a core in Cast::synthesizeType concerning INTERVAL and TINYINT data types. Thanks to @anoopsharma00 for the code for this fix.

[TRAFODION-2131] Fix UPDATE STATISTICS cores + some other issues

---

core/sqf/src/seatrans/tm/macros.gmk
core/sql/optimizer/BindRelExpr.cpp
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED001.SB
core/sql/regress/compGeneral/TEST001

support of SQL syntax INTERSECT, INTERSECT DISTINCT
not able to support INTERSECT ALL, which will raise an error.
TPCDS quries only need INTERSECT, and the semantics is same, while two child input of INTERSECT must have same number of columns and in same order and each column type must be matching.
Also a minor change to TM Makefile to include log4cxx header file path, if log4cxx is not installed into system include path.

[TRAFODION-2047] add support of SQL syntax INTERSECT

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestGetIndexInfo.java

After this comment, both JDBC type4 and ODBC Catalog API will support
get the information about index.
[TRAFODION-2079]([3rd party tool-Squirrel] indexes won't show up on
objects panel, sql command line works fine) which related to Catalog
API of JDBC type, it is fixed also.

[TRAFODION-2079]Catalog API support get indexes

---

core/sqf/sql/scripts/keepHBaseUp.py

This check-in adds a script, keepHBaseUp.py, that can be used in tandem with developer regressions to keep regressions from getting hung when the local_hadoop HMaster goes away (as it is wont to do on busy workstations). The script periodically checks to see if the HMaster is up. If it isn't, it attempts to start it. It will retry the start, at geometrically longer intervals, until over an hour passes without success, then it gives up.
One way to use this script is to start it running in one shell window, then start the developer regressions in another.
The script logs the times when it does its checks, so the developer can correlate HBase down scenarios with regression test failures.

[TRAFODION-2142] Add script to restart HBase for developer regressions

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java
core/sqf/src/tm/tmlogging.cpp
core/sqf/src/tm/tmlogging.h

The PR 629 for the above JIRA exposed the following issues.
1) A transaction remained in HUNGABORTED state when a table is created and
dropped in the same transaction. core/TEST116 exhibited one such hung aborted
transaction.
2) The retry logic was not throwing any exception when the allowed number
of retry attempts are exhausted.
3) When a UnknownTransactionException is encountered in the response to co-processor
request, the commit was getting into endless loop. privs1/TEST133 was returning error 97
on commit transaction.
All the above issues have been fixed.
[TRAFODION-1988] Better java exception handling in the java/JNI layer of TM
Cleaned up the exception logging in TM further and allowing more events to
be logged via Common Logger facility.

[TRAFODION-2129] Trafodion to avoid use of deprecated HBase APIs/Classes

---

core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java

2016-08-21 22:05:02,531 ERROR dtm.HBaseTxClient: Caught recovery thread exception for tmid: 0 retries: 0
java.io.IOException: Non-migratable/unknown version=1
at org.apache.hadoop.hbase.HRegionInfo.readFields(HRegionInfo.java:895)
at org.trafodion.dtm.HBaseTxClient$RecoveryThread.addRegionToTS(HBaseTxClient.java:967)
at org.trafodion.dtm.HBaseTxClient$RecoveryThread.run(HBaseTxClient.java:1094)

Fix for recovery IOException

---

core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/OptLogRelExpr.cpp
core/sql/optimizer/RelExpr.h
core/sql/regress/compGeneral/EXPECTED011.SB
core/sql/regress/compGeneral/TEST011
core/sql/sqlcomp/nadefaults.cpp

Add support for unnesting subqueries with a groupby in addition to the scalar aggregate. 
Only 1 level of subquery is current supported.
Also unnesting that requires left join is excluded from this change.

[TRAFODION-2159] Unnest correlated subquery with explicit groupby

---

core/sql/optimizer/ColStatDesc.cpp

The statistics automation code was not mapping Hive tables to the appropriate Trafodion catalog and schema for the SB_HISTOGRAMS table. That caused UPDATE STATS ON NECESSARY COLUMNS for Hive tables to fail. This has been fixed.

[TRAFODION-2166] Fix UPDATE STATS ON NECESSARY COLUMNS for Hive tables

---

install/traf_tools_setup.sh

This adds protobuf to traf_tools_setup.sh, which is a script for setting
up build tools for trafodion developers. It skips building protobuf in the case
the right version is already in the path. That would likely be the case for
RH7/Centos7 systems where protobuf2.5 is available in the linux distro.

[TRAFODION-2135] Add protobuf-2.5 to build tools

---

core/sqf/sql/scripts/build_apidocs.sh
core/sql/sqludr/doxygen_tmudr.1.6.config
docs/spj_guide/pom.xml

Adding a new apidocs directory to the Trafodion web site. 
This PR is just for the script to generate the content. Instructions
for generating apidocs for a particular release can be found [here](https://cwiki.apache.org/confluence/display/TRAFODION/Merge+Changes#MergeChanges-PublishWebSiteUpdates).

[TRAFODION-2200] Add Javadoc and Doxygen for UDRs to document build

---

core/sql/cli/Cli.cpp

when CQD mode_special_4 is 'on', the binder try to support Oracle sequence syntax as 'indentifier.nextval'.
Binder will regard the identifier as a sequence object which object_type is 'SG'.
However, the sequence execution code will try to get the current value via such a query in SeqGenCliInterfaceUpdAndValidate():
_**"select  case when cast(? as largeint not null) = 1 then t.startVal else t.nextVal end, t.redefTS from 
(update %s.\"%s\".%s set next_value = (case when cast(? as largeint not null) = 1 then start_value + 
cast(? as largeint not null) else (case when next_value + cast(? as largeint not null) > max_value then max_value+1 else next_value + cast(? as largeint not null) end) end), num_calls = num_calls + 1 where seq_uid = %Ld return old.start_value, old.next_value, old.redef_ts) …

[TRAFODION-2202] in mode_special_4, sequence function is broken

---

core/sql/regress/seabase/EXPECTED032
core/sql/regress/seabase/TEST032
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

couple changes:
1) if dev regressions are being run and regr schema ("trafodion.sch")
doesn't exist, then it is automatically created as part
of the first 'create' stmt. This schema is also updated
as the default schema in DEFAULTS metadata table.
2) if cqd traf_auto_create_schema is set and the schema specified
in a 'create' stmt doesn't exist, then it is automatically
created. This helps with migrating scripts from other vendors
if schema is specified as part of create table stmt.

automatic creation of schemas

---

core/sql/generator/GenExplain.cpp
core/sql/generator/GenRelScan.cpp
core/sql/optimizer/RelScan.h
core/sql/regress/charsets/EXPECTED310
core/sql/regress/charsets/EXPECTED311
core/sql/regress/charsets/TEST310
core/sql/regress/charsets/TEST311

Fixed a problem with occasional failures of regressions, due to
non-deterministic order of results.
Also changed the way we show the number of "retrieved columns" for
Hive and ORC scans. The EXPLAIN now only shows the number of
actually needed columns, not all of them.

[TRAFODION-2219] charsets regression failures and retrieved columns

---

core/sql/common/ComSmallDefs.h
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLschema.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/ustat/hs_globals.cpp

The problem was that when a sample table existed, the DROP SCHEMA code would try dropping it but it had already been dropped when its associated user table was dropped.
The fix is to skip over sample tables when dropping user tables, as the sample tables are dropped automatically when their associated user tables are dropped via DROP TABLE.

[TRAFODION-2187] Fix DROP SCHEMA CASCADE when sample tables are present

---

core/sql/langman/LmRoutineJavaObj.cpp
core/sql/src/main/java/org/trafodion/sql/udr/LmUDRObjMethodInvoke.java

DeleteLocalRef added. ReturnInfo is no longer static. Please see JIRA for an explanation.

[TRAFODION-2218] Memory leak from JVM used for TMUDF compile time interaction

---

core/sql/bin/SqlciErrors.txt
core/sql/regress/compGeneral/EXPECTED023
core/sql/regress/compGeneral/TEST023
core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_const.h

Changed the handling of persistent sample tables (that is, those created by UPDATE STATISTICS ... CREATE SAMPLE) to be the same as those created using the PERSISTENT keyword (that is, those created by UPDATE STATISTICS ... SAMPLE RANDOM PERSISTENT). This is a simpler model; now these tables are used interchangeably.
As before, we still limit a table to having at most one persistent sample table.
Contrary to before, the behavior when creating a persistent sample table (via either syntax) when one already exists has been changed. Before we would silently drop the earlier table; now the UPDATE STATISTICS statement will fail with error 9251. This is better behavior, because it prevents a user from accidentally destroying an existing persistent sample. The user has to explicitly remove it …

[TRAFODION-2220] Change handling of manual persistent sample tables

---

core/sql/sqlcomp/nadefaults.cpp

Incompatible operations are defined as opers between datatypes
that belong to different categories.
For ex, comparison of numeric to string. In these cases, one side
need to be converted to the other before doing the comparison.
This checkin enables following incompatible operations:
-- assignment between incompatible datatypes
-- conversion between incompatible datatypes
-- comparison between incompatible datatypes
-- arith between incompatible datatypes
-- string operation on incompatible datatypes
The infrastructure changes to support was added as part of
a previous jira. Dev regressions have since then been running with
incomp opers enabled.
These operations are on by default now and some operations that
previously failed will no longer fail.
Changes are been tested as much as …

jira TRAFODION-2181 Enable incompatible operations in sql queries

---

core/sql/exp/exp_conv.cpp
core/sql/regress/seabase/EXPECTED003
core/sql/regress/seabase/TEST003

On Linux platform, min 64 bit int value is -9223372036854775808. So the validation seems wrong. Try to fix it.

sql regression test executor test022 fix, min largeint

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/RMInterface.java
core/sqf/src/tm/tmddlrequests.cpp
core/sqf/src/tm/tmddlrequests.h
core/sqf/src/tm/tmtransaction.cpp

SQL calls create and drop requests to transaction manager. However, sometimes in error scenarios, the error codes never reach SQL. This results in sql assuming the operation is successful in failure conditions.
Fix is to propagate the error all the way back to RMInterface and raise exception.

TRAFODION-2148 fix : create drop request error codes never reach SQL

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/regress/hive/DIFF003.KNOWN
core/sql/regress/seabase/EXPECTED032
core/sql/regress/seabase/TEST032

code fix so renamed expressions with order by as shown below work:
select count(*) aa from t order by count(*);
or:
select a+1 aa from t order by a+1;

jira TRAFODION-2184 Fix to order by on renamed expressions

---

core/sqf/src/seatrans/tm/hbasetmlib2/javaobjectinterfacetm.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/javaobjectinterfacetm.h
core/sqf/src/tm/tm.cpp
core/sqf/src/tm/tminfo.cpp
core/sqf/src/tm/tmlogging.cpp
core/sql/executor/JavaObjectInterface.cpp
core/sql/executor/JavaObjectInterface.h

The stack trace of the exception displayed from JNI side now contains the
cause of the exception displayed in a nested way.

[TRAFODION-1988] Better java exception handling in the java/JNI layer

---

tests/phx/src/test/java/org/trafodion/phoenix/end2end/MultiCfQueryExecTest.java
tests/phx/src/test/java/org/trafodion/phoenix/end2end/SaltedTableUpsertSelectTest.java

aligned format and upsert with missing cols issue being tracked by jira trafodion-2247.
When that jira is fixed, phoenix testware changes will be reverted back.

TRAFODION-2234 Updated phx tsts to work around an upsert on aligned table pbm

---

core/sql/regress/executor/TEST106

this test hangs sometimes due to ddl transactions and cancel processing.
Once the issue is fixed, test106 will be updated to run with ddl
transactions.

temporarily turned off ddl transactions during executor/test106

---

core/sql/ustat/hs_globals.cpp

This change fixes a problem that caused regression test compGeneral/TEST023 to fail. It turns out to be an example of both an off-by-one bug and a time-bomb bug. The bug only appears in October. If I had been fortunate enough to have added this test last October or before we would have seen this bug a year ago.

[TRAFODION-2255] Fix off-by-one error in incremental update stats

---

core/sql/exp/exp_conv.cpp

The core was caused by a buffer overrun. With this change the buffer overrun is fixed.

[TRAFODION-2194] Fix update stats core on tinyint unsigned column

---

core/sql/executor/ExExeUtilLoad.cpp
core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_cli.h
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h
core/sql/ustat/hs_la.cpp
core/sql/ustat/hs_log.h
core/sql/ustat/hs_parser.cpp
core/sql/ustat/hs_update.cpp

The following issues in UPDATE STATISTICS concerning long char/varchar columns have been fixed:
1. Creating a sample table would fail if the source table was a Hive table with columns longer than the Trafodion maximum (200000 bytes).
2. UPDATE STATISTICS might fail because the Optimizer raised a 2053 warning during pass 2 optimization.  This warning happens on some queries on Hive tables having columns of over 1 million bytes in length. Now UPDATE STATISTICS will ignore the warning and continue. (The Optimizer does generate a plan in spite of the warning.)
3. UPDATE STATISTICS might abend resulting in a core file when sorting varchars of longer than 32767 bytes.
Design notes:
The 32767 limitation is due to the ISVarChar class using a 2-byte length field. I chose to not increase this to 4 …

[TRAFODION-2251] Fix upd stats issues with long char/varchar columns

---

core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

UPDATE STATISTICS on large tables fails on some cluster installations because the hbase.client.scanner.timeout.period setting is too low. The symptom is that a sample scan fails with a SocketTimeoutException. This change adds code to insure the setting is at least 1 hour.
This is viewed as a short-term fix. The setting is hard-coded in the Trafodion HBase client code. Very soon there will be another change that will abstract this out into some sort of properties file mechanism that is easier to manipulate.
Too, as soon as we migrate to HBase 1.1-based distributions, the HBase heartbeat protocol should eliminate the need for this particular change.

[TRAFODION-2272] Insure adequate hbase.client.scanner.timeout.period

---

core/sql/bin/SqlciErrors.txt
core/sql/executor/dfs2fe.h
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ImplRule.cpp
core/sql/optimizer/Inlining.cpp
core/sql/optimizer/NAFileSet.cpp
core/sql/optimizer/NAFileSet.h
core/sql/optimizer/RelExpr.cpp

I removed obsolete code concerning NSK-style entry-sequenced files from the optimizer and from the error messages. There is a little bit of code in the parser which remains, and is currently stubbed out. I left that there on the chance that in the future we implement a new entry-sequenced concept within Trafodion.

[TRAFODION-2277] Remove obsolete entry-sequenced code from compiler

---

core/sql/bin/SqlciErrors.txt
core/sql/regress/seabase/EXPECTED022
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
docs/messages_guide/src/asciidoc/_chapters/ddl_msgs.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

Problem: The SQL Reference manual describes a CASCADE keyword for ALTER TABLE RENAME, however if you try to use it, you get error message 1427, "Table cannot be renamed. Reason: Cascade option not supported."
Supporting this option seems like a fair amount of work, so for the moment, we've simply removed mention of CASCADE from the SQL reference manual.
While working on this issue, I noticed that the DDL messages section of the Messages Guide is woefully out-of-date. Among other things, it lacks several messages including the message 1427 mentioned above. Fixing all of that is a big job, but with this set of changes I did a small part of it. I added documentation for messages 1420-1429.
While doing this I noticed that ALTER TABLE RENAME to an invalid HBase name produced a very ugly 8448 …

[TRAFODION-2267] Fix ALTER TABLE RENAME documentation

---

core/sqf/sql/scripts/traf_authentication_setup
install/installer/traf_config_setup
install/installer/traf_secure_setup
install/installer/trafodion_install

Fixed a couple of problems with security installation scripts:
- Need to source config file in traf_secure_config before checking HADOOP_TYPE
- Need to check for answer regarding creation of keytabs directory
- Perform traf_user_prompt after determining if LDAP is enabled
- Fixed issue with traf_authentication_setup with ldapcheck results

TRAFODION-2281 - Unable to install Kerberos

---

core/sql/cli/CliExtern.cpp
core/sql/exp/exp_clause_derived.h
core/sql/exp/exp_fixup.cpp

[TRAFODION-2265]
Parse ex_conv_clause::convInstrStrInfo at sql process startup
(in sqInit) into a sparsely populated index for quick reference by
ex_conv_clause::findInstruction.

TRAFODION-2265

---

core/sql/parser/sqlparser.y
core/sql/regress/privs1/EXPECTED120
core/sql/regress/privs1/EXPECTED137
core/sql/regress/privs1/TEST120
core/sql/regress/privs1/TEST137
core/sql/sqlcomp/PrivMgrComponentPrivileges.cpp

Privilege checks were not handling role checks correctly.
PrivMgrComponentPrivileges::hasWGO is now checking privileges against roles.
privs1/TEST137 was updated to test role privileges
priv1/TEST120  was added to test query invalidation with roles
(forgot to add it for a previous check in)

[TRAFODION-1758]: A user has dbroot role can't grant component privilege

---

win-odbc64/odbcclient/drvr35/cconnect.cpp

1.When cancel button of prompt dialog is clicked(IDCANCEL msg is signaled), set WM_QUIT msg's wParam value to 1, to differentiate from ok button click msg processing.
2.When prompt dialog's msg loop finishes(WM_QUIT msg is encountered), if WM_QUIT msg's wParam equals 1, return SQL_ERROR HY000 with additional promption"Operation Aborted." instead of establishing connection to server anyway.

[TRAFODION 1441]ODBC:Cancel button dismisses the SQLDriverConnect prompt dialog but still establish connection

---

core/sql/regress/udr/TEST103
core/sql/sqludr/SqlUdrPredefLogReader.cpp

Today the UDF event_log_reader scans all logs, loads events into memory and
then discards the rows that are not needed.  Waiting until the end to discard
rows takes too much memory and causes system issues.
The immediate solution is to use predicate pushdown; that is, specify predicates
on the query using the event_log_reader UDF to limit the scope of the data flow.
These predicates will be pushed into the UDF so the UDF only returns the
required rows instead of all the rows.  Initially only comparison predicates are
pushed down to the event_log_reader UDF.
In addition to predicate pushdown, a new option has been added to the
event_log_reader UDF - the 's' (statistics) option.  This option reports how
many log files were accessed, how many records were read, and how many records
were …

[TRAFODION-2301]: Hadoop crash with logs TMUDF

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java.tmpl

After a region split the transactions to check against list is not fully populated

Fix for JIRA [TRAFODION-2305]

---

.gitignore
core/Makefile
core/trafodion.spec

Make rpm package to contain same things as server tarball.
Only additional pre-install action is to create the trafodion user.
This mimics the regular installer default action to locate files in
/home/trafodion, owned by trafodion user.
File locations and ownership perhaps ought to be changed, but that is
a separate effort from this initial RPM packaging.

[TRAFODION-2292] Add RPM packaging

---

core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

Following changes:
1. Use REALLOCSQLMXHDLS() after each execute.
2. Avoid missing stats message in repository context
3. Handle memory leak in reprepare (delete of tmpSqlString)

[TRAFODION-2309] Memory leak observed in Repository context

---

core/sql/cli/Cli.cpp

Automatic query retry info was populated, but it got reset as part
of successful retry prepare.

[TRAFODION-1077] AQR info missing from GET STATISTICS

---

core/sql/executor/ExHdfsScan.cpp

Fixes cleanup of SequenceFileReader instance. Without this fix, we see this error where jvm is out of memory,
2016-10-28 17:39:00,079, ERROR, SQL, Node Number: 0, CPU: 0, PIN: 55991, Process Name: $Z001APR, SQLCODE: 8447, QID: MXID11000020372212344459045477158000000000106U3333300_4993_HS_CLI_DYNSTMT, *** ERROR[8447] An error occurred during hdfs access. Error Detail: JNI NewObject() failed

[TRAFODION-2332] SequenceFileReader cleanup.

---

install/installer/traf_cloudera_mods

This was only being done for CDH. This change removes that HDFS setting.

[TRAFODION-2334] Installer should not set namenode heap size

---

.rat-excludes
install/python-installer/README.md
install/python-installer/apache_mods.py
install/python-installer/bashrc.template
install/python-installer/common.py
install/python-installer/copy_files.py
install/python-installer/db_config_default
install/python-installer/db_install.py
install/python-installer/dcs_setup.py
install/python-installer/discovery.py
install/python-installer/hadoop_mods.py
install/python-installer/hdfs_cmds.py
install/python-installer/mod_cfgs.json
install/python-installer/prompt.json
install/python-installer/script.json
install/python-installer/traf_authentication_conf.template
install/python-installer/traf_check.py
install/python-installer/traf_dep.py
install/python-installer/traf_discover.py
install/python-installer/traf_kerberos.py
install/python-installer/traf_ldap.py
install/python-installer/traf_package.py
install/python-installer/traf_setup.py
install/python-installer/traf_sqconfig.py
install/python-installer/traf_start.py
install/python-installer/traf_user.py
install/python-installer/version.json
install/python-installer/wrapper.py

[TRAFODION-1839] Trafodion Installer Evolution

---

core/conn/trafci/.gitignore
core/conn/trafci/src/org/trafodion/ci/UserInterface.java

Even this is a packing issue, it should not take up so many connection.
While got this error, Trafci will retry to setup a new session and  doesn't close existing connection.
The fix is to close previous connection in case that it take up more connections.

[TRAFODION-2338]Try to close connection while got exception

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionalTable.java
core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/ExHdfsScan.cpp

[Trafodion 2325] Reduce path length by avoiding expensive APIs
Load with log error rows missing some error rows being logged.
The hdfs file where the error rows are not logged wasn't closed
Avoided unnecessary copy of the transactional put list

[TRAFODION-2351] Bulk load with log error rows enhancements

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/BindWA.cpp
core/sql/optimizer/BindWA.h
core/sql/optimizer/Inlining.cpp
core/sql/optimizer/RelExpr.h
core/sql/optimizer/RelSequence.cpp
core/sql/optimizer/RelUpdate.h
core/sql/regress/executor/EXPECTED015.SB
core/sql/regress/executor/TEST015
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Changes to transform an upsert plan into an efficient plan when indexes are present and allow for rowset type operations.  The plan makes use of existing operators to eliminate duplicates at the source so we don't need to perform a row at a time check and put operation. The code is currently turned off with a CD traf_upsert_to_eff_tree.

{TRAFODION-1562] Index maintenence performance improvements

---

core/conn/odb/src/odb.c

reason: group mutex etab[i].gmutex was initialized only in etab[0] by
function cimutex() at line 5120. But in gunction gclean(),
etab[1].gmutex, etab[2].gmutex and so on are destoried because of for
loop, so it retruned crashed.
solution: only destrory group mutex in etab[0].

[TRAFODION-2029]odb.exe crashed on windows when several files in src

---

core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h
core/sql/ustat/hs_update.cpp

There are two fixes here.
1. Fix for JIRA TRAFODION-2352: Propagate the CQD HIVE_MAX_STRING_LENGTH_IN_BYTES to the grandchild tdm_arkcmp process if needed to avoid possible error 8446 on Hive tables with very long varchar columns.
2. Fix an unrelated minor problem: Warning 9234 may occur non-deterministically in test scripts for incremental UPDATE STATS. A previous pull request, https://github.com/apache/incubator-trafodion/pull/719, had changed most such warnings so they are emitted only when UPDATE STATS logging is 'ON'. I missed a couple; this change takes care of them.

[TRAFODION-2352] UPDATE STATS may fail with error 8446 on Hive tables

---

core/sqf/src/tm/tmddlrequests.cpp

If the DDL has defined the total cluster key length greater than 2048, it will corrupt the memory and cause various core dump.
the fix is to allocate enough memory for the given key. It is not recommended to use very long clustering key, but should be allowed.

[TRAFODION-2170] certain create table DDL will fail with core dump

---

core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_cli.h
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_log.h
core/sql/ustat/hs_read.cpp

This set of changes revamps the retry logic used by UPDATE STATISTICS.
The problem was that very often in Trafodion when a DDL or DML statement fails, the transaction is aborted. (In predecessor products, the statement itself often could be rolled back without aborting the transaction containing it.) The retry loop in HSFuncExecQuery did not take this into account, so most retries would ultimately fail with a confusing and uninformative error 8605 (“Committing a transaction which has not started.”).
Therefore, the retry logic has been redesigned. The logic to begin and commit transactions has been pushed down into the retry loop. The retry loop has been moved to a new function, HSFuncExecTransactionalQueryWithRetry, while the old function, HSFuncExecQuery, is now limited to non-retryable …

[TRAFODION-2341] Redesign UPDATE STATISTICS retry logic

---

core/sql/exp/ExpPackDefs.cpp
core/sql/exp/exp_clause.cpp
core/sql/exp/exp_clause.h
core/sql/exp/exp_function.cpp
core/sql/exp/exp_function.h
core/sql/generator/GenItemFunc.cpp
core/sql/optimizer/BindItemExpr.cpp
core/sql/optimizer/ItemExpr.cpp
core/sql/optimizer/SynthType.cpp
core/sql/parser/ParKeyWords.cpp
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED006.SB
core/sql/regress/compGeneral/TEST006

Support SQL builtin function SOUNDEX() like Oracle does. It allows you compare words that are spelled differently, but sound alike in English, which is useful for searching people's names that sound alike, e.g. “Ruoyu” and “Roy”

[TRAFODION-2358] Implement builtin function SOUNDEX

---

core/sql/exp/exp_math_func.cpp
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED006.SB
core/sql/regress/compGeneral/TEST006

Like Oracle does, the function LOG() function supports 2 parameter of call, in this way, the 1st parameter is the radix, and the second one is power, the function returns the logarithm.
This change implement this, and still, the user can call it with only one parameter (form LOG(X)), in which case the parameter X will be the power, and the function just returns the natural logarithm of X. This is also compatible with MySQL.

[TRAFODION - 2345] Support LOG() function of any base

---

core/sqf/sql/scripts/analyzeMessageGuide.py

This new script is designed to help automate development work on the Messages Guide. In its initial guise, the script does the following:
1. Compares the text in SqlciErrors.txt with that in the Messages Guide
2. Produces a report of mismatched messages. For each mismatched message it shows:
a. The message text in each of SqlciErrors.txt and the Messages Guide
b. Any enums used in the code to refer to the message number
c. A list of regress tests whose expected files might have examples of the message
d. Optionally, a list of all C++ source files with possible references to the message number (this option is very slow unfortunately)
With this information a developer can quickly identify what messages in the Message Guide are out-of-date or missing. If the developer decides to change the …

[TRAFODION-2380] New script to help automate Message Guide updating work

---

core/conn/odbc/src/odbc/Common/QSData.cpp
core/conn/odbc/src/odbc/Common/QSData.h
core/sql/bin/SqlciErrors.txt
core/sql/common/ComSSL.cpp
core/sql/common/ComSSL.h
core/sql/common/OperTypeEnum.h
core/sql/exp/ExpErrorEnums.h
core/sql/exp/ExpPackDefs.cpp
core/sql/exp/exp_clause.cpp
core/sql/exp/exp_clause.h
core/sql/exp/exp_function.cpp
core/sql/exp/exp_function.h
core/sql/generator/GenItemFunc.cpp
core/sql/nskgmake/common/Makefile
core/sql/optimizer/BindItemExpr.cpp
core/sql/optimizer/SynthType.cpp
core/sql/parser/ParKeyWords.cpp
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED006.SB
core/sql/regress/compGeneral/TEST006
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Add two functions which used to encrypt and decrypt the data using the
official AES (Advanced Encryption Standard) algorithm.
AES_ENCRYPT(str, key_str[, init_vector])
AES_DECRYPT(crypt_str, key_str[, init_vector])
Both these two function have optional init_vector argument which
provides an initalization vector for block encryption modes that
require it. For modes that require the optional init_vector argument, an error
occurs if init_vector is missing. For modes that don't need
init_vector, it will raise a unused argument waring if init_vector is
provided.
The new CQD block_encryption_mode controls the mode for
block-based
encryption algorithm. The default value is 0, which use
aes-128-ecb.
Here is the list for diffferent values for
block_encryption_mode
CQD value          algorithm
0 …

[TRAFODION-2228]Add AES_ENCRYPT/AES_DECRYPT functions

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/cdiag.cpp
win-odbc64/odbcclient/drvr35/cdiag.cpp

Acoording to ODBC reference, in function SQLGetDiagRec,  param _TextLengthPtr_  should point to a buffer in which to return the total number of characters, but it returns number of truncated characters when param _BufferLength_ is smaller than character number of error message text.
Thus, modifications are made relating to win/unix odbc driver code as following:
Unix ODBC: if truncation occurs, return SQL_SUCCESS_WITH_INFO, and set variable strLen as total number of error message text whenever data is truncated.
Windows ODBC: set variable strLen as total number of error message text whenever data is truncated.

[TRAFODION-2375]ODBC:SQLGetDiagRec return wrong msg length when data truncate

---

core/conn/odbc/src/odbc/nsksrvr/Makefile
core/conn/odbc/src/odbc/nsksrvrcore/Makefile

The test suite fails becuase pthread_mutex_unlock returns EPERM error
pthread_mutex_lock and pthread_mutex_unlock always return success when
a program is not linked with -lpthread option. It is linked this way
when a multi-threaded program is run in single thread mode to avoid the
overhead of locking.
The mxosrvr program is now linked with -lpthread. However, it is not
clear how and why it would fix the EPERM error returned from
pthread_mutex_unlock API. But it is good to ensure that mxosrvr .sos and
the binaries are compiled with -lpthread.
Will revisit this issue if the problem persists.

[TRAFODION-2314] MXOSRVR sometimes exit abnormally with NAMutex assert

---

core/conn/trafci/Makefile
core/conn/trafci/build.xml
core/conn/trafci/install/Installer.java-tmpl
core/conn/trafci/installer_pom.xml
core/conn/trafci/pom.xml
core/conn/trafci/src/main/java/org/trafodion/ci/ConsoleReader.java
core/conn/trafci/src/main/java/org/trafodion/ci/Session.java
core/conn/trafci/src/main/resources/install_jar.xml
core/conn/trafci/src/main/resources/install_tar.xml
core/conn/trafci/utils/trafci_install.sh

trafci should support up, down, left, right key in the keyboard

[TRAFODION-2211] trafci can use history cmd

---

core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp

APIs used to clear compiler caches had changed, leading to syntax errors.
Modified the following -
DELETE ALL FROM TABLE(QUERYCACHE());
to
DELETE ALL FROM TABLE(QUERYCACHE('ALL','LOCAL'));

[TRAFODION-2411] Conn aborted when connecting with a reregisterd user

---

core/sql/exp/exp_datetime.cpp
core/sql/exp/exp_datetime.h
core/sql/optimizer/BindItemExpr.cpp
core/sql/parser/sqlparser.y
core/sql/regress/seabase/EXPECTED030
core/sql/regress/seabase/TEST030
docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc

This set of changes does the following:
1. Adds documentation for the TO_CHAR function to the SQL Reference Manual.
2. Fixes four bugs:
a. TO_CHAR(x), where x is a TIME column, would sometimes have garbage characters at the end of it. This has been fixed.
b. TO_CHAR(x,'YY/MM/DD') produces garbage output when x is a TIME column, because x has no date fields. This has been fixed. A 4072 error is now raised instead.
c. TO_CHAR(DATE '2016-03-01', 'YYYYMMDDHH24MISS') returns an incorrectly formatted value, '2016030100:00:'. This has been fixed; it now returns the correct value '20160301000000'.
d. DATEFORMAT(5,USA) returns an error 4071 (as it should), but the error message text says "TO_CHAR" instead of "DATEFORMAT". This has been fixed.
3. Updates to regression test seabase/TEST030 and its …

[TRAFODION-2394] Add documentation for TO_CHAR + fix some bugs in it

---

core/sql/optimizer/TransRule.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Trafodion has a rule that pushes a groupby down over a join when possible, but it will not push the groupby to the left child of a join - it relies on join commutativity. This might have been ok 20 years ago when this was coded (by me...), but it isn't good for some situations today. Example:
select d.y, count(f.a), sum(f.b)
from big_fact f join small_dim d on f.x=d.y
where d.a = 1
group by d.y
The plan we would like is a hash join with the group by on big_fact as the left child. To do this, we need to remove the heuristic that prevents this form of push-down.

[TRAFODION-2418] Allow group by push-down to a fact table

---

core/sql/executor/hiveHook.cpp
core/sql/qmscommon/QRLogger.cpp

populateSortCols was flagged as major perf offender during profiling
the reason being an unbound iterative string search on huge string.
Added a minor fix: When not setting category in log conf file, extra code is executed, potentially impacting performance

[TRAFODION-2422]

---

core/sqf/Makefile
core/sqf/sqenvcom.sh
core/sqf/sql/scripts/install_traf_components
core/sqf/sysinstall/etc/init.d/trafodion
core/sqf/sysinstall/etc/security/limits.d/trafodion.conf
core/sqf/sysinstall/etc/sudoers.d/trafodion
core/sqf/sysinstall/home/trafodion/.bashrc
core/trafodion.spec
dcs/conf/dcs-env.sh
install/installer/dcs_installer
install/installer/rest_installer
install/installer/traf_add_ldap
install/python-installer/scripts/dcs_setup.py
install/python-installer/scripts/traf_ldap.py

Simplify install operations for dcs and rest by setting default values
in env files. Also make trafci use config files rather than have hard-coded
setting. This reduces code in existing command-line installers.
Add system setting files to RPM. These files are stored in core/sqf/sysinstall.
The existing command-line installers could also take advantage of these files,
but it is not required, and I have not made those changes in this commit.

[TRAFODION-2417] Installer pre-work for ambari integration

---

dcs/src/main/java/org/trafodion/dcs/Constants.java
dcs/src/main/java/org/trafodion/dcs/util/RetryCounter.java

once down & up a node there will cost a few time , currently the check policy of whether node up is check&wait ( (2^attempts)*5 ), the wait time is 10s-20s-40s-80s-160s-320s, totally will be 630s. 
now after check, normally, it will cost about 11s to up a node, so the first wait should be longger than 10s, and be more smooth, now there use ( log(attempts+15)*5 ), the wait time will be 13.5s-13.8s-14.1s-14.4s-14.7s-14.9s, total time is 75s.

TRAFODION-2421

---

core/sql/optimizer/BindItemExpr.cpp
core/sql/optimizer/costmethod.cpp
core/sql/regress/seabase/EXPECTED030
core/sql/regress/seabase/EXPECTED032
core/sql/regress/seabase/TEST030
core/sql/regress/seabase/TEST032
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

-- TRAFODION-2442 timestamp comparison with date returns incorrect results.
that has been fixed. Date value is expanded to timestamp datatype and
then compared.
Fix is for timestamp/date comparison only.
TIMESTAMP comparison to TIME, and DATE comparison to TIME is not allowed.
-- row length of aligned format tables is now calculated correctly and
stored in metadata.
-- optimizer cost method for sort had a high limit of MEMORY_UNITS_SIZE
default set to 20M. For large rows in the range of 10 Mb,
this caused an overflow.
Fix is to allocate space for MAXOF default and size of 2 rows.

TRAFODION-2442  timestamp/date comparison bug. And couple other fixes.

---

core/sqf/sql/scripts/install_apache_hadoop
core/sqf/sql/scripts/install_local_hadoop
core/sqf/sql/scripts/update_hbase
docs/provisioning_guide/src/asciidoc/_chapters/prepare.adoc
docs/provisioning_guide/src/asciidoc/_chapters/quickstart.adoc
docs/provisioning_guide/src/asciidoc/_chapters/script_install.adoc
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/service_advisor.py
install/installer/traf_cloudera_mods
install/installer/traf_hortonworks_mods
install/python-installer/configs/mod_cfgs.json

This changes all install methods to no longer touch the log splitting
property.

[TRAFODION-2426] Do not set hbase master log splitting property

---

install/python-installer/scripts/common.py
install/python-installer/scripts/traf_setup.py
install/python-installer/scripts/traf_user.py
install/python-installer/scripts/wrapper.py

remove unused templates folder.
copy bashrc file in 'traf_setup' step, because trafodion package is not extracted in 'traf_user' step.

[TRAFODION-2450] copy file error for python-installer/templates

---

core/sql/regress/executor/DIFF015.KNOWN
core/sql/regress/tools/runregr_compGeneral.ksh

executor/TEST015 is being tracked by TRAFODION-2438. A known diff file
is being created to handle the diff.
compGeneral/TEST042 failure is being tracked by TRAFODION-2457. Once
that jira is fixed, this test will be re-enabled.

handling of known failures for executor/TEST015 and compGeneral/TEST042

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/TrxRegionEndpoint.java.tmpl
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java

Queries such as drop schema cascase involve multiple DDL operations that take some time to process. This cause transaction commits to timeout and cause transaction aborts. Fix is to detect long prepare scenarios and continue to commit the transaction.
Cleanup Chore thread calls were deprecated and required chore service constructs. This should help memory cleanup issues in end point co processor. This should also help some of the regression test failure we see in executor/TEST130

[TRAFODION-2150] and [TRAFODION-2151] TM long prepare and chore thread Issues

---

core/sqf/export/limited-support-tools/LSO/README
core/sqf/export/limited-support-tools/LSO/offender
core/sql/cli/Context.cpp
core/sql/executor/ExStats.cpp
core/sql/executor/ExStats.h
core/sql/executor/ex_frag_rt.cpp
core/sql/executor/ex_root.cpp
core/sql/runtimestats/ssmpipc.cpp

Added yet another offender feature to list query ids that has a total
IO time for any storage engine opertor consuming longer than a given
number of seconds.
./offender -s se_offender
Will list the query ids along with the table name. SEE
$TRAF_HOME/export/limited-support-tools/LSO/README
The "Number of SQL Processes" counter is now made multi-fragment aware
and hence contains the actual number of ESPs used + 1 for master
process.

[TRAFODION-2420] RMS Enhancements

---

core/sql/arkcmp/CmpStatement.cpp
core/sql/arkcmp/CmpStatement.h
core/sql/bin/SqlciErrors.txt
core/sql/comexe/ComTdbHdfsScan.h
core/sql/executor/ExHdfsScan.cpp
core/sql/executor/ExHdfsScan.h
core/sql/exp/ExpLOBinterface.h
core/sql/generator/GenPreCode.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ColStatDesc.cpp
core/sql/optimizer/ColStatDesc.h
core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/OptLogRelExpr.cpp
core/sql/optimizer/RelExeUtil.cpp
core/sql/optimizer/RelExeUtil.h
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelExpr.h
core/sql/optimizer/RelGrby.h
core/sql/optimizer/RelJoin.h
core/sql/optimizer/RelMisc.h
core/sql/optimizer/RelScan.h
core/sql/optimizer/RelSet.h
core/sql/optimizer/VEGTable.cpp
core/sql/optimizer/ValueDesc.cpp
core/sql/optimizer/ValueDesc.h
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED045
core/sql/regress/compGeneral/TEST045
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

This includes various fixes in addition to the heuristic decision,
mainly an improvement on how to navigate between parent and child
common subexpressions and improvement of support for statistics.
Also, see the comment in RelMisc.h (class CommonSubExprRef) for
a definition of some terminology.

[TRAFODION-2315] Heuristic decision for common subexpressions

---

install/.gitignore
install/ambari-installer/Makefile
install/ambari-installer/meta.template
install/ambari-installer/mpack-install/am_install.sh
install/ambari-installer/mpack.json
install/ambari-installer/repo.template
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodiondcs.py
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodionnode.py
install/ambari-installer/traf_ambari.spec

Enhance traf_ambari RPM to call upgrade-mpack instead of install-mpack
when we are upgrading the mpack.  Unfortunately, the upgrade-mpack command
does not (yet) seem to do the needed things.  More tweaks may be needed
in the future to support upgrade from trafodion 2.1.0 to later release.
Also support removal of the RPM to clean up everything.

[TRAFODION-2452] Fix upgrade or removal of Ambari mpack

---

install/python-installer/scripts/hadoop_mods.py

When kerberos is enabled in HDP, there would be some security related properties set in `hbase.coprocessor.region.classes`, pyinstaller should not overwrite it. So the solution is to add these additional properties when install on a kerberos enabled HDP environment.

[TRAFODION-2460] pyinstaller-should not overwrite previous hbase.coprocessor.region.class settings when modify HDP settings.

---

install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodionnode.py

Trafodion works fine with 1.7 or 1.8.

[TRAFODION-2446] Remove java 1.8 check from ambari plug-in

---

core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_parser.cpp

This set of changes fixes two problems (both introduced by me):
1. When UPDATE STATISTICS retries a statement, and the statement continues to fail, the error diagnostics are incorrect. The root cause of the error is not reported, and some irrelevant errors are reported (i.e. 8609, error on transaction rollback, which happens because the Executor sometimes has already rolled back the transaction when UPDATE STATISTICS attempts a ROLLBACK after a statement failure). This bug was introduced when I rewrote the retry logic in JIRA TRAFODION-2341. My unit test was not thorough enough. (ustat/hs_cli.cpp)
2. Performing UPDATE STATISTICS ON EXISTING COLUMNS PERSISTENT would fail on Hive tables with varchar columns over 200000 characters long. I fixed a similar issue in JIRA TRAFODION-2322, but …

[TRAFODION-2465] Fix two bugs

---

core/sql/pom.xml
core/sql/sqludr/sqludr.cpp
core/sql/src/main/java/org/trafodion/sql/udr/ColumnInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/ComparisonPredicateInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/ConstraintInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/OrderInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/ParameterListInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/PartitionInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/PredicateInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/TMUDRSerializableObject.java
core/sql/src/main/java/org/trafodion/sql/udr/TableInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/TupleInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/TypeInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/UDR.java
core/sql/src/main/java/org/trafodion/sql/udr/UDRInvocationInfo.java
core/sql/src/main/java/org/trafodion/sql/udr/UDRPlanInfo.java

Just setting the desired degree of parallelism often doesn't
actually choose a parallel plan, the UDF writer may also need
to specify an estimate of the number of rows produced.
Also made the methods that are not intended for the UDR writer
package-private (no qualifier). This has two good side-effects: One is
that UDR writers no longer can call these methods (accidentally) and
the other is that we can set Javadoc to display only public methods,
which suppresses these package-private methods.

[TRAFODION-2456] Improve documentation for UDF parallelism

---

core/sql/regress/compGeneral/EXPECTED042
core/sql/regress/compGeneral/FILTER042
core/sql/regress/compGeneral/TEST042
core/sql/regress/tools/runregr_compGeneral.ksh

Implemented suggestions made by Suresh and Selva. Suresh found out
that the test gives different results when authorization is
initialized, and that caused problems because it is usually
initialized on developer workstations but not on Jenkins.
Suresh and Selva suggested to suppress the key length, since that can
vary with different CQD settings like SCHEMA.
Added the queries to the log and expected files to see whether that
will make failure diagnosis easier. The queries get filtered out, so
should not cause test failures.

[TRAFODION-2457] Re-enable compGeneral/TEST042 and try to stabilize

---

core/sql/optimizer/NATable.cpp

Make sure we complete a partial region start key for a datetime column
such that year, month and day are set to at least 1.

[TRAFODION-2467] HBase region start key straddling a datetime key error

---

core/sql/optimizer/ImplRule.cpp

During upsert into table with index there is a temporary scan in optimizer.
If index access path is chosen for this scan, query would raise an error.
This is now fixed by using the correct indexDesc from this temporary scan.

[TRAFODION-2464] failure to upsert into a table with an index

---

core/sql/parser/SqlParserAux.cpp

The function literalOfNumericPassingScale (parser/SqlParserAux.cpp) is used to parse literals into ConstValue nodes and encoded values. It was incorrectly handling signed numeric literals of 20 characters in length: it would encode these as an unsigned 64-bit integer, then create a signed SQLLargeInt or SQLNumeric with that unsigned encoded value. One symptom of this is that histograms for NUMERIC datatypes would encounter 6004 errors (out-of-order histogram intervals) if there were some values requiring less than 20 characters and others requiring 20 or more.
The fix here reverts to using SQLBigNum instead for such values.

[TRAFODION-2470] Fixed one cause of 6004 warnings

---

core/sqf/export/include/dtm/tm.h
core/sqf/src/tm/tmlib.cpp
core/sqf/src/tm/tmlib.h
core/sqf/src/tm/tools/dtmci.cpp

Created a new API TMCLIENTEXIT in TM library to clean up
opens. dtmci now calls this API before exiting

[TRAFODION-2469] TM clients like dtmci don't exit cleanly

---

core/sql/cli/memorymonitor.cpp
core/sql/cli/memorymonitor.h
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

Two minor changes found as result of some experiments:
Add a cardinality hint to a join query used during drop constraint.
This should cause us to use a nested join, reducing the chances of
a write conflict during commit processing.
Also added debugging support for memory pressure, setting an environment
variable allows to log the parameters to a file. It's best to use
this with a single sqlci tool, like this:
export SQL_MEMMONITOR_LOGFILE=mylogfile
sqlci
Sample output:
Fri Feb  3 01:33:42 2017: pctFree=0.274771, pageFaultRate=24.115740, (free*normpagefault*commitratio) = (-0.099085 * 0.246121 * 0.535585), pressure=0
Fri Feb  3 01:33:48 2017: pctFree=0.274772, pageFaultRate=25.187914, (free*normpagefault*commitratio) = (-0.099086 * 0.257064 * 0.535585), pressure=0
Fri Feb  3 01:33:54 …

Improve concurrency of drop constraint, log memory pressure

---

core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

A previous change for this JIRA to CmpSeabaseDDL::createSeabaseTableExternal meant to use a CQD for maximum column length but used a hard-coded constant instead. This change just replaces the hard-coded constant with the intended CQD. (Compare with the use of this CQD in CmpSeabaseDDLcommon.cpp.)

[TRAFODION-2442] Small correction to previous fix

---

core/sql/generator/GenPreCode.cpp

Transaction DDL for alter commands is currently disabled. 
There are few statements such as alter hbase option that is not disabled which results in unpredictable errors. 
Initially fix would be to disable alter statement to not use DDl transaction. 
Following this initial fix,  DDL transaction would be enhanced to support of Alter table statement.

[TRAFODION-2472] disable transactional alter command for hbase options.

---

core/sql/common/NAMemory.cpp
core/sql/exp/ExpLOBinterface.cpp
core/sql/generator/GenPreCode.cpp

Fixes as suggested by @selvaganesang and @sandhyasun 
We were hitting the code to make heap thread safe repeatedly while running
jdbc and phoenix tests.
PROCESS_LOB flag was being set incorrectly in some cases.
Unlocking a mutex owned by a different thread lead to the assertion.
This could also result in heap corruption.

[TRAFODION-2314] MXOSRVR sometimes exits abnormally with NAMutex assert

---

install/python-installer/scripts/hdfs_cmds.py

The old command doesn't work.
also change the owner of HDFS directory /user/trafodion

[TRAFODION-2471] pyinstaller: error command when grant privilege in HBase.

---

core/sqf/sql/scripts/sqnodestatus

specify the '-q' command to ignore ssh banner.

[TRAFODION-2473] sqnodestatus report wrong status if ssh banner is configured.

---

install/python-installer/db_install.py

Avoid using cfgs directly in line 501 `if` statement, don't make the key avaiable in the dict.

[TRAFODION-2487] pyinstaller - error handling home_dir variable

---

core/sql/comexe/ComTdb.h
core/sql/comexe/ComTdbExeUtil.cpp
core/sql/comexe/ComTdbExeUtil.h
core/sql/executor/ExComTdb.cpp
core/sql/executor/ExExeUtil.h
core/sql/executor/ExExeUtilGet.cpp
core/sql/executor/ExExeUtilMisc.cpp
core/sql/generator/GenRelExeUtil.cpp
core/sql/optimizer/RelExeUtil.cpp
core/sql/optimizer/RelExeUtil.h
core/sql/parser/ParKeyWords.cpp
core/sql/parser/sqlparser.y
core/sql/regress/hive/EXPECTED005
core/sql/regress/hive/EXPECTED007
core/sql/regress/hive/TEST005
core/sql/regress/hive/TEST007
core/sql/regress/seabase/EXPECTED003
core/sql/regress/seabase/EXPECTED031
core/sql/regress/seabase/EXPECTED033
core/sql/regress/seabase/TEST003
core/sql/regress/seabase/TEST031
core/sql/regress/seabase/TEST033
core/sql/sqlci/sqlci_lex.ll
core/sql/sqlci/sqlci_yacc.y
core/sql/sqlcomp/parser.cpp

Syntax:
process hive statement '<string>';
<string>: hive statement starting with create/drop/alter/truncate.
These are the only stmts currently supported.
Ex:
>>process hive statement 'create database trafsch';
will create hive database 'trafsch'
>>process hive statement 'create table trafsch.t (a int)';
will create hive table 't' in hive schema 'trafsch'.
'process hive statment ..' could be issued from any traf interface
(sqlci/trafci/jdbc...)

TRAFODION-2498 Add support to run hive stmts from traf interface

---

core/sql/executor/ExUdr.cpp

Added check to avoid clearing out the error when source and
destination diags area are the same.

[TRAFODION-2499] TMUDF does not pass error to client

---

install/python-installer/configs/db_config_default.ini
install/python-installer/db_install.py
install/python-installer/db_uninstall.py
install/python-installer/discovery.py
install/python-installer/scripts/apache_mods.py
install/python-installer/scripts/common.py
install/python-installer/scripts/constants.py
install/python-installer/scripts/copy_files.py
install/python-installer/scripts/dcs_setup.py
install/python-installer/scripts/hadoop_mods.py
install/python-installer/scripts/hdfs_cmds.py
install/python-installer/scripts/traf_discover.py
install/python-installer/scripts/traf_kerberos.py
install/python-installer/scripts/traf_ldap.py
install/python-installer/scripts/traf_package.py
install/python-installer/scripts/traf_setup.py
install/python-installer/scripts/traf_sqconfig.py
install/python-installer/scripts/traf_start.py
install/python-installer/scripts/traf_user.py
install/python-installer/scripts/wrapper.py

Put constants together into a new constants.py file. It will be easy to modify them to fit new Hadoop environment.
along with some minor fixes:
1. kill krb5service and delete status file in uninstall script
2. fix hbase_lib_path issue while install trafodion on apache hadoop
3. typo in db_config_default

[TRAFODION-2496] pyinstaller - better handle constants

---

core/sql/common/conversionLocale.cpp
core/sql/exp/exp_function.cpp
core/sql/exp/exp_function.h
core/sql/generator/GenItemFunc.cpp
core/sql/regress/charsets/EXPECTED314
core/sql/regress/charsets/TEST314
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Right now we ignore such invalid characters and also may truncate
the string at the point of the invalid char. The expected behavior
would be an error.
The only type of invalid data I could create with regular SQL syntax
is an invalid UTF-16 surrogate pair. We have no checks that detect
those when we enter the data. Invalid UTF-8, on the other hand, is
rejected when we try to insert it in the database (at least in the
case I tried).
The fix adds a check to generate an error (file conversionLocale.cpp).
It also adds two CQDs to suppress the error (remaining code files)
and to replace the invalid character with a replacement character.
Right now we use "?", even for Unicode, which has a special replacement
character, see TRAFODION-2515.

[TRAFODION-2477] Invalid characters in translation are ignored

---

core/sql/parser/sqlparser.y
core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/EXPECTED107.SB
core/sql/regress/udr/TEST001
core/sql/regress/udr/TEST107

Added a parser rule for this case. Fortunately the new rule did not
increase the number of parser conflicts. Note that TMUDFs already
allowed delimited identifiers.

[TRAFODION-2517] Allow scalar UDFs with delimited identifiers

---

core/sqf/sqenvcom.sh

Some HDP installations d not have the directory /usr/hdp/current/hadoop-client/client .
Eg Hbase version  1.1.2.2.3.4.7-4
This caused errors when running Trafodion . 
This could be the result of changes due to the following 2 JIRAs
https://issues.apache.org/jira/browse/HDFS-9815
https://issues.apache.org/jira/browse/HDFS-6200

Change file location of Hadoop hdfs jar file [TRAFODION-2528]

---

core/sql/ustat/hs_cli.cpp

This change causes UPDATE STATISTICS to do an explicit BEGIN WORK before creating histogram tables and an explicit COMMIT WORK (or ROLLBACK) afterwards. This will help make UPDATE STATISTICS behavior immune to autocommit settings.

[TRAFODION-2530] Add explicit transaction control in CreateHistTables

---

core/sqf/sql/scripts/analyzeMessageGuide.py

This improves the report of where references to Optimizer messages occur.

[TRAFODION-2474] Add opt_error.h to files read by analyzeMessageGuide.py

---

core/sql/generator/Generator.cpp
core/sql/regress/hive/EXPECTED017
core/sql/regress/seabase/EXPECTED010

The problem was a query on a large table with a salted index chose a serial plan when a parallel plan on the salted index would have been superior.
The cause was a bit of missing logic. Function createNAFileSets (optimizer/NATable.cpp) relies on the presence of a files descriptor in the indexes descriptor to deduce that an index is salted. The code that generates these descriptors, Generator::createVirtualTableDesc (generator/Generator.cpp) however only creates a files descriptor for the clustering key or primary key indexes descriptor. So, the fix was to add logic to Generator::createVirtualTableDesc to create a files descriptor when a secondary index is salted.
Note that the only form of salting supported on indexes today is SALT LIKE TABLE. If in the future we add support for salting …

[TRAFODION-2537] Add file_desc to salted secondary indexes indexes_desc

---

core/sql/generator/GenRelExeUtil.cpp
core/sql/optimizer/ItemFunc.h

The default lob max size for "UPDATE LOB" operator should be 10000MB
rather than 10000B

[TRAFODION-2541]"UPDATE LOB" default max lob size error

---

core/sql/optimizer/ItemExpr.cpp

Scenario: A join on two tables, on a column that is badly skewed in one of the tables. The join predicate is of the form SUBSTR(skewedcolumn,1,n) = SUBSTR(othercolumn,1,n). We use the default distribution for this predicate, so we miss an opportunity to use skew buster.
The fix simply allows the base table column statistics to be used in this case.

[TRAFODION-2552] Use column stats when SUBSTR takes a column prefix

---

core/sql/optimizer/BindItemExpr.cpp
core/sql/regress/core/FILTERRTS

The binder transformation for RIGHT was incorrect in the case where the length parameter exceeds the character length of the string parameter.
Also in this change is a filter tweak to core/TESTRTS due to a new RMS counter, "SQL Heap WM".

[TRAFODION-2559] Fix bug in RIGHT function

---

core/sqf/sql/scripts/analyzeULOG.py
core/sql/common/wstr.cpp
core/sql/common/wstr.h
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp
core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h
core/sql/ustat/hs_read.cpp

This pull request submits a performance enhancement to the UPDATE STATISTICS utility. This work is the completion of a prototype originally done by Barry Fritchman (@blfritch).
For the moment, the feature is turned off by default. Use CQD  USTAT_COMPARE_VARCHARS 'ON' to turn on this enhancement.
What this feature does is compact varchars in memory for the internal sort code path in UPDATE STATISTICS. In the old code, varchars are expanded out to their full length. (Actually, we already truncate them at 256 characters -- the setting of CQD USTAT_MAX_CHAR_COL_LENGTH_IN_BYTES -- giving up some accuracy in UEC computation perhaps but improving performance dramatically for very long varchar columns.) In the new code, we estimate the average length of the column, and allocate space assuming the …

[TRAFODION-2376] Improve UPDATE STATS performance on varchar columns

---

core/sql/langman/LmLangManagerJava.cpp
core/sql/langman/LmLangManagerJava.h
core/sql/src/main/java/org/trafodion/sql/udr/LmClassLoader.java
core/sql/src/main/java/org/trafodion/sql/udr/LmUtility.java
core/sql/src/main/java/org/trafodion/sql/udr/predef/JDBCUDR.java

Two changes in the custom Java class loader used for UDRs.
First, the class loader now adds any jar files stored in
$TRAF_HOME/udr/public/external_libs to its CLASSPATH.
The choice of this directory is anticipating work on
isolated UDFs, see TRAFODION-2561.
Second, the custom class loader LmClassLoader now uses
java.net.URLClassLoader to do most of the work. This allows
us to delete a lot of code in this file. When this class
was first written, many years ago, the URLClassLoader was
probably not yet available.
Finally, with the new class loader, the JDBC predefined
UDF can also be simplified.

TRAFODION-2534 CLASSPATH for Java UDRs

---

core/sqf/sql/scripts/analyzeOptimizerTrace.py
core/sql/optimizer/ScmCostMethod.cpp

This adds some temporary code for UPDATE costing.
The existing code returns a constant value for cost on all UPDATE operations; it is a stub that was put in when the predecessor product was ported to Hadoop and HBase. The temporary code is a copy of the costing code for DELETE. It is being put in because we have an immediate need for parallel UPDATE plans in a particular application, which you don't get with the current stub.
This temporary code, of course, uses the DELETE theory of operation, which understates the costs for UPDATE in general. So it is a stop-gap until better code can be written.
To turn on this code, one must issue CQD HBASE_UPDATE_COSTING 'ON'. Without this CQD, the old stub, a constant cost of 1e32, will be used.

[TRAFODION-25] Temporary code for UPDATE costing

---

core/sql/ustat/hs_globals.cpp

This change affects the SELECTs that UPDATE STATISTICS generates when computing aggregates on long character and varchar columns. We now truncate the string before doing aggregation. (Note: We already do this in other code paths in UPDATE STATISTICS -- namely internal sorts and sample table population. This particular code path was overlooked.)
Besides improving performance, this will avoid UPDATE STATISTICS failing due to lingering engine issues concerning long varchars and sorts.

[TRAFODION-2575] Truncate long strings when computing USTAT aggregates

---

install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/configuration/traf-cluster-env.xml
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/configuration/trafodion-env.xml
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/params.py
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/trafodionmaster.py

Based on python-installer, added these to config:
ZOOKEEPER_NODES
ZOOKEEPER_PORT
SECURE_HADOOP
CLUSTERNAME

[TRAFODION-2577] Add missing config variables in Ambari install

---

install/python-installer/configs/prompt.json
install/python-installer/scripts/traf_ldap.py

[TRAFODION-2579] installers should allow multiple ldap hosts and ldap UID lines

---

core/sql/bin/SqlciErrors.txt
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ImplRule.cpp
core/sql/optimizer/IndexDesc.cpp
core/sql/optimizer/IndexDesc.h
core/sql/optimizer/OptHints.h
core/sql/optimizer/OptLogRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelScan.h
core/sql/optimizer/SimpleScanOptimizer.cpp
core/sql/optimizer/TableDesc.h
core/sql/optimizer/TransRule.cpp
core/sql/optimizer/memo.cpp
core/sql/optimizer/opt.cpp
core/sql/optimizer/opt.h
core/sql/parser/sqlparser.y
core/sql/regress/compGeneral/EXPECTED006.SB
core/sql/regress/compGeneral/EXPECTEDTOK2
core/sql/regress/compGeneral/TEST006
core/sql/regress/executor/EXPECTED063
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

Allowing hints in update and delete statements - they apply to the
scan of the table. Also making sure that heuristics to eliminate
indexes don't apply to indexes listed in a hint. Excluding the right
child of an index join when giving priority to plans that satisfy the
hint. Otherwise, an index join (index - base table) could be chosen
when the hint lists the base table.
Also removed some unused interfaces:
- no_log option in grammar, since it made changing the update syntax harder.
If we decide to implement incremental MVs in the future, we should use
a better parser or a different syntax for the no log feature.
- Some obsolete parser rules.
- Another set of hints in the scan node, in addition to those in the RelExpr.

[TRAFODION-2569] Improve handling of index hints

---

install/ambari-installer/mpack.json
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/configuration/trafodion-env.xml
install/ambari-installer/traf-mpack/common-services/TRAFODION/2.1/package/scripts/params.py

Also updates service number to match release number on master branch.
Common services remain as 2.1, since they work for 2.1+ releases.
This version of ambari installer specifies trafodion 2.2 for all
three HDP stacks.  If it becomes incompatible, then we should specify
2.1 for the older stacks.

[TRAFODION-2579] Allow multiple LDAP values in ambari-installer

---

core/sql/generator/GenPreCode.cpp
core/sql/optimizer/Analyzer.cpp
core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelScan.h
core/sql/optimizer/ScmCostMethod.cpp
core/sql/optimizer/SearchKey.cpp
core/sql/optimizer/SearchKey.h
core/sql/optimizer/ValueDesc.cpp
core/sql/optimizer/ValueDesc.h

2568 - Predicates that are always false at compile time will cause their scan to have begin and end keys reversed. No rows will be scanned. Idea due to Hans.
Files : ValueDesc.h/.cpp, SearchKey.h/.cpp and GenPreCode.cpp
2574 - Update on table with an index in which SET and WHERE clause contain an index key column can now get a index driven scan. Thank you Qifan and Hans for your help.
Files : NormRelExpr.cpp, RelExpr.cpp and RelScan.h
Two other minor changes that will help get index plans. I am not able to get reproducible test cases to open JIRAs on them. Thank you Eric and Dave for your help.
Files : ScmCostMethod.cpp and Analyzer.cpp
Thank you Ming for finding all these issues.

[TRAAFODION-2568] [TRAFODION-2574]

---

core/sqf/monitor/linux/zclient.cxx

retry 3 times when connecting to zookeeper.
@narendragoyal @zcorrea please review.

[TRAFODION-2588] monitor failed to start if part of zookeeper server is down

---

core/sql/executor/ExHdfsScan.cpp

[TRAFODION-2483] fix issue: '\'  is treated as NULL in hive table

[TRAFODION-2483] Trafodion treat '\' as NULL in hive table

---

docs/src/site/markdown/documentation.md
docs/src/site/markdown/download.md
docs/src/site/markdown/index.md
docs/src/site/markdown/release-notes-2-1-0.md
docs/src/site/markdown/release-notes.md

* Added new section to download page. Note: Right now these artifacts are not yet available on the mirror site, hopefully they will show up soon. Steve told me this usually takes a day or two.
* Added new section for 2.1.0 on the documentation page. Note: The links will not work if you build the site yourself, but should work when deployed on the actual site, since the site already has the 2.1.0 manuals in a docs/2.1.0 directory.
* Transferred release notes from wiki https://cwiki.apache.org/confluence/display/TRAFODION/Release+2.1 to the web site. Once the site is up I'll remove the text from the wiki and replace it with a link.
* Minor changes to main site.

[TRAFODION-2602] Update Trafodion web site with new 2.1.0 release

---

core/sql/regress/executor/DIFF140.KNOWN

It turns out the fix for this JIRA has a flaw. Not caching a query plan actually changes the plan! This shows up in executor/TEST140. This pull request provides a DIFFs file for that test. A permanent fix will be done later via JIRA TRAFODION-2605.

[TRAFODION-2294] Add known diffs file for executor/TEST140

---

core/sqf/sql/scripts/install_hadoop_regr_test_env

..to test for existence of ship_mode hdfs directory to decide whether to shortcut the hive setup process

Additional check in regr test env script [TRAFODION-2098]

---

docs/sql_reference/src/asciidoc/_chapters/introduction.adoc

Changes proposed in this pull request: 
1.  Add data-type mappings of hive and trafodion
- varchar
- char
- decimal (precision, scale)
- date

[TRAFODION-2549] update sql reference manual about new hive data type

---

core/sql/arkcmp/CmpStatement.cpp
core/sql/regress/executor/DIFF140.KNOWN
core/sql/regress/executor/EXPECTED140
core/sql/sqlcomp/CmpMain.cpp
core/sql/sqlcomp/CmpMain.h

This fix reworks part of the fix for JIRA TRAFODION-2294. It contains the following changes:
1. The "useQueryCache" logic at the sqlcomp/CmpMain.cpp level has been changed. Formerly, there were just two options, useQueryCache == TRUE and useQueryCache == FALSE. For EXPLAIN, we want to pretend like we are using the query cache, but at the last minute choose not to cache the plan. (In this way, we get the same query plan as would be in cache, without actually caching it and thereby opening the security hole that TRAFODION-2294 fixed.)
2. The known differences file for regression test executor/TEST140 has been removed.
3. The expected results file for test executor/TEST140 has been updated. In one place, we do an EXPLAIN after executing the same statement. The new logic picks up the cached …

[TRAFODION-2605] Rework of fix for TRAFODION-2294

---

core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/TransRule.cpp
core/sql/udrserv/udrserv.cpp

When pushing predicates into a scan node, it is not ok to copy the
index info of the original scan to the new scan node, since the
additional predicates may change the set of qualifying indexes.
Also, the method to copy the index info needs to copy the set of
computed predicates, since these are computed in the addIndexInfo()
method.
Also added a fix for TRAFODION-2625 to this PR. Sorry for combining these,
but it saves me a day in my workflow.

[TRAFODION-2616] Nested join regression after fix for TRAFODION-2569

---

core/sqf/sql/scripts/gensq.pl
core/sqf/sysinstall/home/trafodion/.bashrc

**rework jira 1860:**
missing ctime.pl file on CentOS7.
[trafodion@vmcentos7 ~]$ sqgen
Workstation environment - Not a clustered environment
Can't locate ctime.pl in @INC (@INC contains: /home/trafodion/trafodion-2.0.1/export/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./gensq.pl line 24.

rework of TRAFODION-2001

---

core/sql/common/NumericType.cpp
core/sql/exp/exp_conv.cpp
core/sql/exp/exp_math_func.cpp
core/sql/optimizer/ItemFunc.h
core/sql/optimizer/SynthType.cpp
core/sql/regress/core/EXPECTED038.LINUX
core/sql/regress/core/TEST038

Before this change, the Trafodion FLOOR/CEIL functions returned a floating-point data type. This is counter-intuitive since FLOOR/CEIL return an integer value. This makes it awkward to nest a FLOOR/CEIL call inside some other function (e.g. LEFT) which requires an integer data type.
Other DBMSs return an integer data type for FLOOR/CEIL.
Most of the work for this change is due to @nonstop-qfchen. I added a missing case in ExFunctionMath::eval.

[TRAFODION-2634] Change return type of FLOOR/CEIL to an integer type

---

core/sql/common/NAMemory.h
core/sql/optimizer/ControlDB.cpp

Fixing a memory leak found by Selva. See [[TRAFODION-2636]](https://issues.apache.org/jira/browse/TRAFODION-2636) for details. Also adding a method that helped me in debugging this issue.

[TRAFODION-2636] Memory leak in metadata context

---

core/sql/common/NAMemory.h
core/sql/generator/GenRelExeUtil.cpp
core/sql/generator/GenRelMisc.cpp
core/sql/generator/GenRelScan.cpp
core/sql/generator/GenUdr.cpp
core/sql/generator/Generator.cpp
core/sql/generator/Generator.h
core/sql/optimizer/NATable.cpp
core/sql/optimizer/RelScan.h
core/sql/optimizer/ValueDesc.cpp
core/sql/sqlcat/TrafDDLdesc.cpp
core/sql/sqlcat/TrafDDLdesc.h
core/sql/sqlcat/readRealArk.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

This set of changes fixes two bugs.
1.	In ValueIdList::computeEncodedKey (optimizer/ValueDesc.cpp), if we used HBASE.\”_CELL_\” access for a salted Trafodion table, and we had no begin/end key (e.g. select count(*) from hbase.\”_CELL_\”.\”TRAFODION.SCH.XYZ\”), the code would dereference a null pointer.
2.	In NATableDB::get, if we were creating an NATable object on the NATable cache for an HBASE.\”_CELL_\” access to a Trafodion table, the HBase-related descriptors were allocated on the statement heap instead of the context heap, resulting in a dangling pointer (with unpredictable failure modes) when the object was accessed that way in a second statement.
The change to optimizer/ValueDesc.cpp fixes the first bug.
The remaining changes fix the second bug.
Why so many changes for the second …

[TRAFODION-2635] Fix two bugs re: HBASE CELL access on Traf objects

---

core/conn/odb/src/odb.c

root cause: generated random index out of range.
fix by: narrow down random range, and the last element no need to be exchanged.

[TRAFODION-2639] parallelize commmands with randomizes execution order core dumped

---

core/conn/odb/src/odb.c

Whatever the precision of oracle timestamp's second is 0-9, the char buffer is like YYYY-MM-DD HH24:MI:SS.FFFFFFFFF.
So data size is always equal the display size of timestamp(9) ( SQL_TIMESTAMP_LEN + '.' + 9 for precision )

[TRAFODION-2035] Not able to copy table where there is column with type timestamp(0), error out with ERROR[8102]

---

core/conn/odb/src/odb.c

Linux use '\n' as LF, Windows use "\r\n" and Mac use '\r'.
It's not yet distinguished in code. So that data inserted will be wrong, or odb will crash because the buffer is too long but not divided.

[TRAFODION-1975] odb load error with different system formatted LF

---

core/conn/odb/src/odb.c

When using absolute path on windows such as src=d:/src.txt , ':' will be used as separator.
So I add judging condition to avoid dividing when ':' and '/' is apart.

[TRAFODION-2337] odb on windows can not use parameter with absolute path

---

core/conn/odb/src/odb.c

fix jira TRAFODION-2346 and TRAFODION-2373 bug as follows:
When using parallel, max rows/ parallel will cause rows cutting because of divisibility.
When using rowset, per thread rows/rowset will cause one more round contained the same rowset.
For example, rows = 5000 ,max = 500000 ,parallel = 6 :
per thread rows(size_t) = max rows / parallel = 500000 / 6 = 83333
round = per thread rows / rowset = 83333 / 5000 = 16 (actually do one more round)
Finally , 5000 * 17 * 6 = 510000 rows will be load and copy

[TRAFODION-2346] ODB copy incorrect rows when using rowset and parallel

---

core/sql/generator/GenPreCode.cpp
core/sql/generator/GenRelExeUtil.cpp
core/sql/optimizer/RelExeUtil.cpp
core/sql/optimizer/RelExeUtil.h
core/sql/optimizer/SynthType.cpp
core/sql/parser/sqlparser.y
core/sql/sqlcomp/CmpDescribe.cpp
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/sqlcomp/parser.cpp

-- REPLACE function max length is no longer limited to 32K
-- HBase object unregister was not working correctly. That is fixed.
-- class DDLExpr has been cleaned up to have one constructor for all cases.
All options are now set using flags instead of constructor params.
-- "showddl <tab>, explain " command now returns an error instead of crash.

Multiple fixes: REPLACE func maxlen, hbase unregister, DDLExpr cleanup

---

docs/sql_reference/src/asciidoc/_chapters/introduction.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_language_elements.adoc

1. Add "tinyint data type".
2. Fix some typos.

[TRAFODION-2548] Add tinyint data type for sql reference manual 

---

core/sql/arkcmp/CmpContext.cpp
core/sql/arkcmp/CmpContext.h
core/sql/cli/Context.h
core/sql/export/NAStringDef.cpp
core/sql/export/NAStringDef.h
core/sql/optimizer/HDFSHook.cpp
core/sql/optimizer/HDFSHook.h
core/sql/optimizer/NAClusterInfo.cpp
core/sql/optimizer/NAClusterInfo.h
core/sql/optimizer/NodeMap.cpp
core/sql/optimizer/ObjectNames.cpp
core/sql/optimizer/ObjectNames.h
core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/OptimizerSimulator.cpp
core/sql/optimizer/OptimizerSimulator.h
core/sql/optimizer/ScanOptimizer.cpp
core/sql/optimizer/ScmCostMethod.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

This set of changes does three things:
1. Increases the weight of cumulative MDAM probe costs by a factor of 3 (configurable via the new CQD MDAM_PROBE_TAX), to encourage consideration of MDAM plans on fewer key columns. This addresses the issue with the first query in this JIRA.
2. Changes the default of CQD MDAM_APPLY_RESTRICTION_CHECK from '2' to '0'. This heuristic was put in place before cumulative probes were taken into account for MDAM probes. Now that this is the case, and now that their weight has been adjusted above, this heuristic should no longer be needed. The heuristic prevents MDAM plans in some cases where they are beneficial, such as the second query in this JIRA.
3. The predecessor product contained a feature called the "Optimizer Simulator". This feature allows one to …

[TRAFODION-2655] Fix 2 MDAM optimizer bugs. Update optimizer simulator.

---

docs/sql_reference/src/asciidoc/_chapters/sql_language_elements.adoc

1. Add descriptions for `unit` and `char-set-name`.
2. Fix some mistakes based on AsciiDoc syntax.

[TRAFODION-2665] Update Character String Data Types

---

docs/sql_reference/src/asciidoc/_chapters/sql_utilities.adoc

Changes proposed in this pull request: 
1. Remove **Automating Update Statistics**

[TRAFODION-2657] Remove Automating Update Statistics for SQL Reference Manual

---

core/sqf/sql/scripts/gensq.pl
core/sqf/sql/scripts/rmscheck
core/sqf/sql/scripts/sqconfig
core/sqf/sql/scripts/sqgenrmscheck

It now generates the 'rmscheck.sql' logic in a temporary file which obtains the
node-ids from the 'trafconf' utility. The tempory file is created at 'rmscheck'
invocation.

[TRAFODION-2649] Fixed 'rmscheck' method for obtaining status

---

core/conn/odb/src/odb.c

root cause: "etab[eid].r = etab[eid].rbs / etab[eid].s" may be zero, this value will use for memory allocation and loop condition. so etab[eid].r = 0 is unreasonable, at least one.
fixed by: if etab[eid].r < 0 let it be 1.

[TRAFODION-2652] run cmd “./odb64luo -l src=nofile:tgt=ldata:map=map:max=300000:rows=K1:parallel=16” core dumped

---

core/sql/regress/compGeneral/FILTER023

The line wrap gods are fooling with this test. Added more patterns to the filter file allow for more places where line wrap may occur.

[TRAFODION-2662] Yet another attempt at fixing compGeneral/TEST023

---

core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/EXPECTED002
core/sql/regress/udr/TEST001
core/sql/regress/udr/TEST002

My earlier change for TRAFODION-2637 (PR #1141) caused a
non-deterministic failure of test udr/TEST001 and probably also
TEST002.
I added code that enables more parallel execution for TMUDFs.  The
tests have SELECT statements for these UDFs in them. Normally, the
logsort program sorts the output of these queries, so random
differences caused by parallel queries are ignored. However, some UDF
query have the keywords ORDER BY in them, not for the main query, but
for the inner query that is the child of the UDF. That suppressed
sorting and caused a difference.
The fix is to add an ORDER BY for the main query when we could expect
a non-deterministic order and when the child query of the UDF uses
ORDER BY.
@DaveBirdsall  suggested that we could also change the logsort program to
recognize …

Fix for udr/TEST001 test failure

---

core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h

This change improves the performance of incremental UPDATE STATISTICS by using "WITH NO ROLLBACK" when deleting rows from the persistent sample table.
A CQD, USTAT_DELETE_NO_ROLLBACK, has been added. When set to 'ON' (the default), we use DELETE WITH NO ROLLBACK on the persistent sample table. When set to 'OFF', we do the old behavior, that is, a vanilla transactional DELETE. This CQD is here mostly in order to test and verify the performance improvement. It can be removed later.
While I was at it, I noticed another CQD that is no longer used anywhere and removed it.

[TRAFODION-2673] Improve incremental update stats performance

---

core/sql/exp/ExpError.cpp
core/sql/exp/ExpError.h
core/sql/exp/exp_conv.cpp

Trying to give a better indication in some cases, to show
whether we exceeded the character limit or the byte limit.
The character limit is defined by a "precision" that is
a positive number.

[TRAFODION-2669] Improve error message 8402 - string overflow

---

core/sql/optimizer/HbaseSearchSpec.cpp

When extracting text, don't include any NUL (0) bytes in the result.

[TRAFODION-2675] Fix for seabase/TEST010 failure

---

core/sql/common/str.cpp
core/sql/common/str.h
core/sql/executor/MdamPoint.cpp
core/sql/executor/MdamPoint.h
core/sql/executor/ex_mdam.cpp
core/sql/nskgmake/Makerules.linux
core/sql/optimizer/ScanOptimizer.cpp
core/sql/optimizer/mdam.cpp

JIRA TRAFODION-1641 fixed an issue with MDAM costing, where MDAM costing was not accounting for the cost of recursion. That is, it was not accounting for the accumulated costs of probes as we recurse through a set of key columns. When analyzing that JIRA, I uncovered an issue with RangeSpec costing which I partially fixed.
JIRA TRAFODION-2655 tuned the above fix further, increasing the weight of the cost of accumulated probes. So for plans lacking RangeSpecs, or plans whose RangeSpecs lack ORs, MDAM costing should now be doing a much better job of picking prefixes when it should.
This fix addresses the last bit of the problem by addressing RangeSpecs. There was some code that was forcing MDAM plans to traverse all key columns when a RangeSpec containing an OR was present. I have simply …

[TRAFODION-2661] Improve MDAM costing for RangeSpecs

---

core/conn/odb/src/odb.c

root cause: write tag to file which had been closed.
fix by: don't close file until tag writing finished.

[TRAFODION-2679] odb crash when extracting data to xml file

---

core/sql/comexe/ComTdbExeUtil.cpp
core/sql/comexe/ComTdbExeUtil.h
core/sql/executor/ExExeUtilExplain.cpp
core/sql/executor/ExFastTransport.cpp
core/sql/generator/GenRelExeUtil.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/ItemOther.h
core/sql/optimizer/RelExeUtil.cpp
core/sql/optimizer/RelExeUtil.h
core/sql/optimizer/SynthType.cpp
core/sql/regress/executor/EXPECTED131
core/sql/regress/executor/EXPECTED140
core/sql/regress/executor/TEST131
core/sql/regress/executor/TEST140
core/sql/regress/hive/EXPECTED005
core/sql/regress/hive/EXPECTED009
core/sql/regress/hive/TEST005
core/sql/regress/hive/TEST009
core/sql/regress/seabase/EXPECTED031
core/sql/regress/seabase/TEST031

-- fix an issue where multiple values inserted from a list would return
error but each value inserted on its own would succeed.
ex: create table ts (a timestamp);
insert into ts values ('2017-01-01 10:10:10'), ('2018-01-01 10:10:10');
-- sometimes errors returned from child during hive inserts were not
being returned. That has been fixed.
-- TRAFODION-2683 extension.
added a 'p' (prune) option which would cleanse and filter unneeded
explain output. This helps in reducing output especially
for larger explains.
Ex:
>>explain option 'p' select * from dual;
------------------------------------------------------ PLAN SUMMARY
STATEMENT_NAME ........... NOT NAMED
STATEMENT ................ select * from dual;
------------------------------------------------------- NODE LISTING
ROOT …

Few fixes, details listed below.

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/sqltocconv.cpp
win-odbc64/odbcclient/drvr35/sqltocconv.cpp

Snprintf using sizeof(__int64) to set the max length of binding char to bigint with 8 chars.
It is too short for bigint.

[TRAFODION-2701] The maxlength for LargeInt was fixed to 8

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/sqltocconv.cpp

The offset will record the number of the chars returned,which have been translated from ucs2 to SQL_C_CHAR. When the function is called again to get the remaining chars, it  use the length of string without translation and the offset translated to calculate the number of the remaining chars.

[TRAFODION-2702]Fix wrong offset when the charset type is ucs2 in SQLTOC

---

core/sql/arkcmp/CmpStatement.cpp
core/sql/regress/seabase/EXPECTED002
core/sql/regress/seabase/TEST002
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

Traf now uses HBase truncate api to delete all rows from
a table and indexes, instead of dropping/recreating underlying HBase
objects.
A second change has also been added to fix a bug where compiler cache
was being cleared whenever a DDL statement was issued.
This change was added a while back before Query Invalidation(QI) feature
was available and was not removed when QI was added.
It has now been removed.

TRAFODION-2722 Change purgedata to use HBase truncate api

---

win-odbc64/odbcclient/drvr35/sqltocconv.cpp

For last PR , the bug on windows has not been mentioned

[TRAFODION-2702] fix wrong offset while converting sql to c with ucs2

---

core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

At compile time, the NATable layer has logic to construct a metadata definition when accessing native HBase tables via HBASE."_ROW_".objectName and HBASE."_CELL_".objectName syntax. Unfortunately, when calling the HBase client routines to read region key information, the HBASE._ROW_ and HBASE._CELL_ prefixes were passed down as part of the object name. So of course HBase could not find the object, and the Trafodion compiler would think there was only one region in the object. That would result in serial plans, even in the presence of cardinality hints.
The fix is to check for HBASE._ROW_ and HBASE._CELL_ prefixes, and if present, not pass them down to HBase when reading region keys.

[TRAFODION-2729] Fix bug reading region keys for hbase _ROW_, _CELL_ access

---

core/sql/regress/charsets/TEST014

an existing bug causes process loop when infer_charset is ON
and query invalidation needs to remove entries from query cache.
Until this bug is fixed, turn query_cache OFF.

fixed an issue that caused charsets/TEST014 to loop.

---

core/sql/ustat/hs_la.cpp

UPDATE STATISTICS generates several SQL statements internally. When referencing column names, the safest thing to do is to double-quote them, because sometimes we have SQL keywords serving as column names. Many code paths in UPDATE STATISTICS already do this; this particular change is for one that didn't.

[TRAFODION-2732] Add delimited identifier handling to sample table code path

---

core/sql/bin/SqlciMain.cpp
core/sql/bin/ex_ssmp_main.cpp
core/sql/cli/Cli.cpp
core/sql/cli/Context.cpp
core/sql/cli/Globals.cpp
core/sql/cli/Statement.cpp
core/sql/executor/ExStats.cpp
core/sql/executor/ex_esp_frag_dir.cpp
core/sql/executor/ex_ex.cpp
core/sql/executor/ex_exe_stmt_globals.cpp
core/sql/executor/ex_globals.cpp
core/sql/executor/ex_root.cpp
core/sql/executor/ex_send_bottom.cpp
core/sql/executor/ex_split_bottom.cpp
core/sql/executor/ex_split_top.cpp
core/sql/exp/ExpHbaseInterface.cpp
core/sql/runtimestats/CancelBroker.cpp
core/sql/runtimestats/SqlStats.cpp
core/sql/runtimestats/SqlStats.h
core/sql/runtimestats/sscpipc.cpp
core/sql/runtimestats/ssmpipc.cpp

RMS semaphore handling had the following:
1) Passed in parameters that are no longer used. It had these parameters for legacy reasons
2) Was returning errno for short return code. This might have caused unexplainable behavior
at times.
3) The caller was aborting for non-zero return value, but the return value is not easily visible.
All the above problems have been fixed in this PR.

[Trafodion 2739] RMS semaphore handling need to log the error for easy resolution of the issue

---

core/sqf/monitor/linux/cluster.cxx
core/sqf/monitor/linux/redirector.cxx
core/sqf/monitor/linux/reqqueue.cxx

The problems were:
1. A segmentation violation occurred during the Integration phase, when the new 
monitor is establishing the socket communication paths between itself and 
the existing monitors.
a. Information is exchanged between the master (creator) monitor and the
slave (new) monitor process which tells the new monitor which nodes
monitor process make up the existing cluster instance. During these
exchanges, in CCluster::ReceiveSock() one of the messages was large
enough to require chunking and the logic which kept track of the
number of bytes received was not calculated correctly which resulted
in an overwrite past the boundary of the receive buffer. 
2. A second segmentation violation was due to a buffer overwrite during the
Joining (revive) phase.
a. In requeue.cxx, when creating …

[TRAFODION-2746] Fixed various problem detected in large clusters (> 30)

---

win-odbc64/odbcclient/drvr35/drvrglobal.cpp
win-odbc64/odbcclient/drvr35/drvrglobal.h
win-odbc64/odbcclient/drvr35/sqltocconv.cpp

**_root cause:_** write stack variable out of range.
unsigned long ODBC::ConvertSQLToC(...., targetLength) {
...
CHAR	cTmpBuf[132];
...
double_to_char (dTmp, FLT_DIG + 1, cTmpBuf, targetLength) **// when targetLength > 132, the stack will be broken.**
...
}
**_fixed by:_** limit the max size to sizeof(cTmpBuf)
**_test result:_** run coast to check, no new issue introduced.

[TRAFODION-2725] SQL types are REAL, FLOAT, and DOUBLE. Some values are inserted, a stack overflow occurs when SQLGetData is executed.

---

core/sql/ustat/hs_globals.cpp

The code path in UPDATE STATISTICS where it creates multi-column histograms did not handle column names that happen to be reserved words correctly. These need to be double-quoted as delimited identifiers. (Oddly, vanilla delimited identifiers worked just fine.)

[TRAFODION-2749] Fix issue with reserved words as column names

---

core/conn/odb/Makefile
core/conn/odb/odb/odb.vcxproj
core/conn/odb/odb/odb.vcxproj.filters
core/conn/odb/src/JsonReader.c
core/conn/odb/src/JsonReader.h
core/conn/odb/src/odb.c

**1. Why support json?**
1. custormer needed.
2. JSON is a data inter-exchange format. When compared to XML, it is very lightweight and more human-readable.
**2. Why not use existing c json lib?**
Considered using the json-c and json-glibc, but seems neither them support stream parse.  For a large file, the memory may not enough.
**3. How odb support json loading function?**
1. Create table tbjson(id int, name char(20));
2. cat test.json
{
"test":[
{ "id":1 , "name":"hello" },
{ "id":2 , "name":"world" },
]
}
3. Load Command
./odb64luo -l src=test.json:tgt=tbjson:jsonkey=test
odb [parseopt(14249)] - Warning: this function is not fully tested "jsonkey"
odb [2017-09-18 15:28:39]: starting ODBC connection(s)... 0
Connected to Trafodion
[0] 2 records inserted [commit]
[0] odb version 1.1.0 …

[TRAFODION-2726] odb support to load json file

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceStatement.java

The jdbcT4 driver can't check the sql statement type succefully if the beginning of the query is 'with ... select'.

[TRAFODION-2757] Fix bug JDBC executeQuery() throws exception on the "with ... select" stmt

---

core/sql/ustat/hs_update.cpp

This change causes UPDATE STATISTICS to always set CQD ALLOW_NULLABLE_UNIQUE_KEY_CONSTRAINT 'ON' and CQD CONTROL QUERY DEFAULT CAT_ERROR_ON_NOTNULL_STOREBY 'OFF'.
This allows UPDATE STATISTICS to create a sample table with a nullable primary key (the first CQD) or a nullable STORE BY (the second CQD). In this way, the user does not need to remember to set these CQDs when doing UPDATE STATISTICS on a table that was created with either of these experimental features.

[TRAFODION-2762] Allow UPDATE STATS to create sample tables regardless

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

This change adds new heuristic code to ScanOptimizer::useSimpleFileScanOptimizer (optimizer/ScanOptimizer.cpp). The new code checks to see if a single subset scan uses all the key predicates in the query. If so, we don't bother to cost MDAM. But if not, we do consider MDAM.
The old code contained some (probably unintended) odd heuristics. Given a salted table with keys A, B and C, and a query SELECT * FROM T WHERE A = 5 AND C = 20, the old code would consider MDAM for serial plans but not for parallel ones! This is because in the serial case, a single subset would be a full table scan (so it is quite reasonable to try MDAM), but in the parallel case, because the "_SALT_" column would be covered by an equality predicate, the single subset SearchKey would have equality predicates on a …

[TRAFODION-2765] Change heuristics so MDAM is considered more often

---

docs/lob_guide/pom.xml
docs/src/site/markdown/documentation.md
pom.xml

These changes do the following:
1. Add an entry to the top-level pom.xml file so that the new Trafodion LOB Guide will get built as part of the documentation build (mvn post-site step).
2. Add an entry to the documentation.md file so that links to the new Guide will appear on the Trafodion documentation web page.
3. Change the lob_guide/pom.xml file to provide an appropriate name for the pdf file for the LOB Guide.

[TRAFODION-2771] Add build step and web site link for Trafodion LOB Guide

---

docs/lob_guide/pom.xml

The last pull request for this JIRA copied the LOB Guide to the sql_reference directory, overwriting the SQL Reference Manual. This one copies it to the right place on the web site.

[TRAFODION-2771] Fix lob_guide/pom_xml to copy LOB guide to right place

---

core/sql/optimizer/mdam.cpp

The problem is that during MdamKey::preCodegen we regenerate the disjuncts and expect to get the same number as we saw during optimize phase. This is mostly true, but in some cases not. There is some defensive code to handle this case, but it does not trigger when there is a partKey predicate. The fix removes the partKey predicate check for the defensive code.

[TRAFODION-2776] Mdam plans with more than one disjunct sometimes cause either a compiler core or have an incorrect predicate

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/regress/seabase/DIFF003.KNOWN
core/sql/regress/seabase/EXPECTED010
core/sql/regress/seabase/TEST010

This fix comments out some code that now causes non-determinstic failures in test compGeneral/TEST006. The essence of the bug is that queries against tables lacking statistics would non-deterministically flip to MDAM. The commented-out code contains several issues; rather than fixing them it seems more efficient to simply continue with the MDAM costing code rewrite which is occurring under JIRA TRAFODION-2645.

[TRAFODION-2777] Fix latent bug unmasked by JIRA TRAFODION-2765 fix

---

core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/executor/org_trafodion_sql_HTableClient.h
core/sql/src/main/java/org/trafodion/sql/HTableClient.java

and cqd traf_table_snapshot_scan 'latest' fail
Changed to pass two more arrays references - familyArray and QualifierArray
from Java to JNI to extract the family and the qualifier names correctly
on the native side

[TRAFODION-2801] select count(*) with cqd hbase_coprocessors 'off'

---

core/conn/odb/src/odb.c

in function Oload2:
```
static void Oload2(int eid)
{
.....
unsigned int nldr=0, /* number of loaders */
k=0, /* input file field number */
m = 0, /* rowset array record number */
i=0, /* loop variable */
....
while ( go ) {
size_t i = 0; //<----- the name conflict with outer scope name cause some bug
while (i < len) {
...
for(i=0;i<nldr;i++)
{ ... }
}
}
}
```

[TRAFODION-2797] odb variable name conflict

---

core/sqf/sqenvcom.sh

cache the output of 'hbase classpath' to a file under $TRAF_VAR/hbase_classpath, then sqenvcom.sh will get the hbase lib from this file if exists.

[TRAFODION-2806] optimize 'hbase classpath' cmd in sqenvcom.sh

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/ctosqlconv.cpp
win-odbc64/odbcclient/drvr35/ctosqlconv.cpp

When inserting NULL buffer to varchar, ODBC has not sent the real length of data to server.
Error: [Trafodion ODBC Driver][Trafodion Database] SQL ERROR:*** ERROR[8402] A string overflow occurred during the evaluation of a character expression.

[TRAFODION-2811] When convert NULL to SQL_VARCHAR, the length was not be sent

---

core/sql/bin/SqlciErrors.txt

Replace mention of predecessor products with Trafodion equivalents.

[TRAFODION-2814] Fix error message 2243

---

dcs/src/main/java/org/trafodion/dcs/Constants.java

Trafci connection failure,Check the DCS log,it shows:
2017-11-13 07:58:01,465, INFO, org.trafodion.dcs.server.ServerManager, Node Number: , CPU: , PIN: , Process Name: , , ,Server handler [1:4] is not running
2017-11-13 07:58:01,466, INFO, org.trafodion.dcs.server.ServerManager, Node Number: , CPU: , PIN: , Process Name: , , ,User program exec [cd /home/gongpj/incubator-trafodion/core/sqf;. sqenv.sh;mxosrvr -ZKHOST localhost:2181 -RZ workspace-gongpj:1:4 -ZKPNODE "/gongpj" -CNGTO 60 -ZKSTO 180 -EADSCO 0 -TCPADD 192.168.0.70 -MAXHEAPPCT 0 -STATISTICSINTERVAL 60 -STATISTICSLIMIT 60 -STATISTICSTYPE aggregated -STATISTICSENABLE true -SQLPLAN true -PORTMAPTOSECS -1 -PORTBINDTOSECS -1]
2017-11-13 07:58:01,533, INFO, org.trafodion.dcs.server.ServerManager, Node Number: , CPU: , PIN: , Process …

TRAFODION-2812 sqenv.sh file not found

---

core/sql/optimizer/RelRoutine.cpp
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLcommon.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp
core/sql/sqlcomp/CmpSeabaseDDLview.cpp

When CQD TRAF_MAX_CHARACTER_COL_LENGTH is set to a value lower than '500', then DROP TABLE will fail when it tries to do a DELETE under the covers on the SB_HISTOGRAMS table. The latter fails with error 4247, raised in CmpSeabaseDDL::getColInfo (sqlcomp/CmpSeabaseDDLcommon.cpp).
The fix is to change CmpSeabaseDDL::getColInfo to exempt metadata, histogram and repository tables from the maximum column length check.

[TRAFODION-2819] Fix 4247 error on drop table when certain CQDs are present

---

core/sql/executor/OrcFileReader.cpp
core/sql/executor/OrcFileReader.h
core/sql/executor/SequenceFileReader.cpp

The method Ids of the different Java classes are now initialized
in a thread safe manner in JNI layer.
The missing code to initialize the thread specific JNIEnv are added.

[TRAFODION-2821] Trafodion core code base needs to be thread safe

---

core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/RelExpr.cpp

This pull request contains two changes:
1. Views defined using [first n] or [any n] are now marked as not updatable and not insertable. So, when a MERGE statement is attempted on a new view of this type, we will get a compile time error that the view is not insertable or updatable (instead of getting an incorrect result).
2. MERGE statements that have a WHEN NOT MATCHED INSERT action are prevented from undergoing a tuple substitution transformation (that is, the TSJRule and TSJFlowRule will not fire on a merge node possessing a WHEN NOT MATCHED INSERT action). This is necessary because the run-time implementation of insert actions takes place in the merge node itself; that is, scanning has to happen in the merge node. These two rules would take the scanning out of the merge node into a …

[TRAFODION-2822] Make [first n] views non-updatable; prevent bad MERGE plans

---

core/sqf/sql/scripts/beheadMergeConflict.py

Very often a conflict occurs because a test has been updated in two branches, and that test has output containing DDL timestamps or plan IDs or other unimportant information that varies on every regress run. When these are the only differences, the conflict resolution is simple: Delete all the HEAD stuff and accept all the new stuff. This script does exactly that.
The script looks for lines of the following form:
```
<<<<<<< HEAD
-- Definition current  Wed Nov 29 08:53:46 2017
=======
-- Definition current  Wed Dec  6 19:32:34 2017
>>>>>>> b149874... [TRAFODION-2827] Turn update costing code on by default
```
When it finds this, it removes the lines from <<<<<< HEAD to ======, and removes the final >>>>>> line, leaving just:
`  -- Definition current  Wed Dec  6 19:32:34 2017`

[TRAFODION-2835] Add script to aid in merge conflict resolution

---

.gitattributes
doap.rdf
docs/src/site/site.xml

The project DOAP file was created from template at:
https://projects.apache.org/create.html
That page also says it should not be included in source/binary packages,
hence it is excluded from git export used to create source product.

[TRAFODION-2831] Add project DOAP file for inclusion in ASF project list

---

core/sql/optimizer/NATable.cpp

This will prevent cores in  NATable::updateExtTableAttrs when an error occurs under the NATable constructor for a Hive table that has a Trafodion external table definition.

[TRAFODION-2838] Add error check to NATableDB::get

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/drvrglobal.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/drvrglobal.h

the root cause is that the fcvt and gcvt are not threading safe, but double_to_char also has other issue fixed in [TRAFODION-2725](https://github.com/apache/incubator-trafodion/pull/1220), so we apply the fixed in [TRAFODION-2725](https://github.com/apache/incubator-trafodion/pull/1220).

[TRAFODIION-2828] Multi-threaded batch loading causes the program to crash

---

core/sqf/sql/scripts/sqgen
core/sqf/sql/scripts/sqstart

sometimes the hbase classpath may get updated,  the cache file will be obsolete. Now we clean the cache file during 'sqstart/sqgen'

additional fixes to [TRAFODION-2806]

---

core/conn/odb/src/odb.c

odb will try to get max(splitby) and min(splitby) to split to multithread,  we can apply pwhere condition in this stage to improve performance.

fix TRAFODION-2830

---

dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/PropTest.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestNetworkTimeout.java
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestWrap.java

some classes in incubator-trafodion/dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test do not close statement and connection, which will lead to no connection can be use.
classes include : 
PropTest.java
TestNetworkTimeout.java
TestWrap.java

TRAFODION-2823 some test case donot close connection

---

core/sql/cli/Cli.cpp

CLI entry points to LOB and Sequence generator didn't deallocate
the local diags area.

[TRAFODION-2853] Memory leak of ComDiagsArea in Context

---

core/sqf/sql/scripts/analyzeMessageGuide.py

This allows the script to search for references to certain messages using these enums as well as the numbers themselves.

[TRAFODION-2856] Add optimizer/UdrErrors.h to analyzeMessageGuide.py

---

core/sql/generator/GenRelUpdate.cpp

When load returns an error during insert, the row is reconstructed
to log in the same format as the source. During the reconstruction process
a wrong tuple format was used.

[TRAFODION-2854] Load encounter Operating system error 201

---

core/sqf/sql/scripts/analyzeMessageGuide.py

Ignore trailing spaces in message text and documentation text.
Take into account multiple substitution fields in message text and documentation text by replacing them with '.elided.' (before they were simply removed).

[TRAFODION-2875] Fix inaccuracies in comparison in analyzeMessageGuide.py

---

core/sqf/build-scripts/build.branch

[TRAFODION-2876] suppress the output of color control code from command `git branch` in file core/sqf/build-scripts/build.branch.

[TRAFODION-2876] suppress the output of color control code

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

-1 no longer denotes FOREVER in HBase. Please see JIRA for an explanation.

[TRAFODION-2868] bug of hbase option TTL

---

core/seamonster/src/Makefile
core/sql/nskgmake/executor/Makefile
core/sql/nskgmake/tdm_sqlmxevents/Makefile

Because the SP_EXPORT_LIB is empty.
make a build error, as:
mkdir -p        ##(SEAMONSTER)
mkdir: 缺少操作数       ##(SEAMONSTER)
请尝试执行"mkdir --help"来获取更多信息。        ##(SEAMONSTER)

[TRAFODION-2892] remove code about SP_EXPORT_LIB

---

core/sql/bin/SqlciErrors.txt
core/sql/sqlcomp/CmpDDLCatErrorCodes.h
docs/messages_guide/src/asciidoc/_chapters/ddl_msgs.adoc

Removed unused messages from the code.
Added messages 1719 and 1720. Added some other DDL messages that snuck in since the last time I visited their range or that I couldn't resolve on my first pass. Tweaked text in a couple of other messages.

[TRAFODION-2895] Update Message Guide for messages 1700-1721 + some others

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp
dcs/src/test/jdbc_test/src/test/java/org/trafodion/jdbc_test/TestGetIndexInfo.java

Table TRAFODION.\"_MD_\".INDEXES only has column "is_unique", but the output column is NON_UNIQUE.

[TRAFODION-2911] Catalog Api gives wrong values about NON_UNIQUE column

---

core/sql/generator/GenRelMisc.cpp

In some plans the Assign node binding happens in the generator. The fix added prior in PR  https://github.com/apache/incubator-trafodion/pull/1330  
Was not sufficient to cover this case.

Fix for a second case for Trafodion-2832.

---

core/sql/optimizer/ScanOptimizer.cpp
core/sql/optimizer/ScanOptimizer.h
core/sql/sqlcomp/nadefaults.cpp

There are two changes in this pull request.
1. The default value for CQD MDAM_SELECTION_DEFAULT has been changed from 0.5 to 8.0. This is a recalibration of this default; it had not been changed since predecessor product days. The old value resulted in MDAM not being considered at times when it is the better plan. Details of how this recalibration was done will be documented in the JIRA.
2. The heuristic implemented by IndexDesc::pruneMdam is now limited to index elimination logic and no longer used by the scan optimizer. As a practical matter this was already true in most circumstances: ScanOptimizer::getMdamStatus ignored the mdamFlag when CQD RANGESPEC_TRANSFORMATION is set to 'ON'. (And 'ON' is the default value for that CQD.) The one case when this was not true was if CQD FSO_IN_USE …

[TRAFODION-2913] Tweak some MDAM-related heuristics

---

core/sql/nskgmake/SqlCompilerDebugger/Makefile

make sure the QT_TOOLKIT set and execute the command as following:
cp -f ../$(basename $(CMPGUI_OBJ))/$(LIBPREFIX)$(notdir $(obj)) $(CMPGUI_FINAL)

[TRAFODION-2919] fixed a negligible error when compile without setting QT_TOOLKIT

---

core/conn/odb/src/odb.c

**the root cause**:  the allocating size of str is determined by max field length + 128(here is 1500+128), but during loading, str will be filled with actual field data exceeding this size(here maybe 2000 characters) if str overflow the client app will crash. 
**solution**: increase the size of str to the size of one-time fread(default is 262144). there is still a risk of a crash when a user provides an incredibly large size of an invalid field.
**additional fix**: also fix other same type potential bugs in Oload2 and OloadJason.

Trafodion 2916

---

docs/src/site/markdown/download.md

As Seth pointed out on the user list, I missed updating paths on the
downloads web page.  The old release names still have "incubating" in
the dir and file names, but the whole trafodion dist site has moved
out of the incubator directory.

[TRAFODION-2857] Remove remaining "incubator" path on downloads page

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Statement.java

The batchRowCount array is used to store rowcount for each batch sql comman,it should be the return value of ist_.getRowCount() . BatchRowCount_new twice, apply for extra memory.

TRAFODION-2922 fix return incorrect affect row count

---

core/sql/generator/GenPreCode.cpp
core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/Inlining.cpp
core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelMisc.h

JIRA TRAFODION-2822 attempted to make views containing [first n] in the select list non-updatable. It missed one case, the case where both [first n] and ORDER BY are present in the view definition.
The reason it missed that case is because of a design oddity in how [first n] is implemented. When there is no ORDER BY clause, the Binder pass introduces a FirstN node into the query tree. But if an ORDER BY is present, it defers doing this to the Generator. That means any FirstN-related semantic checks in earlier passes will not be applied when ORDER BY is present.
This set of changes refactors the FirstN implementation a little bit so that the FirstN can be introduced in the Binder when ORDER BY is present. Then the check added in JIRA TRAFODION-2822 will apply, and such views will be marked …

[TRAFODION-2840] Make [first n] with ORDER BY views non-updatable

---

core/sql/optimizer/NormItemExpr.cpp
core/sql/optimizer/NormRelExpr.cpp
core/sql/regress/udr/EXPECTED103
core/sql/regress/udr/TEST103
core/sql/regress/udr/TEST103_functions.cpp

Fix some issues found by Andy Yang and others while writing a
non-deterministic scalar UDF (a random generator in this case).
This UDF was transformed into a hash join, which executes the UDF
only once and not once per row. Another problem is the probe cache,
which can also lead to a single execution instead of once per row.
The fix records the non-deterministic UDF attribute in the group
attributes and it adds checks in the normalizer to suppress the
conversion from a TSJ to a non-TSJ when non-deterministic UDFs are
present. The probe cache logic already had this check, so all that was
needed was to set the attribute.
Note that there may be some more complex queries where we still won't
execute the UDF once per row. In general, there is no absolute
guarantee that a non-deterministic …

[TRAFODION-2912] Better handling of non-deterministic scalar UDFs

---

core/conn/odb/src/odb.c

**root cause:** max rows were divided into each thread may cause etab[eid].mr < etab[eid].r, so even only one-time fetch, the actual fetched rows will exceed max row of each thread.
**fixed by:** limit etab[eid].r less or equal to etab[eid].mr.

[TRAFODION-2939] odb copied data exceeds the max size specified by max option when copying data from oracle to Trafodion

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceStatement.java

we met a bug, when the server return without value, will make a null point error.

[TRAFODION-2936] nullpointer error where server return without value

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4Properties.java

if the given value is 32768 throw err msg : org.trafodion.jdbc.t4.TrafT4Exception: Invalid connection property setting: Incorrect value for connectionTimeout set: [40001]. Max value is: [32767]

TRAFODION-2932 ConnectionTimeout value for jdbc cannot lager than 32768

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

DATE precision expect: 10 and actual: 11
TIME precision expect: 8 and actual: 9
TIMESTAMP precision expect: 19 and actual: 20

[TRAFODION-2903] correct Column_Size fetched from mxosrvr

---

core/conn/odb/Makefile
core/conn/odb/src/odb.c

**root cause:** During building extract command, odb tool will try to split the task into multithread if parallel, but the parallel is equal 1 here,  so it should still go to single thread branch. 
**fixed by:**  only if parallel bigger than 1, odb go splitting branch.
**Aditional fix:**  make code cleaner and odb support g++ 4.8.5

[Trafodion-2937] the actual copied data is less than expected when copying data from MySQL to Trafodion

---

install/python-installer/scripts/traf_ldap.py

Fix the code that sets the TRAF_AUTHENTICATION flag to YES if LDAP is enabled.

TRAFODION-2962 : Enable LDAP authentication flag at install time

---

core/sql/regress/hive/EXPECTED018

A side effect of https://github.com/apache/trafodion/pull/1414 is that [first n] + ORDER BY queries are now considered non-cacheable. (Queries with [first n] but without ORDER BY have always been non-cacheable.) This caused a failure in hive/TEST018, as a query that was formerly cacheable is now not.
This change updates the expected results for hive/TEST018.

[TRAFODION-2840] Update expected results for test hive/TEST018

---

core/sql/executor/ex_hash_grby.cpp

Hash partial groupbys now report their row count in operator-level
statistics. These are not considered BMOs, so they need to use the
generic stats entry, not the BMO stats, to report the row count.

[TRAFODION-2965] Fix row count stats for partial groupby

---

core/sql/ustat/hs_log.cpp

Instead of passing raw data as a message template to the logging layers, pass "%s", and then pass the raw data as a parameter. That prevents misinterpretation of substrings that look like printf format strings, avoiding cores.

[TRAFODION-2967] Fix CommonLogger::buildMsgBuffer core in UPDATE STATS

---

core/sql/optimizer/BindRelExpr.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelMisc.h
core/sql/regress/core/EXPECTED002.LINUX
core/sql/regress/core/TEST002

Formerly, a [first n] in a subquery in a SELECT list resulted in an internal error in the Normalizer. The problem was that the Normalizer method Subquery::transformToRelExpr was not expecting a FirstN node at the top of the subquery tree.
Besides the fact that the Normalizer doesn't like it, having FirstN above the GroupByAgg node that enforces the one-row cardinality rule doesn't make sense.
In this set of changes, the FirstN node is placed underneath the GroupByAgg node when it matters. For [first n] / [any n] where n > 1, we can simply throw the [first n] / [any n] away, since the subquery already enforces at most one row semantics. For [first 1] and [last 1], we need to insert the FirstN node below the GroupByAgg node so that we narrow the result set down to one (or zero) rows before …

[TRAFODION-2969] Fix interaction of [first n] etc. with subqueries

---

core/sql/optimizer/ScanOptimizer.cpp

The new MDAM costing code was not respecting CONTROL QUERY SHAPE directives to force MDAM. This has been fixed.

[TRAFODION-2966] Fix new MDAM costing code to respect CQS forces

---

core/sql/bin/SqlciErrors.txt
core/sql/common/ComSmallDefs.h
core/sql/lib_mgmt/src/main/java/org/trafodion/libmgmt/JDBCUDR.java
core/sql/optimizer/BindRelExpr.cpp
core/sql/regress/udr/EXPECTED002
core/sql/regress/udr/TEST002
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLroutine.cpp
core/sql/sqlcomp/CmpSeabaseDDLroutine.h
core/sql/src/main/java/org/trafodion/sql/udr/LmT2Driver.java
docs/messages_guide/src/asciidoc/_chapters/binder_msgs.adoc

Roberta pointed out that we have two predefined UDFs, EVENT_LOG_READER
and JDBC, where the system administrator should have the ability to
control who can execute these functions.
To do this, these two UDFs cannot be "predefined" UDFs anymore, since
those don't have the metadata that's required for doing grant and
revoke.
Roberta also pointed out that the JDBC UDF should refuse to connect to
the T2 driver, for security reasons.
The fix leaves the predefined TMUDFs in place, for now, they will be
removed in R2.4 (see TRAFODION-2975).
The new "real" TMUDFs are in the "_LIBMGR_" schema, mostly for
convenience, as this schema has other UDFs that are created when
Trafodion is initialized.
Note for reviewers: The new JDBCUDR.java file is the same as the existing file, except for the package …

[TRAFODION-2974] Make event log reader and JDBC real TMUDFs

---

core/sql/generator/GenPreCode.cpp
core/sql/optimizer/RelExpr.cpp

This fix changes GroupByAgg::tryToPullUpPredicatesInPreCodeGen (optimizer/RelExpr.cpp) to make sure that characteristic inputs needed to calculate characteristic output expressions are not removed.
It also makes a small improvement to some ValueId Equivalence Group (VEG) debugging code.

[TRAFODION-2983] Be careful to preserve inputs needed for output computation

---

core/sql/common/NAString.cpp

The routine LineBreakSqlText (common/NAString.cpp) was inserting a line break after the decimal point in a numeric constant, making one token into two. The code has been changed to distinguish between a dot that separates two identifiers (a legitimate place to insert line breaks) and decimal points.

[TRAFODION-2990] Fix CREATE TABLE LIKE having long numeric default constant

---

core/sql/executor/ExExplain.cpp

SELECT * FROM TABLE(explain(null, 'EXPLAIN_QID=MXID11000007019212384153894533416000000002206U3333308T150010100_923_SQL_CUR_2'));
this is related to TRAFODION-1755

TRAFODION-2981 mxosrvr crashes during explain using EXPLAIN_QID

---

core/sql/bin/SqlciErrors.txt
core/sql/generator/GenRelUpdate.cpp
core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp
core/sql/sqlcomp/CmpSeabaseDDLtable.cpp

This set of changes fixes several minor bugs:
1. The key length limit that Trafodion imposes differed from the HBase limit. They are now the same.
2. CREATE INDEX logic lacked a check on key length. This has now been added.
3. There was a typo in the message text for message 1141 preventing the computed key length from being displayed. This has been fixed.
4. There was a bug in the generator where, if CREATE INDEX were allowed to have a long key, we generated plans to populate that index that would overrun their buffers, causing ESPs to core. This has been fixed; we now guarantee that buffers are long enough for at least one row.

[TRAFODION-2977] Fix issues with maximum key length detection

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

This option does not do anything in Trafodion.

Removing the "WITH PARTITIONS" syntax description

---

core/sql/optimizer/Inlining.cpp

The inlining code for index maintenance in one place was assuming a record descriptor (RETDesc) for new values existed for a MERGE DELETE statement lacking a "when not matched" clause. But no such record descriptor exists, since there are no values being updated or inserted. That place has been changed to use the old record descriptor.

[TRAFODION-3000] Fix binder issue with index maintenance on MERGE DELETE

---

core/sql/exp/exp_function.cpp

Wrong implementation in the sleep runtime code. And made it not able to be built on CentOS 7 because of bad data type conversion.

[TRAFODION-2998] sleep execution code cannot build on CentOS 7

---

core/sql/ustat/hs_globals.cpp

Formerly, UPDATE STATS would fail with an internal error when processing an INTERVAL DAY(13) TO SECOND(0) column. It would also fail with a core when processing an INTERVAL DAY(8) TO SECOND(0) column. This has been fixed.

[TRAFODION-3002] Fix UPDATE STATS for certain INTERVAL data types

---

core/sql/sqlcomp/CmpSeabaseDDL.h
core/sql/sqlcomp/CmpSeabaseDDLindex.cpp

This is a follow-on to JIRA TRAFODION-2977 (pull request https://github.com/apache/trafodion/pull/1473).
I made two changes here.
1. In the previous pull request, I added a check to the CREATE INDEX logic to make sure the key length is not too long. I put that check too early in the logic. I have now moved that check to the proper place.
2. It turns out that HBase uses rowIDs + possibly the HBase object name + some other info to make entries into another HBase structure internally, and imposes a 32767 key length limit on that. Unfortunately when we exceed the length limit on that internal structure, the HBase application (Trafodion in our case) experiences a hang. To avoid these hangs, we will further restrict maximum key length in Trafodion to 32000. The code change contains a detailed …

[TRAFODION-3005] Fix issues with keys on long columns

---

core/sql/exp/exp_function.cpp

Wrong input param for strptime, null pointer

[TRAFODION-3006] unix_timestamp runtime core dump issue

---

core/sql/optimizer/BindItemExpr.cpp

The BuiltinFunction::bindNode method inserts Cast nodes with the matchChildType flag on on top of the operands of any function that can be affected by substituting another equal value. For example, OCTET_LENGTH is sensitive to this: While 'ax' = 'ax   ' from a SQL point of view, the two values have different octet lengths so we want to force the data type of any substitution to whatever was there originally. The Upper::bindNode method removes the Upper node when its operand already has the Upshift attribute. The bug is, Upper::bindNode wasn't also removing the Cast inserted by BuiltinFunction::bindNode on its behalf. This lead to trouble at code generation time when an UPPER function on an upshifted column was used in an equi-join predicate on a hash join.
The fix is to change …

[TRAFODION-3018] Fix issue with UPPER on an UPSHIFT column

---

core/sql/bin/SqlciErrors.txt
core/sql/executor/ExExeUtilGet.cpp
core/sql/executor/HBaseClient_JNI.cpp
core/sql/executor/HBaseClient_JNI.h
core/sql/exp/ExpHbaseInterface.cpp
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java
core/sql/src/main/java/org/trafodion/sql/TrafRegionStats.java

get region stats command was populating the errors in the
queue entry directly, but still used handleErrors() to populate the
errors again in the HANDLE_ERROR_ state.  In some cases, the diagnostics
area wasn't populated too.
In CDH5.4, when the table is purged, the region info wasn't returned. This commit is expected to fix the core files seen with seabase/TEST002

[TRAFODION-3009] Streamline error handling in Executor utility commands

---

core/sql/sqlcomp/CmpSeabaseDDLroutine.cpp
core/sql/sqlcomp/CmpSeabaseDDLroutine.h
install/python-installer/scripts/traf_start.py

Updated initialize trafodion, upgrade library management to modify the
jar/dll file locations for all system libraries to the new location.
Changed python installer to call ..., upgrade library management during
an upgrade operation

[TRAFODION-2249] Cannot use library management SPJs after an upgrade

---

docs/src/site/site.xml

This adds the ApacheCon (or whatever ASF current event is next) icon on the top-right of the web pages, opposite of the Dragon logo.
Icon can be previewed here: https://www.apache.org/events/current-event-125x125.png

[TRAFODION-3022] Add web site link to Apache Current Events

---

core/sql/common/ExprNode.cpp
core/sql/common/OperTypeEnum.h
core/sql/generator/GenShape.cpp
core/sql/optimizer/ControlDB.cpp
core/sql/optimizer/RelExpr.cpp
core/sql/parser/sqlparser.y

Adding fast_extract() and hive_insert() CQS operator syntax to be able to force shapes of Hive insert statements.
Example:
control query shape hive_insert(cut);
explain insert into hive.hive.t values(1,1);
Note: I don't think this fix works for UNLOAD, since that seems to be
an "ExeUtil" statement that gets executed in two phases.

[TRAFODION-3028] Support CONTROL QUERY SHAPE (CQS) for Hive insert

---

core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelSet.h
core/sql/regress/core/EXPECTED005.SB

Make UNION, INTERSECT, EXCEPT cacheable.

[TRAFODION-3021] union, intersect, except should be cacheable

---

core/sql/exp/exp_function.cpp

When called without a seed, we use a seed based on the system timestamp. The random generator we use generates similar output values for seeds that are close together. Adding another randomization step to avoid that.
Also switched from a microsecond to a nanosecond-based timestamp.

[TRAFODION-3042] RAND() function is not always random

---

core/sql/common/DTICommonType.cpp
core/sql/optimizer/SynthType.cpp

This change adds a check to Extract::synthesizeType (optimizer/SynthType.cpp) to raise a 4037 error if one attempts to perform DATE_PART on an Interval data type with an extract qualifier of YEARMONTH or YEARQUARTER.

[TRAFODION-3043] Add missing binder check for DATE_PART function

---

core/sql/optimizer/ItemExprList.cpp
core/sql/optimizer/NATable.cpp
core/sql/optimizer/OptPhysRelExpr.cpp
core/sql/optimizer/PartFunc.cpp

This change adds a Cast node on top of the data value passed to CompEncode, insuring that it is the proper data type. This resolves an issue that was causing a compile-time core in the PCode evaluator. Also included is some debug code concerning range partitioning functions.
Thanks go to @zellerh for this code.

[TRAFODION-3052] Fix core in PCode evaluator

---

core/sql/parser/sqlparser.y

Disable this syntax that is no longer supported, so that we don't
get a core dump in debug builds. This caused a core every time I
ran the core/TEST019 regression test on a debug build.

[TRAFODION-510] Internal error or core dump with set table timeout

---

core/sqf/src/trafconf/tcdbsqlite.cpp
core/sqf/src/trafconf/tctrace.cpp
core/sql/sqlcomp/CmpSeabaseDDLmd.h

There are some coding cannot be compiled using GCC in CentOS 7.
We need to continuously check and fix these issues until CentOS7 is supported and jenkins test established.

[TRAFODION-3061] eliminate building errors on CentOS7

---

core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_log.h

When RMS is absent, UPDATE STATISTICS either fails with an internal error 9200 or cores.
This set of changes adds code to UPDATE STATISTICS so that it will ignore any 2024 warnings returned by the Executor due to RMS being absent.

[TRAFODION-3056] Change UPDATE STATISTICS to tolerate absence of RMS

---

core/sql/optimizer/GroupAttr.h
core/sql/optimizer/NormRelExpr.cpp

When a query has at least three levels of subquery, and when the subqueries are transformed from semi-joins to inner-joins, we may see an Optimizer assertion failure warning (2053) when preparing the query. This bug has been there for a long time but is more likely now due to the changes in https://github.com/apache/trafodion/pull/1530.
The problem is that when transforming a semi-join to an inner-join + group by, the new GroupByAgg node was getting its GroupAttributes as a copy of the child node. If the child node happened to also be a Join (as would happen with nested subqueries), the numJoinedTables_ field for the GroupByAgg's GroupAttributes would remain 2 or more. If during optimization, the GroupByOnJoinRule fired, pushing the GroupByAgg down, we end up with another Join expression …

[TRAFODION-3066] Fix bug that causes 2053 warning on deeply nested subqueries

---

core/sqf/src/seatrans/hbase-trx/pom.xml.cdh54
core/sqf/src/seatrans/hbase-trx/pom.xml.cdh55
core/sqf/src/seatrans/hbase-trx/pom.xml.cdh57

The various pom.xml.cdh<version> file can be used as pom.xml for maven input, to build protobuf java output for hbase-trx.
As we want to modify the .proto to add a new coprocessor, we found that it failed with ERROR:
Caused by: java.lang.UnsupportedClassVersionError: org/apache/hadoop/maven/plugin/protoc/ProtocMojo : Unsupported major.minor version 52.0
And the plug-in information is 
[INFO] --- hadoop-maven-plugins:3.1.0:protoc (compile-protoc) @ hbase-trx-cdh5_4 ---
So the lasted Hadoop maven plugins for protoc is 3.1.0 which need JDK 1.8.
It also means the pom.xml.cdh<version> files should be updated to match the Hadoop-Maven-plugin version same as its hadoop version, instead of using latest version (without specifying the version tag)

[TRAFODION-3054] update pom.xml.cdh for hbase-trx to build protobuf

---

core/sql/exp/exp_bignum.cpp
core/sql/regress/executor/EXPECTED016.SB
core/sql/regress/executor/TEST016

When the column is BIGNUM, and the predicate is comparing to a string. Trafodion cast the string into FLOAT and the convert FLOAT into BIGNUM, 
There is an issue when convert FLOAT into BIGNUM that didn't considering the rounding:
so 2.73804679999999968E+007 will become 27380467 instead of 27380468

[TRAFODION-3015] query no result when comparing string with BIGNUM

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

SendEventMsg use dynamic parameter.
And there is a parameter control the total, all of dynamic parameters are string data type.
But some place input a number parameter for it.
I checked it again and found two such mistakes.

[TRAFODION-3039] SendEventMsg is used in a wrong way

---

core/sql/optimizer/ValueDesc.cpp

ValueIdList::convertToTextKey (optimizer/ValueDesc.cpp) in some cases was encountering INTERVAL literal values containing the text "INTERVAL ... < qualifier >". The code expects this text to be there in some code paths but not all. With this change, I've taken care of the remaining code paths. So we should no longer see data conversion errors in the cases noted in the JIRA.

[TRAFODION-3088] Fix data conversion issue with INTERVAL literals

---

docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

The CQD `CACHE_HISTOGRAMS_REFRESH_INTERVAL` has been removed.

[TRAFODION-3085] Add Examples for *CONTROL QUERY DEFAULT Statement* in *Trafodion SQL Reference Manual*

---

core/sql/optimizer/NormRelExpr.cpp
core/sql/optimizer/RelMisc.h
core/sql/regress/core/EXPECTED002.LINUX
core/sql/regress/core/TEST002

ORDER BY in subquery is ignored by Trafodion, when in the subquery, there is a limit N, it is good to keep the order by:
select * from t ( select * from t order by c limit 20);
for example

TRAFODION-3025 support order by with limit N in subquery

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/CONNECTION_CONTEXT_def.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InitializeDialogueMessage.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceConnection.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceResultSet.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4DSProperties.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/T4Properties.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TRANSPORT.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Statement.java
core/conn/odbc/src/odbc/Common/Global.h
core/conn/odbc/src/odbc/Krypton/generated_incs/odbcCommon.h
core/conn/odbc/src/odbc/nsksrvr/Interface/odbcs_srvr.cpp
core/conn/odbc/src/odbc/nsksrvr/SrvrConnect.cpp
core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

When fetching varchar type data from SQL engine, mxosrvr will apply for enough memory to ensure that the data can be stored, regardless of the actual varchar length.Then send such a large piece of data to jdbct 4.This results in unnecessary network overhead and JDBC memory usage.
So I added a function to clip the resulting data. The data to be sent to JDBCT4 in mxosrvr is trimmed to reduce network overhead and memory consumption.This function cuts out the redundant parts of varchar type data, and is very useful for the case where varchar is very long but actually occupies very little.
I added a switch to jdbct4 code to turn this function on and off according to the situation.
I tested my code with phx

[TRAFODION-3096] clip the varchar type data from mxosrvr to jdbct4

---

core/sqf/monitor/linux/cluster.cxx
core/sqf/monitor/linux/pnode.cxx
core/sqf/src/seatrans/tm/hbasetmlib2/testrun.cpp

Some new code checkin broke the build on CentOS 7
I will continously monitor the CentOS 7 build until the jenkins setup.
CentOS 7 jenkins test now failed on some UDR regression, it is hard to find out root cause yet, still need some time.

TRAFODION-3111 CentOS 7 build error

---

core/sql/optimizer/RelExpr.cpp

For query " insert into to t1 select seqnum(seq1, next) from t1;", there is no SORT as left child of TSJ, and it is a self-referencing updates Halloween problem.  In NestedJoin::genWriteOpLeftChildSortReq(), child(0) producing no outputs for this query, which means that there is no column to sort on. So we  solve this by having the source for Halloween insert produce at least one output column always.

[TRAFODION-2901] Self-reference Holloween problem fix

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/cconnect.cpp
win-odbc64/odbcclient/drvr35/cconnect.cpp

SQLConnect returns failure when the connection string has an incorrect value  which is"sessionName":"10".
The sessionName is an uninitialized variable.

[TRAFODION-3124] initialize session name in connection string

---

win-odbc64/Install/win64_installer/installer.iss

Now the directory for certification is set as "SYSTEM_DEFAULT"
User can only alter it by altering registry or add in connection string.
So a set of Installer is necessary.

[TRAFODION-3108] Windows ODBC Installer add widget to choose directory for certification

---

core/sql/common/NAWinNT.h
core/sql/common/wstr.cpp
core/sql/optimizer/EncodedValue.cpp

When an INTERVAL SECOND(m,n) column participates in a multi-column histogram, EncodedValue::constructorFunction (optimizer/EncodedValue.cpp) did not properly scan for the comma delimiter between column values, resulting in 6003 warnings. This has been fixed; we now ignore commas within sets of parentheses.

[TRAFODION 3128] Fix issue with interval literals in multi-column histograms

---

core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_read.cpp
core/sql/ustat/hs_update.cpp

This pull request contains two changes:
1. It removes obsolete static SQL code from two ustat modules (hs_read.cpp and hs_update.cpp). It also removes obsolete metadata version checking code. Thanks to @anoopsharma00 for these changes.
2. It fixes a bug in incremental UPDATE STATISTICS. If one has a table name containing a dot (.), incremental UPDATE STATISTICS fails. For example:
```
>>update statistics for table "A.B" on existing columns incremental where a > 128;
*** ERROR[15005] Unmatched quote in input (unterminated string): 
select count(*) from B" where  a > 128;
--- SQL operation failed with errors.
>>
```
This bug has been fixed (hs_globals.cpp). Thanks to @anoopsharma00 also for this change.

[TRAFODION-3138] Part 1 of removing static SQL code from ustats + one bug fix

---

core/sql/parser/sqlparser.y
core/sql/regress/core/EXPECTED002.LINUX
core/sql/regress/core/TEST002

Just as the title shows, it is to support limit n in subquery.

[TRAFODION-3133] limit n support in subquery

---

core/sql/ustat/hs_la.cpp

This fixes a bug concerning sample tables created by UPDATE STATISTICS on Hive tables.
When a Hive table had a column named "_DIVISION_1_" (or any other reserved Trafodion column name), the UPDATE STATISTICS command would fail if a sample table needed to be created. The failure would occur because we would not include "_DIVISION_1_" etc. in the select list of the UPSERT/SELECT statement used to populate the sample table.
This has been fixed.

[TRAFODION-3148] Fix UPDATE STATS bug on Hive tables w/ column _DIVISION_1_

---

core/sql/parser/sqlparser.y

Change the parser production for CREATE EXTERNAL TABLE to point to the proper token for the optional IF NOT EXISTS clause.

[TRAFODION-3153] Fix issue with CREATE EXTERNAL TABLE

---

core/sql/executor/ExExeUtil.h
core/sql/executor/ExExeUtilGet.cpp
core/sql/regress/compGeneral/EXPECTED023
core/sql/regress/core/EXPECTED116
core/sql/regress/executor/EXPECTED130
core/sql/regress/hive/DIFF009.KNOWN
core/sql/regress/hive/EXPECTED007
core/sql/regress/hive/EXPECTED009
core/sql/regress/privs1/EXPECTED123
core/sql/regress/privs1/EXPECTED125
core/sql/regress/privs1/EXPECTED132
core/sql/regress/privs1/EXPECTED136
core/sql/regress/privs1/EXPECTED141
core/sql/regress/privs2/EXPECTED135
core/sql/regress/privs2/EXPECTED138
core/sql/regress/privs2/EXPECTED140
core/sql/regress/privs2/EXPECTED143
core/sql/regress/privs2/EXPECTED144
core/sql/regress/privs2/EXPECTED146
core/sql/regress/seabase/EXPECTED011
core/sql/regress/seabase/EXPECTED012
core/sql/regress/seabase/EXPECTED022
core/sql/regress/seabase/EXPECTED031
core/sql/regress/udr/EXPECTED001
core/sql/regress/udr/EXPECTED102
core/sql/regress/udr/EXPECTED103
core/sql/regress/udr/EXPECTED107.SB

At field, engineers issue get tables to list all tables, and want to count how many tables got, it will be good to show that info by 'get' command itself.
The current implementation is to show that count as part of get command output, just as header info.

[TRAFODION-3101] enhance get command to show rows get

---

core/sql/generator/GenPreCode.cpp
core/sql/optimizer/ItemFunc.h
core/sql/regress/core/EXPECTED038.LINUX
core/sql/regress/core/TEST038

**Before this, the result of below SQL are incorrect:**
```
>> select split_part('aaabbcc', 'bb', -2) from dual;
Expr
------
--- 1 row(s) selected.   (error)
```
**for now,** 
```
>> select split_part('aaabbcc', 'bb', -2) from dual;
*** ERROR[8691] Field position must be greater than zero, currently is -2.
--- 0 row(s) selected.
```
`

[TRAFODION-3136] Bug fixed:  If position is a negative value, the result does not match expectations.

---

core/sql/optimizer/EncodedValue.cpp
core/sql/optimizer/EncodedValue.h

This pull request makes two code changes to function EncodedValue::constructorFunction.
1. Formerly, the function would check for the existence of an error in CmpCommon::diags() and remove it if present. This wasn't sufficient though as the test case in the JIRA generated *two* errors in CmpCommon::diags(); the code as it was removed only one of them. The result was that the Normalizer retried the query, and the warnings concerning the bad histogram values were lost.
2. In my initial attempt to fix this problem, I put an unguarded call to CmpCommon::diags()->mark() to capture the state of CmpCommon::diags() on entry to EncodedValue::constructorFunction. This turned out to cause cores in the mxssmp process at sqstart time, because in that process it happened that the EncodedValue …

[TRAFODION-3158] Make EncodedValue error handling more robust

---

core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_globals.h

If the "_HIVESTATS_" schema didn't already exist, UPDATE STATISTICS ... CREATE SAMPLE and UPDATE STATISTICS ... REMOVE SAMPLE would fail with weird errors.
With this change, they now will succeed. The "_HIVESTATS_" schema and associated histogram tables will be created automatically.

[TRAFODION-3152] Fix bug in UPDATE STATISTICS CREATE SAMPLE

---

core/conn/odb/src/odb.c

**root cause:** SQLGetDiagRec expected an error message buffer length parameter which type is signed short, but odb defined a macro LINE_CHUNK as 51200 and this macro will be pass to SQLGetDiagRec as error message buffer length parameter,  51200 is a negative value for signed short, so no error message returned.
**solution:** define a new macro ERR_MSG_LEN with a small value for SQLGetDiagRec function.

[TRAFODION-3710] odb don't report error message.

---

core/sql/executor/ExSequence.cpp
core/sql/executor/ExSequence.h
core/sql/executor/cluster.cpp
core/sql/executor/cluster.h

ERROR[8427] [2018-07-23 15:52:16]
will now be more descriptive 
*** ERROR[8427] Sequence Scratch IO Error occurred. Scratch Error: -10005, System Error: 13, System Error Detail: 0, Details: SQScratchFile::SQScratchFile 3
--- 0 row(s) selected.

[TRAFODION-3166] enhance 8427 error detail when thrown by sequence operator

---

core/conn/odbc/src/odbc/nsksrvr/SrvrMain.cpp
dcs/src/main/java/org/trafodion/dcs/master/DcsMaster.java

This code adds a zookeeper value to signal to mxosrvr processes
when it is time to exit. This allows to phase out processes when
things in the environment change. The process will wait until it
is idle before exiting.

[TRAFODION-3164] Restart mxosrvrs on-demand

---

core/sql/generator/Generator.cpp
core/sql/generator/Generator.h
core/sql/optimizer/BindRI.cpp
core/sql/sqlcat/TrafDDLdesc.h

In my previous fix to TRAFODION-1858, I add a new method to check if a column is a system column by comparing the column name with "_SALT_", "_DIVISION_" etc, that is not a good way.
This is a new implementation, it use more robust way to tell if a column is a system column.
To check the RI, the predicate only need to check the user specified Primary Column.

[TRAFODION-1881] A better way to solve TRAFODION-1858

---

core/sql/executor/ExExeUtilCli.cpp

enhance the ExeCliInterface get method to return NULL ptr for NULL value.
So the caller is able to determine the null value.
This is only for the fetchAllRow interface, where later the caller need to call OutputInfo method get, instead of adding a new array to save null indicator, I choose to reuse the data_ pointer

[TRAFODION-3175] enhance ExeCliInterface get interface to return null indicator

---

core/sqf/monitor/linux/cluster.cxx
core/sqf/monitor/linux/redirector.cxx

At field, when we want to do trafodion trouble shooting. Open mon.xxx.log file, in many times, it is flood with message related STDIN redirection entries.
These log entries are never real issues, and it is very hard to understand, so this PR is to move these log entries into DEBUG level. 
So only when an expert want to debug very complicated issue and need to turn-on the DEBUG log/trace, these info will be printed out.
I am trying to make log file more useful, this is the first attempt.

[TRAFODION-3182] cleanup monitor log content

---

core/sql/executor/ex_tuple_flow.cpp

The original code lacks the ref count increment, compared the correct code, so add it now.

[TRAFODION-3187] increase the ref count

---

core/sql/exp/exp_clause_derived.h
core/sql/exp/exp_like.cpp

Previously, each time evaluate a row, it needs to invoke the regcomp(), by this change, only when the pattern is changed, invoke the regcomp()

[TRAFODION-2404] enhance the regexpr performance

---

core/sql/executor/ExExeUtilCli.cpp

I had a wrong understanding of the outputInfo class, so a wrong 'fix' in TRAFODION-3175
it can save as many rows , the numEntries is for columns, not rows

[TRAFODION-3201] fix wrong understanding of code in TRAFODION-3175

---

docs/cqd_reference/src/asciidoc/_chapters/operational_controls.adoc
docs/cqd_reference/src/asciidoc/_chapters/query_plans.adoc

[TRAFODION-3191] Correct Syntax Descriptions for *DEFAULT_DEGREE_OF_PARALLELISM* in *Trafodion CQD Reference Guide*

---

win-odbc64/odbcclient/drvr35/cstmt.cpp

Windows ODBC won't initialize the variable before a new statement while Linux ODBC have this operation.

[TRAFODION-3209] The variable of won't be initialized before a new statement

---

core/sql/regress/privs2/EXPECTED135
core/sql/sqlcomp/PrivMgrPrivileges.cpp
core/sql/sqlcomp/PrivMgrPrivileges.h

Fixed issue where revoke all on object did not actually revoke the privilege.
Also fixed an issue where setting up default privileges did not set the
correct default bits for object type.

TRAFODION-3194 update

---

core/sql/executor/ex_frag_rt.cpp
core/sql/regress/tools/regress-filter-linux
core/sql/src/main/java/org/trafodion/sql/HBaseClient.java

The estimateRowCount code in HBaseClient.java tried to scale down row counts by the proportion of non-Put cells in the file. That is, it was trying to estimate row count from cell count, in part by discounting the effect of Delete tombstone cells. It was doing this on the basis of a sample of 500 rows in one HFile.
We find, however, that with time-ordered data that is aged out, the Delete cells are not uniformly distributed but instead tend to clump in one place. If we are unlucky and get an HFile that begins with 500 Delete tombstones, we will incorrectly assume most of the table consists of deleted rows and drastically underestimate the number of rows.
Drastically underestimating can be very bad. It is much better to overestimate. So the code that attempted to scale down row count based …

[TRAFODION-3223] Don't scale down for non-Puts when estimating row counts

---

core/sqf/monitor/linux/redirector.cxx
core/sqf/monitor/linux/shell.cxx
core/sql/regress/privs1/Utils.java

* Fix a wrong variable name in regression test code.
* Revert the original changes to monitor redirector that caused loss of some stdout data.
* Change monitor shell to put persistent process logs in TRAF_LOG.

[TRAFODION-2626] Fix regressions

---

docs/sql_reference/src/asciidoc/_chapters/sql_functions_and_expressions.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_language_elements.adoc
docs/sql_reference/src/asciidoc/_chapters/sql_statements.adoc

IS_IPV6:
```
SQL>SELECT IS_IPV6('10.0.5.9'), IS_IPV6('::1') from dual;
(EXPR) (EXPR)
------ ------
0      1
--- 1 row(s) selected.
```
INET_ATON:
```
SQL>SELECT INET_ATON('10.0.5.9') from dual;
(EXPR)
----------
151322634
--- 1 row(s) selected.
```
INET_NTOA:
```
SQL>SELECT INET_NTOA(167773449) from dual;
(EXPR)
---------------
9.5.0.10       
--- 1 row(s) selected.
```
ALTER TABLE Statement:
```
SQL>showddl float_1;
CREATE TABLE TRAFODION.SCH.FLOAT_1
( 
A                                DOUBLE PRECISION DEFAULT NULL NOT
SERIALIZED
)
ATTRIBUTES ALIGNED FORMAT 
;
-- GRANT SELECT, INSERT, DELETE, UPDATE, REFERENCES ON TRAFODION.SCH.FLOAT_1 TO DB__ROOT WITH GRANT OPTION;
--- SQL operation complete.
```
```
SQL>alter table FLOAT_1 alter column a REAL;
--- SQL operation complete.
```

[TRAFODION-3229] Update *Syntax Descriptions* for *FLOAT* in *Trafodion SQL Reference Manual*

---

dcs/bin/dcs
dcs/src/main/jamon/org/trafodion/dcs/tmpl/server/ServerStatusTmpl.jamon
dcs/src/main/jamon/org/trafodion/dcs/tmpl/servermt/ServerStatusTmpl.jamon
dcs/src/main/java/org/trafodion/dcs/Constants.java
dcs/src/main/java/org/trafodion/dcs/http/HttpServer.java
dcs/src/main/java/org/trafodion/dcs/master/DcsMaster.java
dcs/src/main/java/org/trafodion/dcs/server/DcsServer.java
dcs/src/main/java/org/trafodion/dcs/servermt/DcsServer.java
dcs/src/main/resources/dcs-webapps/master/servers.jsp

Previous change allowed configuration of log location, but did not
take into account retrieving logs via DCS web interface.
Link to trafodion logs is not exposed by default, but this change was tested
with that option enabled, as well as default.

[TRAFODION-2626] Fix DCS API for $TRAF_LOG

---

core/conn/odb/src/odb.c

the parameter of SQLGetDiagRec need to be initialized

[TRAFODION-3230] The number of error message is less than the failed input rows

---

core/sql/exp/ExpLOBaccess.cpp
core/sql/regress/executor/EXPECTED130
core/sql/regress/executor/TEST130

Remove code that renames the lob data file when an empty_blob is created. 
When allocating the descriptor for a new empty_blob entry, the lob data file was being renamed. That is incorrect since the lob data file can contain data from other  lob entries in the column. (There is one single lob data file for each LOB column and it can hold several blob entries in it).   So remove the code that  does this and simply update the descriptor files to have an entry which keeps the LOB offset and leave the LOB length as 0. This way we know the LOB is empty . If data is appended to it, the data will go into a new offset within that data file.

[TRAFODION-2408] Remove code that empties the LOB data file when creating an empty_blob.

---

core/sqf/sql/scripts/hbcheck

When you were executing hbcheck, you see an error saying "file exists" as the JIRA described.

[TRAFODION-3240]hbcheck, file exists issue

---

core/sql/exp/ExpPCodeOptimizations.cpp
core/sql/regress/core/EXPECTED038.LINUX
core/sql/regress/core/TEST038

When an interval literal was referenced twice or more in an INSERT/SELECT in expressions with different INTERVAL types, the PCode optimizer was incorrectly treating the code to produce the interval literal value as a common subexpression, so the INSERT/SELECT would insert incorrect values. 
This has been fixed. The PCode optimizer common subexpression elimination logic now checks for commonality in datatype, scale and precision for INTERVAL conversions.
A test case that demonstrates the problem (with correct behavior with the fix) has been added to core/TEST038.

[TRAFODION-3237] Fix incorrect PCode optimization

---

core/conn/jdbcT4/pom.xml
core/conn/jdbcT4/src/assembly/slf4j.xml
licenses/lic-clients-bin

add a new jar which can use slf4j to print log

[TRAFODION-3246] add slf4j in jdbc

---

core/conn/jdbcT4/Makefile

it does not support TLSv1.1 since 2018-6-18. see : https://central.sonatype.org/articles/2018/May/04/discontinued-support-for-tlsv11-and-below/

[TRAFODION-3246] support TLS for jdbc

---

core/sql/cli/Statement.cpp

Add missing "return ERROR" (and an NADELETEBASIC to avoid memory leak) in method Statement::doHiveTableSimCheck.

[TRAFODION-3256] Fix error path in CLI similarity check code

---

core/sql/ustat/hs_globals.cpp
core/sql/ustat/hs_la.cpp

This pull request changes the access mode on all SELECTs against a base or sample table from READ UNCOMMITTED ACCESS  to SKIP CONFLICT ACCESS. Since the engine today maps READ UNCOMMITTED ACCESS to READ COMMITTED ACCESS, this change will improve the concurrency of data ingest operations with UPDATE STATISTICS.

[TRAFODION-3266] Change ustats base table accesses to SKIP CONFLICT ACCESS

---

core/sql/generator/GenPreCode.cpp

If we have a join predicate of incompatible types and nested join is chosen, we get an assertion failure in the Generator in debug builds.
This changes fixes that, by adding logic to handle incompatible types when generating key expressions.

[TRAFODION-3270] Handle incompatible types in key expressions

---

core/sql/regress/tools/logsort_src/line.c
core/sql/regress/tools/logsort_src/line.h
core/sql/regress/tools/logsort_src/logsort.c
core/sql/regress/tools/logsort_src/tokstr.c
core/sql/regress/tools/logsort_src/tokstr.h

The logsort tool is used by the developer regression suite testware to sort output in test logs that has non-deterministic order. Today it does so for SELECT statement output where the SELECT lacks an ORDER BY.
This pull request enhances logsort so that it also sorts the output of certain GET statements.

[TRAFODION-3261] Change logsort tool to sort GET statement output also

---

core/sqf/src/seabed/src/sock.cpp
core/sql/bin/ex_ssmp_main.cpp
core/sql/common/Ipc.cpp
core/sql/common/Ipc.h
core/sql/executor/ex_split_bottom.cpp
core/sql/runtimestats/ssmpipc.cpp

Encapsulated the changes in the commit 2ee272b325d021 to Ipc layer.
[TRAFODION-3274] At times sqlci or any other SQL process fails to come up and dumps core
It looks like there is a race condition in C++ main function prologue while
initializing the embedded global objects and the stdin, stdout and stderr file
descriptors.
File descriptor of value 2 is returned for epoll_create(). But, the error redirection
code possibly used this fd to redirect overriding the epoll fd.
This caused epoll_ctl to return EINVAL resulting in core dump of sql process.
Changed the global object gv_sock_ctlr to a global object pointer.

[TRAFODION-3260] SSMP may wait 3 seconds before handling requests

---

core/conn/odb/src/odb.c

**New Feature Description:** Now, the odb's -cp command supports "bad" option. For example, you can use below command to specify where to store the records that can't be loaded to Trafodion.
`./odb64luo -d dsn1:dsn2 -u user1:user2 -p passwd1:passwd2 -cp src=tb1:tgt=tb2:bad=badf`
The bad file records the 'bad' records in the CSV format. 
**Changes In odb:** New field ' **Octype**' to remember the C data type has been added to the '**struct tdesc**' to decode the batch buffer if failed to load the data to the target table later. Some variables were used for multiple purposes, now add new variables to separate it.
**Verification:** No new issue was introduced by running the odb regression test set. The new feature also works fine by current test cases.

[TRAFODION-3252] odb -cp command does not support writting to bad file

---

core/sql/generator/GenPreCode.cpp

In the fix for TRAFODION-3270, I did not take into account the possibility that a null value might be used as a key value in a primary key predicate. (Of course, such a value results in no rows, but nevertheless it is a valid predicate.)
This change corrects the fix for TRAFODION-3270.

[TRAFODION-3276] Fix regression introduced by [TRAFODION-3270]

---

win-odbc64/odbcclient/drvr35/Interface/odbcas_drvr.cpp
win-odbc64/odbcclient/drvr35/cconnect.cpp
win-odbc64/odbcclient/drvr35/cconnect.h
win-odbc64/security_dll/native/header/secpwd.h
win-odbc64/security_dll/native/source/secpwd.cpp

When the source length is the same as the target length, conversion always fails.

[TRAFODION-3238] ODBC correct the length used for convert GBK to UTF8

---

docs/src/site/markdown/download.md
docs/src/site/markdown/index.md

Update the web pages to use https for KEYS, sigs and hashes for archive locations.
Previous changes only affected the current release

Fix for [Trafodion-2997]

---

core/sql/bin/SqlciErrors.txt
core/sql/executor/ExHdfsScan.cpp
core/sql/exp/ExpErrorEnums.h
core/sql/ustat/hs_globals.cpp
docs/messages_guide/src/asciidoc/_chapters/executor_msgs.adoc

There are two changes in this pull request:
1. Fix a buffer overrun in ExHdfsScanTcb::work, which happens when we process a Hive row longer than we expect and that row spans read buffers. Now we will raise an 8457 error in this case.
2. A workaround to avoid error 8457 is to use CQD HIVE_MAX_STRING_LENGTH_IN_BYTES 'nnnn', setting nnnn to the length of the longest string in the Hive table. There was a bug in UPDATE STATISTICS ... CREATE SAMPLE where this particular CQD was not passed down to the appropriate tdm_arkcmp, defeating the workaround. This bug has been fixed.

[TRAFODION-3282] Fix buffer overrun in ExHdfsScanTcb::work

---

core/sqf/conf/sqconfig
core/sqf/sqenvcom.sh
core/sqf/sql/scripts/gensq.pl
core/sqf/sql/scripts/gomon.cold
core/sqf/sql/scripts/install_local_hadoop
core/sqf/sql/scripts/sqgen
core/sqf/sql/scripts/sqshell
core/sqf/sql/scripts/sqstart
core/sqf/sql/scripts/trafnodestatus
core/sql/regress/core/EXPECTED131
core/sql/regress/core/EXPECTEDRTS
core/sql/regress/hive/EXPECTED018
core/sql/regress/hive/FILTER018
core/sql/regress/seabase/DIFF025.KNOWN
core/sql/regress/seabase/EXPECTED031
core/sql/regress/tools/runallsb
core/sql/regress/udr/EXPECTED001
install/python-installer/scripts/traf_sqconfig.py

Changed workstation mode (aka install_local_hadoop aka ILH) to use
single-node configuration instead of virtual nodes.
* ILH script generates sqconfig for current node.
* template sqconfig file moved to config template dir.
* Updated expected files accordingly.
** Filed jira [TRAFODION-3283] for bug found.
Removed setting and use of SQ_VIRTUAL_NODES variable.
Removed virtual nodes support in sqgen.
Changed installer to not treat single-node clusters specially.

[TRAFODION-3281] Remove virtual nodes configuration

---

core/sql/exp/exp_eval.cpp
core/sql/exp/exp_ieee.cpp
core/sql/exp/exp_ieee.h

This change makes overflow checking on floating point datatypes for SUM (and AVG) consistent with floating point overflow checking elsewhere in the product.
To do so required inlining certain code in order to not regress performance.

[TRAFODION-3284] Make overflow processing for float SUM consistent

---

build_easily.sh

There are several unpleasant places when compiling the trafodion(not make package):
1. We need to redirect the make information manually,
otherwise the information will flood the screen
2. The build information mixed together so that we couldn't locate the build error quickly
3. We need to make all again when we fix a building error of one component.
This scripts could build trafodion component based.
And it will write the compiling information into build_log file.
Also you can continue to compile the remaining components which havn't been compiled by commented components which have finished compiled.

add a scripts to make trafodion build easily and Visualized

---

core/sqf/sql/scripts/install_local_hadoop

Earlier changes for this jira introduced syntax error in script
with spaces, where tabs are expected.

[TRAFODION-3281] Fix syntax error introduced in previous change

---

core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/InterfaceStatement.java
core/conn/jdbcT4/src/main/java/org/trafodion/jdbc/t4/TrafT4Desc.java
core/conn/trafci/src/main/java/org/trafodion/ci/DatabaseQuery.java
core/sqf/tools/sqtools.sh

- an extra msg 'pmd is null' no longer shows from trafci prepare execute
- trafci queries with multiple param no longer returns an 'invalid desc index' error
- changed reference to 'jave.sql.Varbinary' to 'java.sql.Varbinary'

fixes to trafci prepare/execute queries

---

core/conn/unixodbc/odbc/odbcclient/unixcli/cli/drvrglobal.cpp
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/drvrglobal.h
core/conn/unixodbc/odbc/odbcclient/unixcli/cli/sqltocconv.cpp
win-odbc64/odbcclient/drvr35/drvrglobal.cpp
win-odbc64/odbcclient/drvr35/drvrglobal.h
win-odbc64/odbcclient/drvr35/sqltocconv.cpp

**root cause:** original double_to_char is too complicated and with some bug. (for example, not thread-safe, memory overflow, precision lost)
**solution:** reimplement with a simpler one.
**verify:** had run a full regression of coast in CentOS 6 to verify the fix, no new issue was introduced by this fix and some other bug also been fixed. The regression on Windows is ongoing.

[TRAFODION-3262] Insert float to numeric(19,0) lost precision for some case

---

core/sql/cli/Globals.cpp

New member variables were not initialized in the CliGlobals constructor

Fix for cores seen with T2 JDBC applications caused by PR 1820

---

core/sql/bin/SqlciErrors.txt
docs/messages_guide/src/asciidoc/_chapters/binder_msgs.adoc

Added documentation for messages 4140 and 4141 to Messages Guide.
Edited text for a few others.
Marked several others as unused in bin/SqlciErrors.txt (as they are no longer used anywhere).

[TRAFODION-3297] Update Messages Guide for some more binder messages

---

core/sql/bin/SqlciErrors.txt
core/sql/regress/executor/EXPECTED001
docs/messages_guide/src/asciidoc/_chapters/binder_msgs.adoc

Added documentation for messages 4185, 4191, 4192, 4193.
Removed some unused messages from the code.
Edited the message text for a few others. In one case, this required an update to the expected results of one regression test.

[TRAFODION-3299] More improvements to binder messages in Messages Guide

---

core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/JtaXAResource.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/RMInterface.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/SsccTransactionalTable.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TrafodionLocationList.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionManager.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionState.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionalScanner.java.tmpl
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/client/transactional/TransactionalTable.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/coprocessor/transactional/SsccTableClientUtils.java
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/regionserver/transactional/TrxTransactionState.java.tmpl
core/sqf/src/seatrans/hbase-trx/src/main/java/org/apache/hadoop/hbase/util/ByteArrayKey.java
core/sqf/src/seatrans/tm/hbasetmlib2/javaobjectinterfacetm.cpp
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/HBaseTxClient.java
core/sqf/src/seatrans/tm/hbasetmlib2/src/main/java/org/trafodion/dtm/TmAuditTlog.java
core/sqf/src/seatrans/tm/hbasetmlib2/testrun.cpp
core/sql/executor/ExHbaseAccess.cpp
core/sql/executor/ExHbaseAccess.h
core/sql/executor/ExHbaseIUD.cpp
core/sql/executor/ExHbaseSelect.cpp
core/sql/qmscommon/QRLogger.cpp

Improvements in DTM register region concept.
1. TransactionalTableClient is retired. ttable in RMInterface is now HTable. SSCC transaction type might need some rework.
2. registerTransaction method is now refactored to reduce pathlength.
3. All the regions during scan are registered upfront at the time of scan instead of trying to figure out if new regions are accessed while the rows are processed.
4. Removed unnecessary synchronization of RMInterface methods.
5. Changed idTm to be one per process.
6. Changes in SQL layer to bypass the java layer when start row id is less than the end row id.
7. RegionList is now collected per table on the client side using HashMap instead of Set. This
allows client to register to TM the region only if it not already registered within a transaction.
Added …

TRAFODION-3280] Reduce path length in Trafodion for improved performance and scalability

---

core/sql/bin/SqlciErrors.txt
core/sql/cli/ExSqlComp.cpp
core/sql/comexe/FragDir.cpp
core/sql/comexe/FragDir.h
core/sql/common/Ipc.cpp
core/sql/common/Ipc.h
core/sql/common/IpcGuardian.cpp
core/sql/executor/ExCancel.cpp
core/sql/executor/ExExeUtil.h
core/sql/executor/ExExeUtilCommon.cpp
core/sql/executor/ExUdrServer.cpp
core/sql/optimizer/NodeMap.cpp
core/sql/runtimestats/ssmpipc.cpp
docs/messages_guide/src/asciidoc/_chapters/compiler_msgs.adoc
docs/messages_guide/src/asciidoc/_chapters/sqlstate.adoc

This pull request contains improvements to error reporting when a process server cannot be started. The following changes are made:
1. Logic in the compiler (optimizer/NodeMap.cpp) to compute node names has been corrected. Thanks to @sandhyasun for this change.
2. The correct node name is now reported in error messages 2012 and 2013 (common/IpcGuardian.cpp). Formerly, a hard-coded value of "NSK" was reported.
3. Redundant 2013 and 2002 error messages are no longer generated (common/IpcGuardian.cpp and cli/ExSqlComp.cpp).
4. Interpretive text has been added to error 2012 to give a more human-understandable reason behind certain common error codes (common/IpcGuardian.cpp and bin/SqlciErrors.txt).
5. The nodeName_ member in IpcGuardianServer is now computed at run time, and only if needed …

[TRAFODION-3308] Improve error reporting when a process cannot be started

---

core/sqf/sql/scripts/analyzeMessageGuide.py
core/sql/arkcmp/CmpErrors.h

Changed the error code symbols in arkcmp/CmpErrors.h to use an enum instead of "static const int". That makes it possible for the analyzeMessagesGuide.py script to know about these symbols when searching the code base for files that issue these errors.

[TRAFODION-3309] Convert arkcmp errors to enum

---

core/sql/generator/GenPreCode.cpp
core/sql/regress/core/EXPECTED116
core/sql/regress/core/TEST116
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

A CQD BEGIN_TRANSACTION_FOR_SELECT is introduced. This CQD can take a value 1,2 or any numeric value. Default is 1.
1 - means mark the statement as transaction required if it is SELECT ... FOR UPDATE
2 - means mark the statement as transaction required if it is SELECT statement with
isolation other than SKIP CONFLICT ACCESS or READ UNCOMMITTED ACCESS.
Any other value - SELECT statement is not marked to begin transaction.
Trafodion always change the isolation level to READ COMMITTED ACCESS when it is
READ UNCOMMITTED ACCESS.

[TRAFODION-3311] Trafodion to start transactions for select statements with FOR UPDATE

---

core/conn/odbc/src/odbc/nsksrvrcore/srvrothers.cpp

Frequently , during performance test runs like OE and other regression tests, following errors
are observed in master logs:
ERROR[8605] Committing a transaction which has not started.
ERROR[8609] Waited rollback performed without starting a transaction.
MXOSRVR does return success to the client for these errors but since commit/rollback is executed, the error gets logged.
Some of these can be avoided if mxosrvr implements the following ODBC standard and skips executing the commit/rollback statement.
"For drivers and data sources that support transactions, calling SQLEndTran with either SQL_COMMIT or SQL_ROLLBACK when no transaction
is active returns SQL_SUCCESS (indicating that there is no work to be committed or rolled back) and has no effect on the data source."

[TRAFODION-2311] Avoid logging error 8605 and 8609 during SQLEndTrans if no trans active

---

core/sql/optimizer/OptimizerSimulator.cpp

The problem: When a table has a unique constraint, OSIM generates both the ALTER TABLE statement to create the constraint and the CREATE INDEX statement for the system-generated index into CREATE_TABLES_DDL.txt. When we then do OSIM LOAD, the CREATE INDEX is executed, then the ALTER TABLE. The ALTER TABLE fails because the index already exists.
The fix: Don't write the CREATE INDEX to the CREATE_TABLES_DDL.txt file.

[TRAFODION-3314] Avoid generating redundant DDL in OSIM for unique constraints

---

core/sql/optimizer/OptimizerSimulator.cpp

When a Hive exception occurs in OSIM, OSIM puts out the rather unhelpful error message, "Error running Hive SQL." There is no clue given as to what the Hive difficulty is.
This pull request adds the Hive exception information to this message.

[TRAFODION-3315] Add Hive exception info to OSIM Hive error message

---

core/sql/ustat/hs_cli.cpp
core/sql/ustat/hs_cli.h
core/sql/ustat/hs_globals.cpp

Three fixes to UPDATE STATISTICS:
1. Add support for Hive TIMESTAMP data type. The only change needed is to tolerate a precision of 9 on a TIMESTAMP.
2. When creating a sample table on a small Hive table, the SAMPLING_RATIO recorded in SB_PERSISTENT_SAMPLES is incorrect. This happened because the estimated size for the table was off by two orders of magnitude. We calculated the sampling ratio from the number of rows returned in the sample and this estimated size. There was logic to adjust the estimated size of the table as well from the statistics of the sample SELECT, however that logic was stubbed out because it didn't work. That logic has been removed -- the design premise was flawed anyway because it does not take into account the possibility that a key predicate will be used in …

[TRAFODION-3316] Three fixes to UPDATE STATISTICS

---

core/conn/odb/src/odb.c

**root cause:**
odb create a 'etab' for each table to be extracted,  'etab' is execution table and the preallocated chunk is 8. When the number of the list tables bigger than 8,  odb will write to unallocated memory.
**solution:**
try to enlarge 'etab' array when trying to create a 'etab' for a table.

fix TRAFODION-3317

---

core/conn/odb/src/odb.c

**changes:**
1. add two options: 'mcfs' and 'mcrs' to specify the multi-character field separator and record separator.
2. add two functions: 'replace_escapes' and 'hextobin' to handle escape sequences in the separator.
3. currentFiledPos -> currentFieldPos 
**separator check algorithm:**
check last few characters in temp field buffer to see if we found a field separator and record separator.

[TRAFODION-3320] support multiple characters field and record separator when for data loading and extracting

---

docs/client_install/src/asciidoc/_chapters/odb.adoc

This change removes the line "AppUnicodeType=utf16" from the odbc.ini examples used for the odb utility with the Unix ODBC driver. It is no longer needed, and indeed odb no longer works correctly if this line is present.

[TRAFODION-3323] Remove AppUnicodeType=utf16 from Client Install Guide

---

core/sql/optimizer/RelExpr.cpp
core/sql/optimizer/RelExpr.h
core/sql/optimizer/opt.cpp
core/sql/sqlcomp/DefaultConstants.h
core/sql/sqlcomp/nadefaults.cpp

The problem is that sometimes join equality predicates are not converted into VEGs, and therefore do not get pushed down to their children. That prevents Scan::addIndexInfo from considering indexes when there are column references in the join predicate. That can result in missed opportunities to use efficient index plans and instead doing full table scans + hash joins.
My first attempt at fixing this problem was to generate an IS NOT NULL predicate for the children of such equality predicates, then attempt to push those down. This didn't work well: If the column was not nullable, logic in HBaseTable.java would try to optimize it out resulting in a null filter which resulted in an exception. Too, it also resulted in redundant predicates of the form \<constant\> = \<constant\> in explain …

[TRAFODION-3325] Pass down index hints for non-VEG equality predicates

---

core/sql/cli/Statement.cpp

The query compile timestamp was changed unnecessarily at times.

Fix for core/TEST131 test failure
